backend/refactor/#966 remove static driver bpp module
nammayatri/nammayatri pull request #1050
Opened 2023-05-30 16:47 UTC by Dwibedi-10

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description
Removed static offer BPP module.

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-30 17:20 UTC, DonDokidon requested changes
Please remove migrations, table startups and other things from `dev` folder, related to the thing

2023-05-30 17:22 UTC, srid approved these changes
Nix changes approved.

2023-05-30 17:51 UTC, hkmangla requested changes

2023-05-30 17:51 UTC, hkmangla commented on Backend/test/src/Mobility/Transporter/APICalls.hs
Instead of removing test cases, lets try reusing them for DriverOfferBPP.

2023-05-30 19:12 UTC, 0utkarsh commented
Dhall files can also be removed.

2023-06-01 07:04 UTC, pavelzarubin approved these changes

2023-06-01 07:26 UTC, 0utkarsh commented
`Backend/dev/sql-seed/static-offer-driver-app-seed.sql` needs to be deleted too. Can you run the server and check if transporter schema is being created?

2023-06-01 08:38 UTC, 0utkarsh approved these changes

2023-06-01 08:51 UTC, 0utkarsh commented
We can remove it from everywhere in Readme as well

2023-06-05 20:39 UTC, hkmangla approved these changes

2023-06-05 20:40 UTC, merged