frontend/fix/#1062: updated name from jatri sathi to yatri sathi
nammayatri/nammayatri pull request #1075
Opened 2023-06-01 13:01 UTC by MercyQueen

## Type of Change

- [x ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

2023-06-01 13:35 UTC, kavya-shree-s commented on Frontend/android-native/app/src/driver/jatriSaathiDriver/res/drawable/ic_launcher_with_name.png
@MercyQueen Can you compress the size of the image

2023-06-01 13:35 UTC, kavya-shree-s commented on Frontend/android-native/app/src/driver/jatriSaathiDriver/res/drawable/ny_ic_banner.png
@MercyQueen Reduce image size

2023-06-01 13:35 UTC, kavya-shree-s commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/MainActivity.java
> +            payload.put("clientId","jatrisaathiprovider");
@MercyQueen client ID can be fetched instead of hardcoding?

2023-06-01 13:35 UTC, kavya-shree-s commented on Frontend/android-native/app/src/user/jatriSaathi/res/drawable/ic_share_app.png
@MercyQueen  Reduce the image size

2023-07-11 06:57 UTC, Rohit4997 requested changes

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/android-native/app/src/driver/jatriSaathiDriver/res/drawable/ny_ic_aadhaar_logo.png
@MercyQueen reduce this image size
you can use this website https://www.resizepixel.com/
It will not reduce image quality

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/android-native/app/src/driver/jatriSaathiDriver/res/drawable/ny_ic_new_avatar.png
For small icons size should be less than 5kb

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/CommonJsInterface.java
> +    public void uploadTheFile(){
Please use the same function by overriding the function

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/MainActivity.java
>          if (in.juspay.mobility.BuildConfig.MERCHANT.equals("KL")) {
Can we add a case match here
Instead of if else for better readability

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/android-native/app/src/main/res/drawable/ic_auto_rickshaw.png
@MercyQueen reduce this image size
you can use this website https://www.resizepixel.com/
It will not reduce image quality

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/android-native/app/src/main/res/drawable/ic_white_taxi.png
@MercyQueen reduce this image size
you can use this website https://www.resizepixel.com/
It will not reduce image quality

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/android-native/app/src/user/jatriSaathi/res/drawable/ic_no_quotes_color.png
@MercyQueen reduce this image size
you can use this website https://www.resizepixel.com/
It will not reduce image quality

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/android-native/app/src/user/jatriSaathi/res/drawable/ny_ic_driver_near.png
Reduce this image size

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/android-native/app/src/user/jatriSaathi/res/drawable/ny_ic_driver_started.png
Reduce this image size

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +    console.log("I AM HERE to remove marker------------------");
Remove log

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/ui-customer/src/Components/DriverInfoCard/View.purs
> +  , visibility if ((Array.any (_ == state.props.currentStage) [ RideStarted, ChatWithDriver ]) || (state.props.currentStage == RideAccepted && (not state.props.isSpecialZone)))&& (not state.props.sho
It should come from config, Merchant check should not be there

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +      text =  "Okay"
Can we add translations

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +      text = "Your ride OTP expired. Please book again to get a ride"
Add Translations

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +      text = "OTP Expired"
Add Translations

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/ui-driver/src/Flow.purs
> +            "INVALID_AADHAAR" -> do
Can we move it to a different function for better readability

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/AadhaarVerificationScreen/View.purs
> +  , text $ "Enter Aadhaar OTP"
Add Translations

2023-07-11 06:57 UTC, Rohit4997 commented on Frontend/ui-driver/src/Strings/BN.js
> +  EXCEED_OTP_GENERATION_LIMIT : "ওটিপি তৈরির সর্বোচ্চ সীমা ছাড়িয়ে গেছে। কিছু সময়ের মধ্যে আবার চেষ্টা করুন.",
Add Proper indentation

2023-08-20 19:23 UTC, closed without merging