frontend/fix/#1120: added cross btn for try with tip popup
nammayatri/nammayatri pull request #1136
Opened 2023-06-06 11:32 UTC by ashkriti

## Type of Change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
The tip bottom sheet(when user tries to cancel on-going search and search again with a tip)

## Motivation and Context
https://github.com/nammayatri/nammayatri/issues/1120

## How did you test it?
Tested Manually

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

## Screenshots

<img width="415" alt="Screenshot 2023-06-14 at 2 21 09 PM" src="https://github.com/nammayatri/nammayatri/assets/61149512/7b65178d-9240-4ef5-9f76-1d3d43f1da12">

![Screenshot_2023-06-06-20-32-10-68_88a774e4ba75b7addb8b842e78164a94](https://github.com/nammayatri/nammayatri/assets/61149512/0003a869-52b2-4d8e-bdb3-bce4fa53aff2)

2023-06-08 08:04 UTC, MercyQueen reviewed
@ashkritidewan2000  can we add the images in main directory itself instead of adding it in each merchant directory separately?

2023-06-08 08:08 UTC, MercyQueen requested changes

2023-06-08 12:14 UTC, ashkriti commented on Frontend/ui-common/src/Components/PopUpModal/View.purs
> +            , imageWithFallback "ny_ic_dismiss,https://assets.juspay.in/nammayatri/images/user/ny_ic_dismiss.png"
Done

2023-06-08 12:14 UTC, ashkriti commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +          , imageVisibility = if(isLocalStageOn ST.QuoteList) then GONE else VISIBLE
Done

2023-06-08 13:02 UTC, MercyQueen reviewed
added comments

2023-06-14 09:39 UTC, witcher-shailesh approved these changes

2023-06-14 09:39 UTC, merged