Backend/fix/#960/ Update Driver's Gender
nammayatri/nammayatri pull request #1137
Opened 2023-06-06 12:13 UTC by Akash2172

Updating Driver's Gender using Profile API

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

2023-06-14 12:49 UTC, RitikaHanish approved these changes

2023-06-15 06:37 UTC, hkmangla requested changes

2023-06-15 06:37 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +               gender = fromMaybe person.gender req.gender
do it like this only `req.gender <|> person.gender`

2023-06-15 07:03 UTC, hkmangla approved these changes

2023-06-15 07:04 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +               gender = fromMaybe person.gender req.gender
Not required

2023-06-15 07:04 UTC, merged