Feature module split
nammayatri/nammayatri pull request #1176
Opened 2023-06-08 18:24 UTC by Vignesh-772

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-14 07:09 UTC, Rohit4997 submitted a review, later dismissed

2023-06-14 07:09 UTC, Rohit4997 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/YoutubeVideoView.java
> +//        if(CommonJsInterface.youtubePlayer != null) {
Remove commented code if not used

2023-06-14 07:09 UTC, Rohit4997 commented on Frontend/android-native/mobility-app/src/main/res/drawable/ic_agency_cancelled.xml
Where is this file used?

2023-06-14 07:09 UTC, Rohit4997 commented on Frontend/android-native/mobility-app/src/main/res/drawable/ic_agency_offline.xml
Where is this file used?

2023-06-14 07:09 UTC, Rohit4997 commented on Frontend/output/A/externs.cbor
Why this file is reqiured?

2023-06-14 07:09 UTC, Rohit4997 commented on Frontend/output/A/index.js
Why this file is reqiured?

2023-06-14 07:09 UTC, Rohit4997 commented on Frontend/output/cache-db.json
Why this file is reqiured?

2023-06-14 07:09 UTC, Rohit4997 commented on Frontend/packages.dhall
> +    , version = "Add-font-weight"
Why this version, Any specific reason?

2023-06-16 06:51 UTC, Vignesh-772 commented on .DS_Store
I can't see that file in local

2023-07-03 12:53 UTC, witcher-shailesh requested changes

2023-07-03 12:53 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Handler.purs
> +  _ <- pure $ spy "homrscreen" "handler"
if not required let's remove this log, also spelling is wrong

2023-07-03 12:53 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ScreenData.purs
> +    , isSearchLocation : SearchLocation
Why do we need a view in dummy data? It should be NoView only

2023-07-03 12:53 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +            -- _ <- isMockLocation push IsMockLocation
Why did we removed this check??

2023-07-03 12:53 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +            -- _ <- pure $ logEvent state.data.logField "ny_user_ride_assigned"
better remove than commenting these

2023-07-03 12:53 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Services/Backend.purs
> +  or FITNESS FOR A PARTIcuLAR PURPOSE. See the GNU Affero General Public License for more details. You should have received a copy of
Why this spelling is changes in few of the files? :joy:

2023-07-03 12:53 UTC, witcher-shailesh commented on Frontend/ui-driver/src/Screens/EnterMobileNumberScreen/Controller.purs
> +  let isValidMobileNumber = true --case (charAt 0 newVal) of
why is this removed? It's a mandatory item for getting approval on play store/ app store

2023-07-04 12:07 UTC, Vignesh-772 commented on Frontend/android-native/app/build.gradle
> +        jsUser {
It is done in separate PR

2023-07-04 12:08 UTC, Vignesh-772 commented on Frontend/android-native/mobility-app/src/main/AndroidManifest.xml
This is how the module splitting is works.

2023-07-04 12:08 UTC, Vignesh-772 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/OtpUtils.java
It is deleted moved to HyperSDK

2023-07-04 12:09 UTC, Vignesh-772 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/OverlaySheetService.java
> +    @SuppressLint("SetTextI18n")
To Remove Warnings

2023-07-04 12:10 UTC, Vignesh-772 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/OverlaySheetService.java
> +        if (sheetArrayList.size() > 0) {
It is initialised already it is not going to be null.

2023-07-04 12:19 UTC, Vignesh-772 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/RideRequestUtils.java
> +    public static int calculateExpireTimer(String expireTimeTemp, String currTimeTemp) {
No @Rohit4997 It is good to have helper functions as static.

2023-07-04 12:38 UTC, Vignesh-772 commented on Frontend/packages.dhall
> +    , version = "Add-font-weight"
yes we added new prop.

2023-07-04 14:09 UTC, MercyQueen commented on Frontend/android-native/mobility-customer/src/main/java/in/juspay/mobility/customer/MobilityCustomerBridge.java
> +        Location location = new Location("final point");
@soumyajit2304 can you please reply here.

2023-07-04 14:13 UTC, soumyajit2304 commented on Frontend/android-native/mobility-customer/src/main/java/in/juspay/mobility/customer/MobilityCustomerBridge.java
> +        Location location = new Location("final point");
`new Location` takes a key as paramater.   
Which also denotes the name of that point.

2023-07-04 14:15 UTC, Vignesh-772 commented on Frontend/ui-common/src/Engineering/Helpers/Commons.purs
> +flowRunnerWithState :: forall a st. st -> (Flow st a) -> Aff (Either Error a)
Previous it is needed now the normal flow runner itself will take state so not required

2023-07-30 14:38 UTC, witcher-shailesh approved these changes

2023-07-30 14:39 UTC, merged