frontend/fix/#1184: added the required firebase events
nammayatri/nammayatri pull request #1186
Opened 2023-06-09 12:27 UTC by ashkriti

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
'Set location on map' clicks- to count the number of times users are trying to set/change location(in various places- pickup location, drop location, favourite location) on the map directly.
'Our Live Stats' clicks- to check the impact of removing 'Our Live Stats' CTA during the ride in customer app

## Motivation and Context
https://github.com/nammayatri/nammayatri/issues/1184

## How did you test it?
Tested Manually

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-09 17:19 UTC, kavya-shree-s commented
@ashkriti `Set location on map - favourite location `  firebase event is not added in this PR , Please check

2023-06-09 17:20 UTC, kavya-shree-s requested changes
@ashkriti Set location on map - favourite location  firebase event is not added in this PR , Please check

2023-06-09 19:30 UTC, kavya-shree-s approved these changes

2023-06-13 10:10 UTC, witcher-shailesh approved these changes

2023-06-13 10:10 UTC, merged