backend/feat : Added aadhaar verification for wb
nammayatri/nammayatri pull request #1195
Opened 2023-06-11 09:30 UTC by AshishSaini25

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Added aadhaar verification for wb

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-12 06:25 UTC, RitikaHanish commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/UI/DriverOnboarding.hs
> +             :> ReqBody '[JSON] AV.VerifyOtpReq
@AshishSaini25 Can you rename it to verifyAdhaarOTPReq?

2023-06-12 06:30 UTC, RitikaHanish commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/UI/DriverOnboarding.hs
> +verifyAadhaarOtp (personId, merchantId) = withFlowHandlerAPI . AV.verifyAadhaarOtp False Nothing (personId, merchantId)
Why are you passing merchant and merchantId both ?
And always you are hardcoding merchant to Nothing.

2023-06-12 06:31 UTC, RitikaHanish commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/DriverOnboarding/AadhaarVerification.hs
> +  Esq.runTransaction $ Query.create aadhaarOtpEntity
Put runNoTransaction.

2023-06-12 06:36 UTC, RitikaHanish requested changes

2023-06-12 06:36 UTC, RitikaHanish commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/DriverOnboarding/AadhaarVerification.hs
> +      Esq.runTransaction $ VQuery.create aadhaarVerifyEntity
Same as above

2023-06-12 06:36 UTC, RitikaHanish commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Types/DriverOnboarding/AadhaarOtpReq.hs
Why are you making 3 different  domain types files ?

2023-06-16 12:36 UTC, hkmangla requested changes

2023-06-16 12:36 UTC, hkmangla commented on Backend/app/dashboard/CommonAPIs/src/Dashboard/ProviderPlatform/Driver/Registration.hs
> +    consent :: Text
Here, make it enum. shared-kernel side we can change later.

2023-06-16 12:36 UTC, hkmangla commented on Backend/app/dashboard/CommonAPIs/src/Dashboard/ProviderPlatform/Driver/Registration.hs
> +  { statusCode :: Text,
`statusCode` and `requestId` is not required.

2023-06-16 12:36 UTC, hkmangla commented on Backend/app/dashboard/CommonAPIs/src/Dashboard/ProviderPlatform/Driver/Registration.hs
> +    consent :: Text
And use all this type from main only. No need to create again here.

2023-06-16 12:36 UTC, hkmangla commented on Backend/app/dashboard/CommonAPIs/src/Dashboard/ProviderPlatform/Driver/Registration.hs
> +  { statusCode :: Text,
Same for this.

2023-06-16 12:36 UTC, hkmangla commented on Backend/app/dashboard/CommonAPIs/src/Dashboard/ProviderPlatform/Driver/Registration.hs
> +    includeXml :: Bool,
`includeXml` not required.

2023-06-16 12:36 UTC, hkmangla commented on Backend/app/dashboard/provider-dashboard/src/API/ProviderPlatform/DynamicOfferDriver/Driver/Registration.hs
> +    transaction <- buildTransaction Common.GenerateAadhaarOtpEndpoint apiTokenInfo driverId (Just req)
I think this request will contain Aadhaar number, no need to save req. Pass Nothing instead of `Just req`

2023-06-16 12:36 UTC, hkmangla commented on Backend/app/dashboard/provider-dashboard/src/API/ProviderPlatform/DynamicOfferDriver/Driver/Registration.hs
> +    transaction <- buildTransaction Common.VerifyAadhaarOtpEndpoint apiTokenInfo driverId (Just req)
Saving req is not required here too.

2023-06-16 12:36 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Dashboard/Driver/Registration.hs
> +    Common.GenerateAadhaarOtpRes
This is not needed once you will remove types from Dashboard.

2023-06-16 12:36 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Dashboard/Driver/Registration.hs
> +    Common.VerifyAadhaarOtpRes
same here.

2023-06-16 12:36 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/DriverOnboarding/AadhaarVerification.hs
> +  let key = makeTransactionNumberKey personId
Move all expiry related stuff to a separate function

2023-06-16 12:36 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/DriverOnboarding/AadhaarVerification.hs
> +      let temp =
temp is not a good variable name.

2023-06-16 12:36 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/DriverOnboarding/AadhaarVerification.hs
> +      if res.code == pack "1002"
Not the good way to handle it. But we can iterate it again.

2023-06-19 10:53 UTC, piyushKumar-1 approved these changes

2023-06-19 10:55 UTC, merged