backend/fix: #1123 Added new  parameter, Bonus to driver/profile/stat…
nammayatri/nammayatri pull request #1207
Opened 2023-06-12 14:57 UTC by ratnadeep-99

…s API.

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-12 16:11 UTC, hkmangla requested changes

2023-06-12 16:11 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +           in Money $ L.sum driverSelFares' + L.sum customerExtFees' + length driverSelFares' * 10
sum fareParameters.fareParametersDetails.deadKmFare 
not the length

2023-06-12 16:11 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +import qualified GHC.List as L
GHCL

2023-06-12 16:11 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +            Just id -> QFP.findById id
runInReplica $  QFP.findById id

2023-06-12 16:11 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +  (EsqDBReplicaFlow m r, EncFlow m r, HasField "esqDBEnv" r EsqDBEnv) =>
remove ` HasField "esqDBEnv" r EsqDBEnv)`

2023-06-12 16:11 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +  ( EsqDBEnv,
not needed

2023-06-12 16:11 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +            Just id -> QFP.findById id
`fareParameters' <- mapM (maybe (pure Nothing) QFP.findById . (.fareParametersId)) rides`

2023-06-16 08:57 UTC, piyushKumar-1 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +  fareParameters <- catMaybes <$> mapM (runInReplica . QFP.findById) fareParamId
hey, this can be a in query ?

2023-06-19 12:34 UTC, srid commented on Backend/.envrc
`.envrc` is gitignored.

2023-06-19 13:47 UTC, closed without merging