backend/enhancement: Special Location Tag Modified to Show Both Picku…
nammayatri/nammayatri pull request #1259
Opened 2023-06-15 09:14 UTC by khuzema786

…p and Drop Special Location Category

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-15 14:23 UTC, RitikaHanish approved these changes

2023-06-16 07:01 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/FareProduct.hs
> +    mkSpecialLocationTag pickupSpecialLocationCategory dropSpecialLocationCategory priority = pickupSpecialLocationCategory <> "_" <> dropSpecialLocationCategory <> "_" <> "Priority" <> priority
there should be `-` b/w `"Priority"` and `priority`, right?

2023-06-16 07:02 UTC, hkmangla requested changes

2023-06-16 07:59 UTC, hkmangla approved these changes

2023-06-16 07:59 UTC, merged