backend/fix/#1165-added no of deviation in ride table
nammayatri/nammayatri pull request #1334
Opened 2023-06-21 12:35 UTC by soumyajit2304

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Added a new column named `numberOfDeviation` in the ride table

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-22 09:49 UTC, umangj-28 approved these changes

2023-07-06 06:51 UTC, hkmangla requested changes

2023-07-06 06:51 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Beckn/Search.hs
> +searchRequestKey mId = "Driver:Search:Request:" <> mId
Why this key is defined at two places? It should be at one place only.

2023-07-06 06:51 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Beckn/Search.hs
> +          Redis.hSetExp (searchRequestKey $ getId merchantId) (getId searchReq.id) routeInfo 84000
set expiry time for 1 hour, not 24 hours.

2023-07-06 07:39 UTC, hkmangla approved these changes

2023-07-06 09:32 UTC, merged