Frontend/fix: #1132 adding otp attempts count - WIP
nammayatri/nammayatri pull request #1362
Opened 2023-06-22 12:18 UTC by AmritpalSingh6749

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
added login attempt count

2023-07-06 09:57 UTC, Rohit4997 commented
Have you tested in Android as well?

2023-07-06 20:28 UTC, kavya-shree-s commented
@AmritpalSingh6749 Can you link the issue ?

2023-07-06 20:33 UTC, kavya-shree-s requested changes
@AmritpalSingh6749 Please elaborate task description , Why it is handled completely in frontend ?

2023-07-07 06:37 UTC, AmritpalSingh6749 commented
> Have you tested in Android as well?

Yes

2023-07-07 06:43 UTC, AmritpalSingh6749 commented
> @AmritpalSingh6749 Can you link proper issue ?
> 
> Issue number you have used in commit message is relevant #1132
> 
> Yes, this task is under issue number #1132 only

2023-07-07 07:02 UTC, SrinivasNaikB commented
https://github.com/nammayatri/nammayatri/pull/1362#pullrequestreview-1517267395
Sure, Can we discuss this offline?

2023-07-21 13:53 UTC, ashishsingh101 requested changes

2023-07-21 13:53 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Helpers/Utils.js
> +
@AmritpalSingh6749 since decode payload, code and message act as same can you make it configurable by passing string you want to access value of ?

2023-07-21 13:53 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Helpers/Utils.js
> +
make common function and use same everywhere

2023-07-21 13:53 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Flow.purs
> +                    attemptsLeft = decodeErrorPayload errResp.errorMessage
define this variable inside respective condition

2023-07-24 19:35 UTC, ashishsingh101 approved these changes

2023-07-27 07:33 UTC, kavya-shree-s approved these changes

2023-07-27 11:01 UTC, merged