backend/feature/: #994/created metaData api for BPP
nammayatri/nammayatri pull request #1380
Opened 2023-06-23 15:03 UTC by saurav2401

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

created metaData api to store device details of driver

### Additional Changes

- [x] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [x] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-06-26 06:13 UTC, pavelzarubin approved these changes

2023-07-04 11:55 UTC, hkmangla requested changes

2023-07-04 11:55 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/UI/Driver.hs
> +             :<|> "updateMetaData"
rename it to `metadata`.

2023-07-06 10:45 UTC, hkmangla approved these changes

2023-07-06 10:46 UTC, merged