frontend/fix: #1406 added pincode in overlay sheet
nammayatri/nammayatri pull request #1408
Opened 2023-06-27 06:57 UTC by aryanguptaSG

## Type of Change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Add PinCode of pickup and drop locations in overlay sheet in driver app .
figma :- [link](https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=62317%3A17717&t=5tX4hcKpIk5HTjGF-1)

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-07-03 06:04 UTC, kavya-shree-s commented
@aryanguptaSG Can you attach screenshot/screenrecording

2023-07-03 07:12 UTC, Rohit4997 commented
> @aryanguptaSG Can you attach screenshot/screenrecording

Also record specialZone View as well in this case

2023-07-05 06:19 UTC, Rohit4997 requested changes

2023-07-05 06:19 UTC, Rohit4997 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java
> +                    sheetData.putString("sourcePinCode", addressPickUp.getString("areaCode"));
If `addressPickUp` is not having any areaCode, Handle that case as well

2023-07-05 06:19 UTC, Rohit4997 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/OverlaySheetService.java
> +                holder.sourceAddress.setMaxLines(2);
`holder.sourcePinCode.setVisibility(View.GONE);`
Can you add this line in else case

2023-07-05 06:19 UTC, Rohit4997 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/OverlaySheetService.java
> +                holder.destinationAddress.setMaxLines(2);
`holder.destinationPinCode.setVisibility(View.GONE);`
Add this line in else case

2023-07-05 06:19 UTC, Rohit4997 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/RideRequestActivity.java
> +                        rideRequestBundle.getString("specialLocationTag"),
Add the pincode visibility conditions in this Activity's `onBindViewHolder` as well

2023-07-11 13:19 UTC, aryan-13 approved these changes

2023-07-12 07:10 UTC, Rohit4997 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/RideRequestActivity.java
> +                        rideRequestBundle.getString("specialLocationTag"),
Please add the pincode in this Activity as well

2023-07-12 07:51 UTC, witcher-shailesh approved these changes

2023-07-12 08:02 UTC, kavya-shree-s approved these changes

2023-07-12 08:06 UTC, Rohit4997 approved these changes

2023-07-13 07:33 UTC, merged