frontend/fix: #1043 added info when driver location is not available …
nammayatri/nammayatri pull request #1467
Opened 2023-07-03 09:41 UTC by aryanguptaSG

…in customer app

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
As a rider, I want the accurate location of the driver before pickup so that I am sure that the driver is moving towards my location . if driver is not connected to the internet we are showing a notification to customer app that driver is not connected to internet .
 
figma :- [link](https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=58072%3A11094&t=OWYlVsorPJrLuOkL-1)
output android :- [link](https://drive.google.com/file/d/1G2HsA_rI0CijWHaVjORTcJiBLHAaaAy1/view?usp=sharing)

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-07-12 08:36 UTC, Vignesh-772 requested changes

2023-07-12 08:36 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +              _ <- liftFlow $ showInAppNotification (getString INTERNET_ISSUE_AT_DRIVERS_END) (getString YOU_MAY_CONTACT_DRIVER_TO_TRACK_YOUR_RIDE) "" "" "" "" "" "driver_location_error" 5000 "true"
@aryanguptaSG If it is a boolean then send boolean no need of string.

2023-07-12 08:36 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +              _ <- liftFlow $ showInAppNotification (getString INTERNET_ISSUE_AT_DRIVERS_END) (getString YOU_MAY_CONTACT_DRIVER_TO_TRACK_YOUR_RIDE) "" "" "" "" "" "driver_location_error" 5000 "true"
Do the changes accordingly

2023-07-12 13:06 UTC, shanm-16 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/InAppNotification.java
> +            if(showLoaderImage.equals("true")){
is this formatting correct?

2023-07-12 13:08 UTC, shanm-16 commented on Frontend/ui-customer/src/Services/API.purs
> +newtype GetDriverLocationResp = GetDriverLocationResp Location
there is space between 2 newtypes

2023-07-18 07:39 UTC, aryanguptaSG commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/InAppNotification.java
> +            if(showLoaderImage.equals("true")){
yes .

2023-10-23 10:12 UTC, witcher-shailesh commented
Not required as of now

2023-10-23 10:12 UTC, closed without merging