frontend/fix/IOS-Fix-From-Sheet
nammayatri/nammayatri pull request #1469
Opened 2023-07-03 10:21 UTC by Akash2172

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Bugs Fixed:
1. Emergency Contacts text were going outside screen
2. Favourite Icon was not visible
3. BackSpacing Issue Due to '.' added by pressing space in IOS
4. SetLocation Space was more (Which is required due to home button match) (NEED TO TEST PHYSICAL DEVICE)

2023-07-04 11:20 UTC, MercyQueen requested changes

2023-07-04 11:20 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/CustomerUtils/EmergencyContactsScreen/View.purs
> +        , width if os == "IOS" then V ((screenWidth unit) - 20) else (WRAP_CONTENT)
@Akash2172 can you please remove unwanted brackets

2023-07-04 11:20 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/CustomerUtils/EmergencyContactsScreen/View.purs
> +        , width if os == "IOS" then V ((screenWidth unit) - 20) else (WRAP_CONTENT)
@Akash2172 here also

2023-07-05 11:59 UTC, witcher-shailesh approved these changes

2023-07-06 09:56 UTC, MercyQueen approved these changes

2023-07-06 15:27 UTC, merged