[WIP]: frontend/fix/ Customer feedback pills
nammayatri/nammayatri pull request #1583
Opened 2023-07-11 14:45 UTC by aryan-13

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-07-25 08:32 UTC, witcher-shailesh requested changes

2023-07-26 16:11 UTC, ashishsingh101 requested changes

2023-07-27 10:21 UTC, MercyQueen requested changes

2023-07-27 10:21 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +  _ <- pure $ spy "feedback lsit "  filterFeedbackList
@aryan-13 can you please remove spy statements.

2023-07-27 10:21 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +  continue state { data { rideRatingState { rating = index , feedbackList = if index == state.data.rideRatingState.rating then state.data.rideRatingState.feedbackList else []}, ratingViewState { sele
@aryan-13 temp is defined already. Can we consume this variable.

2023-07-27 10:21 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +      filterFeedbackList = filter (\fa -> length fa.answer > 0) newFeedbackList
@aryan-13 please rename fa to something more meaningful.

2023-07-28 07:16 UTC, ashishsingh101 approved these changes

2023-07-28 08:02 UTC, kavya-shree-s commented
@aryan-13 Is this tested in all the other language and other screen size device ?

2023-07-28 11:22 UTC, Rohit4997 approved these changes

2023-07-28 14:43 UTC, merged