frontend/fix: #1584 Message Overlay Bug Fixes
nammayatri/nammayatri pull request #1587
Opened 2023-07-11 16:41 UTC by PraveenGongada

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Fixed Chat Message overlay issues

Closes #1584

2023-07-12 13:01 UTC, Vignesh-772 requested changes

2023-07-12 15:54 UTC, PraveenGongada commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/MessageOverlay.java
> +                typeface = ResourcesCompat.getFont(context, R.font.notosanskannada_semibold);
Done

2023-07-12 15:54 UTC, PraveenGongada commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/MainActivity.java
> +    public void scrollToBottom () {
Done

2023-07-13 06:56 UTC, aryan-13 approved these changes

2023-07-13 07:11 UTC, Vignesh-772 approved these changes

2023-07-13 07:33 UTC, merged