frontend/feat/#1650/CapturingInstallationSourceOfCustomer
nammayatri/nammayatri pull request #1651
Opened 2023-07-13 14:15 UTC by Akash2172

## Type of Change
Capture the Source of user's redirection to google play for app download

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Integrated Play Install Referrer Library and appInstall/create API

2023-07-25 08:44 UTC, witcher-shailesh requested changes

2023-07-25 08:44 UTC, witcher-shailesh commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/MainActivity.java
> +                            System.out.println("INSIDE REFERRER RESPONSE SUCCESS ");
Remove logs and add proper comment if you want to keep commented code, otherwise remove the commented code

2023-07-25 08:44 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Flow.purs
> +  let versionName = getValueToLocalStore VERSION_NAME
VersionName BundleVersion can be passed from baseAppFlow, instead of fetching it again from the storage. Then no need to pass a dummy string as well

2023-07-25 08:44 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Services/API.purs
> +instance showAppInstallsReq :: Show AppInstallsReq where show = genericShow
Do we need show instance? if not can you remove

2023-08-09 07:17 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Flow.purs
> +  pure unit
After makeAppInstallsCall function is called, where is the flow pointing to? if it's not a separate flow then add this function within the function where it's called under `where` block

2023-08-09 07:17 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Flow.purs
> +import Services.Backend as Remote
This is redundant, one of the cause for increasing warning

2023-09-20 17:37 UTC, Vignesh-772 commented
need to refactor will reopen do once it is required

2023-09-20 17:37 UTC, closed without merging