driver-wait-timer
nammayatri/nammayatri pull request #1714
Opened 2023-07-16 23:15 UTC by mohdshoaib18169

## Type of Change

- [ ] Bugfix
- [ x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
 Adding Wait Timer For Driver

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-07-18 10:27 UTC, kavya-shree-s requested changes

2023-07-25 10:27 UTC, aryan-13 requested changes

2023-07-25 10:27 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +          if ((getValueToLocalStore IS_WAIT_TIMER_STOP) == "Triggered") && initialState.props.timerRefresh  then do
Can we `TRIGGERED` ,  `PostTriggered` and `Stop` as ENUM

2023-07-25 10:27 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/HomeScreen/ComponentConfig.purs
> +      padding = Padding 0 16 0 20
Use `PaddingVertical` here

2023-07-25 10:27 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/HomeScreen/ComponentConfig.purs
> +      padding = Padding 16 0 0 0
Use `PaddingLeft` here

2023-07-25 10:27 UTC, aryan-13 commented on Frontend/ui-driver/src/Helpers/Utils.js
> +          console.log("hello1");
Remove this log

2023-07-25 12:32 UTC, aryan-13 approved these changes

2023-07-25 12:53 UTC, Rohit4997 requested changes

2023-07-26 08:19 UTC, Rohit4997 commented on Frontend/android-native/app/src/driver/jatriSaathiDriver/res/drawable/ny_ic_waiting_auto.png
Reduce size

2023-07-26 08:29 UTC, mohdshoaib18169 commented on Frontend/android-native/app/src/driver/jatriSaathiDriver/res/drawable/ny_ic_waiting_auto.png
reduced

2023-07-26 08:34 UTC, Rohit4997 approved these changes

2023-07-26 09:19 UTC, merged