backend/refactor: #147 Moved endride config to db
nammayatri/nammayatri pull request #172
Opened 2023-03-15 16:01 UTC by Dwibedi-10

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description
removed EndRideconfig from Dhall and fetching data from DB wherever required.

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [x] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-03-15 17:09 UTC, roman-bodavskiy commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Ride/EndRide.hs
> +  thresholdConfig <- findConfig >>= fromMaybeM (InternalError "not found")
Could you add more specific error message?

2023-03-15 17:12 UTC, roman-bodavskiy commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Tabular/TransporterConfig.hs
> +      pickupLocThreshold Meters
you didn't add migration for these changes

2023-03-15 17:14 UTC, hkmangla requested changes

2023-03-15 17:14 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Tabular/TransporterConfig.hs
>        rideTravelledDistThresholdWhenPickupOrDestIsDiff Meters Maybe
remove `rideTravelledDistThresholdWhenPickupOrDestIsDiff` and  `rideTravelledDistThresholdWhenPickupAndDestIsSame` if not used.

2023-03-15 17:14 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Ride/EndRide.hs
> +  thresholdConfig <- findConfig >>= fromMaybeM (InternalError "not found")
User proper error code that TransportConfigNotFound

2023-03-15 17:14 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Ride/EndRide.hs
> +  thresholdConfig <- findConfig >>= fromMaybeM (InternalError "not found")
proper error code

2023-03-16 19:49 UTC, hkmangla requested changes

2023-03-16 19:49 UTC, hkmangla commented on Backend/dev/migrations/dynamic-offer-driver-app/0121-updated-transporter-config-table.sql
> +UPDATE atlas_driver_offer_bpp.transporter_config SET ride_time_estimated_threshold = 700;
Add not null constraints as these values can't be maybe. Add not null on `waitingTimeEstimatedThreshold` too as you have removed maybe from it.

2023-03-18 05:33 UTC, hkmangla approved these changes

2023-03-18 05:33 UTC, merged