Backend/bug fix/#1530/money to high prec money changes
nammayatri/nammayatri pull request #1751
Opened 2023-07-18 09:44 UTC by DwivediAman-exe

## Type of Change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-07-19 07:52 UTC, 0utkarsh requested changes

2023-07-19 07:52 UTC, 0utkarsh commented on Backend/app/mocks/public-transport-provider-platform/src/MockData/OnSearch.hs
> +  let price = Price "INR" $ amount
Can you resolve these comments?

2023-07-19 07:52 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/DriverFeeUpdates/DriverFee.hs
> +            paymentMessage = "Sorry, you are blocked from taking rides as payment of " <> show pendingAmount <> " is pending for " <> show driverFee.numRides <> " ride(s) with a deadline of " <> show
These are removed, can you rebase?

2023-07-19 07:52 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Payment.hs
> +            amount = pendingAmount,
I don't think this should be changed

2023-07-20 04:39 UTC, DwivediAman-exe commented on Backend/app/mocks/public-transport-provider-platform/src/MockData/OnSearch.hs
> +  let price = Price "INR" $ amount
Done

2023-07-20 04:39 UTC, DwivediAman-exe commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/DriverFeeUpdates/DriverFee.hs
> +            paymentMessage = "Sorry, you are blocked from taking rides as payment of " <> show pendingAmount <> " is pending for " <> show driverFee.numRides <> " ride(s) with a deadline of " <> show
Done

2023-07-20 04:40 UTC, DwivediAman-exe commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Payment.hs
> +            amount = pendingAmount,
Removed

2024-06-10 20:02 UTC, closed without merging