frontend/feat/#1401/added delay to callback recieved
nammayatri/nammayatri pull request #1785
Opened 2023-07-20 08:31 UTC by Akash2172

## Type of Change
Added Delay to the callback received when user locates on map.
Current delay time 300ms
When new request is received before the callback is executed the order callback is overwritten.

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

2023-07-20 08:59 UTC, ashishsingh101 requested changes

2023-07-20 08:59 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Helpers/Utils.js
> +            timerIdDebounce = "MAKEAPICALL";
why you need this ?

2023-07-20 10:13 UTC, ashishsingh101 approved these changes

2023-07-25 08:35 UTC, witcher-shailesh approved these changes

2023-07-25 08:35 UTC, merged