frontend/fix #1786 latency pop and remove notification solved
nammayatri/nammayatri pull request #1787
Opened 2023-07-20 09:31 UTC by KiranBKL

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-07-21 09:50 UTC, ashishsingh101 requested changes

2023-07-21 09:50 UTC, ashishsingh101 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java
> +    public static ArrayList<String> removeList = new ArrayList<>();
can we not rely on static variable for this if values are getting restored after killing and opening the app

2023-07-21 09:50 UTC, ashishsingh101 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java
> +                    }
remove this

2023-07-21 09:50 UTC, ashishsingh101 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java
> +                System.out.println("cleared fare "+context.getString((R.string.CLEARED_FARE)));
remove logs

2023-07-21 09:50 UTC, ashishsingh101 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java
> +                            },0000);
not required

2023-07-25 12:57 UTC, ashishsingh101 requested changes

2023-07-25 12:57 UTC, ashishsingh101 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java
> +            //}
remove commented codes

2023-07-25 12:57 UTC, ashishsingh101 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/RideRequestUtils.java
> +        String[] arrOfA = expireTimeTemp.split("T");//2023-07-20T022:45:16.168244Z
remove commented codes

2023-07-25 12:57 UTC, ashishsingh101 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java
> +            //}
other places as well

2023-07-25 12:57 UTC, KiranBKL commented
I have solved using shared pref, could you have look that once in latest commit

2023-07-25 12:58 UTC, ashishsingh101 requested changes

2023-07-25 12:58 UTC, ashishsingh101 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java
> +    public static Map<String,String> removeList = new HashMap<>();
remove this if not required

2023-07-25 13:07 UTC, ashishsingh101 requested changes

2023-07-25 13:07 UTC, ashishsingh101 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java
> +            SharedPreferences sharedRemovePref = context.getSharedPreferences(
@KiranBKL you can use static also since its independent of activity, you can revert your changes and squash

2023-07-26 08:04 UTC, ashishsingh101 requested changes

2023-07-26 08:04 UTC, ashishsingh101 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/RideRequestUtils.java
> +        String[] arrOfB = currTimeTemp.split("T");
use proper variable name

2023-07-26 08:04 UTC, ashishsingh101 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/RideRequestUtils.java
> +        String[] arrOfB = currTimeTemp.split("T");
instead of seperating with `T` can't we fetch time directly ?

2023-07-26 10:55 UTC, Vignesh-772 approved these changes

2023-07-26 11:29 UTC, ashishsingh101 approved these changes

2023-07-26 11:59 UTC, merged