frontend/fix: #1792 driver_crashlytics_fixes
nammayatri/nammayatri pull request #1793
Opened 2023-07-20 14:23 UTC by PraveenGongada

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Fixed some crashlytics crashes for driver app

Closes #1792

2023-07-24 06:08 UTC, Rohit4997 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/CommonJsInterface.java
> +            View view = activity.findViewById(Integer.parseInt(pureScriptId));
As this view we are not using These two lines can we replaced with the following
`if ((activity.findViewById(Integer.parseInt(pureScriptId)) == null) return;`

2023-07-24 06:08 UTC, Rohit4997 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/CommonJsInterface.java
> +            View view = activity.findViewById(Integer.parseInt(pureScriptId));
As this view we are not using These two lines can we replaced with the following
`if ((activity.findViewById(Integer.parseInt(pureScriptId)) == null) return;`

2023-07-24 06:12 UTC, Rohit4997 requested changes

2023-07-24 06:12 UTC, Rohit4997 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/MainActivity.java
>                      Log.e(TAG, "Error in In App Notification Handler " + e);
Can you log firebase event for the crash

2023-07-24 06:12 UTC, Rohit4997 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/InAppNotification.java
> +                        Log.e(LOG_TAG, "Error in onClick " + e);
Can you log firebase event for the crash

2023-07-24 06:12 UTC, Rohit4997 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/LocationUpdateService.java
> +            Log.e(LOG_TAG, "Error in cancelTimer " + e);
Add a firebase log event with tag `EXCEPTION`

2023-07-25 11:48 UTC, Vignesh-772 requested changes
Add firebase logs for all the catch block

2023-07-25 12:13 UTC, Vignesh-772 approved these changes

2023-07-25 12:17 UTC, Rohit4997 approved these changes

2023-07-25 12:44 UTC, merged