backend/refactor: #BKN-2938 issue-report
nammayatri/nammayatri pull request #180
Opened 2023-03-16 14:30 UTC by khuzema786

## Type of Change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
- Seperation issue report list & issue report info API
- Updated DB Schema
- Refactoring
- Added validations

### Additional Changes

- [x] This PR modifies the database schema (database migration added)
- [x] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-03-20 16:02 UTC, hkmangla requested changes

2023-03-20 16:02 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Dashboard/Issue.hs
> +    Just justUserId -> do
userId <- justUserId & fromMaybe (InternalError "userId is not attatched to the request by dashboard.")

2023-03-21 12:21 UTC, hkmangla submitted a review, later dismissed

2023-03-21 12:21 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Dashboard/Message.hs
> +  transporterConfig <- CQTC.findByMerchantId merchant.id >>= fromMaybeM (MerchantServiceUsageConfigNotFound merchant.id.getId)
add proper error type.

2023-03-21 12:21 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Issue.hs
> +  transporterConfig <- CQTC.findByMerchantId person.merchantId >>= fromMaybeM (MerchantServiceUsageConfigNotFound person.merchantId.getId)
proper error type.

2023-03-21 12:21 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Environment.hs
> +data MediaFileConfig = MediaFileConfig
remove this.

2023-03-22 09:51 UTC, roman-bodavskiy commented on Backend/app/dashboard/CommonAPIs/src/Dashboard/Common/Issue.hs
> +  | IssueInfoEndpoint
this datatype used for storing transaction in DB and not required for GET APIs. So it should be:

```
data IssueEndpoint
  = IssueUpdateEndpoint
  | IssueAddCommentEndpoint
```

2023-03-22 10:03 UTC, roman-bodavskiy commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Issue.hs
> +          }
This code is duplicated. All fields, except of `option` are the same

2023-03-22 10:07 UTC, roman-bodavskiy commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Tools/Error.hs
> +  toHttpCode (IssueReportNotFound _) = E400
this should be E500

2023-03-22 10:25 UTC, roman-bodavskiy commented on Backend/dev/migrations/dynamic-offer-driver-app/0128-change-issue-table-properties.sql
> +ALTER TABLE atlas_driver_offer_bpp.comment ADD COLUMN author_id character varying(255) NOT NULL;
`character(36)` here and in other references

2023-03-28 04:39 UTC, roman-bodavskiy commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Issue.hs
> +          }
I meant, you can avoid duplication like this:

```
  mbIssueOption <- (join <$>) $ forM issueReport.optionId $ \justIssueOption -> do
    CQIO.findByIdAndLanguage justIssueOption language
  pure $
    Common.IssueInfoRes
      { issueReportId = cast issueReport.id,
        category = fromMaybe issueCategory.category $ (.translation) <$> issueCategoryTranslation,
        option = mkIssueOption <$> mbIssueOption,
        assignee = issueReport.assignee,
        description = issueReport.description,
        status = toCommonIssueStatus issueReport.status,
        mediaFiles = mkMediaFiles mediaFiles,
        createdAt = issueReport.createdAt
      }
```

2023-03-29 12:26 UTC, piyushKumar-1 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Issue.hs
> +    fromMaybe ENGLISH $
return $ fromMaybe ENGLISH ((. language) =<< driverDetail)

2023-03-29 12:26 UTC, piyushKumar-1 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Issue.hs
> +      foldr'
can we move this function to the common lib.

2023-03-30 08:50 UTC, piyushKumar-1 approved these changes

2023-03-30 08:50 UTC, merged