Frontend/feat/multiple rc
nammayatri/nammayatri pull request #1848
Opened 2023-07-24 13:12 UTC by SanskarGubreley

## Type of Change

- [ ] Bugfix
- [ x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-07-25 09:19 UTC, aryan-13 commented
Please attach Figma and output links

2023-07-26 19:33 UTC, aryan-13 submitted a review, later dismissed

2023-07-26 19:33 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/DriverProfileScreen/Controller.purs
> +        pure $ toast $ "Single RC cannot be deleted"
Add Translations here

2023-07-26 19:33 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/DriverProfileScreen/Controller.purs
> +  else if rcType == ACTIVATING_RC then continue state{props{activateOrDeactivateRcView = true}}
This can be refactored as these many if-else conditions are not required here.

2023-07-26 19:33 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/Types.purs
> +  openRcArray :: Array Int
Rename this variable to something more intuitive

2023-07-26 19:33 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/Types.purs
> +    { rcStatus     :: Boolean
Please fix the formatting here

2023-07-26 19:33 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/DriverProfileScreen/Controller.purs
> +      val = rctransformedData
Remove this `val` if not required

2023-07-26 19:33 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/DriverProfileScreen/Controller.purs
> +      let activeRcVal = val
This variable is also not required

2023-07-26 19:33 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/DriverProfileScreen/Controller.purs
> +        then continue state {data{rcsData = val, rcsExceptFirst = drop 1 val, renderingRc = fromMaybe ({ rcStatus : false, rcDetails : {certificateNumber : "", vehicleColor : "", vehicleModel : ""}})
This `{ rcStatus : false, rcDetails : {certificateNumber : "", vehicleColor : "", vehicleModel : ""}}` can be defined as a dummy value

2023-07-26 19:33 UTC, aryan-13 commented on Frontend/ui-driver/src/Flow.purs
> +      pure $ toast $ "RC-"<>state.data.rcNumber<>" Removed"
Add Translations here

2023-07-26 19:33 UTC, aryan-13 commented on Frontend/ui-driver/src/Services/Backend.purs
> +deleteRc payload = do
Remove, if this is not being used

2023-07-26 19:33 UTC, aryan-13 commented on Frontend/ui-driver/src/Services/Backend.purs
> +makeRcActiveOrInactiveBT payload = do
`makeRcActiveOrInactiveBT` if not used then remove

2023-07-26 19:33 UTC, aryan-13 commented on Frontend/ui-driver/src/Services/API.purs
> +
Add a  `----` separator here

2023-07-26 19:33 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/DriverProfileScreen/Controller.purs
> +import Debug
Remove unnecessary imports

2023-07-26 19:33 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/Types.purs
> +  rcsData :: Array RcData,
`rcsData` Please rename this variable name to `rcDataArray`

2023-07-26 19:33 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/Types.purs
> +  renderingRc :: RcData,
`rcsExceptFirst` and `renderingRc` can also be renamed to something more understandable

2023-07-26 21:02 UTC, MercyQueen submitted a review, later dismissed

2023-07-26 21:02 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/DriverProfileScreen/View.purs
> +  [ { key : "Type" , value :Just  "Auto Rickshaw" , action : NoAction , isEditable : false }
@SanskarGubreley please add translations for this

2023-07-26 21:02 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/DriverProfileScreen/View.purs
> +getRcDetails config = do
@SanskarGubreley give type signature here also.

2023-07-26 21:02 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/DriverProfileScreen/View.purs
> +              , padding $ Padding 8 0 8 0
@SanskarGubreley use PaddingHorizontal here

2023-07-27 07:05 UTC, SanskarGubreley commented on Frontend/ui-common/src/Animation/Animation.purs
> +-- scaleAnim :: AnimConfig -> PrestoAnim.Animation
This is not my change, this commented code is not reflecting in my local code.

2023-07-27 07:52 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/DriverProfileScreen/ComponentConfig.purs
> +deleteRcPopUpCongif state =
check spelling here `deleteRcPopUpCongif`

2023-07-27 09:14 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/DriverProfileScreen/Controller.purs
> +        trackAppActionClick appId (getScreen VEHICLE_DETAILS_SCREEN) "popup_modal_logout" "logout"
Update the logs here . This should be `ActivateOrDeactivateRcPopUpModal`

2023-07-27 13:04 UTC, PraveenGongada requested changes

2023-07-27 13:04 UTC, PraveenGongada commented on Frontend/ui-driver/src/Screens/DriverProfileScreen/ComponentConfig.purs
> +        { primaryText { text = if state.data.rcState then (getString DEACTIVATE_RC) else (getString ACTIVATE_RC)}
Can we change the name of rcState to isActiveRC, since rcState as boolean can't tell the state

2023-07-29 17:29 UTC, PraveenGongada approved these changes

2023-07-29 20:22 UTC, merged