backend/fix: missing migrations directory when running tests.
nammayatri/nammayatri pull request #198
Opened 2023-03-18 09:34 UTC by arjunkathuria

solves #197 

* fixes the tests-suite `beckn-integ-test` not able to find "dev/migrations/static-offer-driver-app" directory error

* much less tests fail or skip after this

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
After careful observation of logs and analysis of the issue, it seems the error was the the path defined in the dhall config was relative to the root dir, while the executable ran in the `tests` folder, which, therefore, could not see the `dev` directory. It was solved by making it a relative path and point it to the directory a level above it's root tests folder.

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [x] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

the changes made in the dhall file can be viewed [here](https://github.com/arjunkathuria/nammayatri/commit/2606ae269a0e84622a3985f1dd152248707b545a#diff-ea94d2271f7691f42afcab90e9738fec300899420befe9c3fdc887e562239544)

## Motivation and Context
please see issue #197 

## How did you test it?
This was tested running the standard `stack test` command.

## Screenshots

See the screenshots after the changes (for the "before" screenshots, please see the github issue #197 ):-

1. Required Tests do not skip now, as they did before :-
![Screenshot from 2023-03-17 18-36-26](https://user-images.githubusercontent.com/12858057/226097231-f747589c-fadd-418a-89a4-f9a63741b7a2.png)

AND
![Screenshot from 2023-03-17 18-36-38](https://user-images.githubusercontent.com/12858057/226097343-838fca0d-0725-4ee1-9277-1fbc648a1d0a.png)

2. Much less tests fail now as compared to before:- 
![Screenshot from 2023-03-17 18-37-02](https://user-images.githubusercontent.com/12858057/226097369-7da52d19-435d-4046-b6c0-f5fa8882e1a2.png)

## Additional context
It was found that the new kind of errors seen in the second screenshot of point 1. in the screenshot sections are unlreated to the changes in this PR. They related to a completely different issue for which i'll open a separate issue.

2023-03-20 06:54 UTC, roman-bodavskiy requested changes
-

2023-03-20 08:52 UTC, arjunkathuria commented on Backend/dhall-configs/dev/static-offer-driver-app.dhall
> +          ? "../dev/migrations/static-offer-driver-app"
I seemed odd that this was the only one in the test-logs that error-ed, unless i missed something. Changing just this seems to fix the tests as shown in the issue #197 error vs the screenshots here. If i reverse this change, the tests seem to break again. Clearly this seems to have had an affect.

i just checked and you're right, `stack exec static-offer-driver-app-exe` doesn't work after this change. 

I think i found the real issue here, i'll update the PR

2023-03-20 11:26 UTC, roman-bodavskiy approved these changes

2023-03-20 11:49 UTC, DonDokidon approved these changes

2023-03-22 11:40 UTC, arjunkathuria commented
@hkmangla @NikithShetty Hi guys, this seems good to go.

2023-04-07 10:42 UTC, hkmangla approved these changes

2023-04-07 10:42 UTC, merged