Frontend feat 1288 payment page
nammayatri/nammayatri pull request #2043
Opened 2023-07-30 18:09 UTC by Vignesh-772

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Payment page for YS

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-07-31 10:47 UTC, kavya-shree-s requested changes

2023-07-31 12:49 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Flow.purs
> +                        _       -> "Payment of ₹" <> payload.amount <>" Successful!"
use currency from config

2023-07-31 13:56 UTC, Rohit4997 commented on Frontend/output/Language.Types/externs.cbor
@kavya-shree-s  it was already there, I deleted it

2023-07-31 15:21 UTC, Rohit4997 commented on Frontend/ui-driver/index.js
> +    , service: "in.juspay.becknui"
@Vignesh-772  can you confirm?

2023-07-31 15:27 UTC, Rohit4997 commented on Frontend/ui-driver/index.js
> +    , service: "in.juspay.becknui"
@kavya-shree-s  we are not using it, It was already there we just created a function

2023-08-01 07:58 UTC, kavya-shree-s commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/MainActivity.java
> +            payload.put("merchantId", "yatrisathi");
@Rohit4997 Why "merchantId" is hardcoded

2023-08-01 07:58 UTC, kavya-shree-s commented on Frontend/ui-driver/src/Components/PaymentHistoryModel/View.purs
> +        , imageWithFallback "ny_ic_download_button,https://assets.juspay.in/nammayatri/images/driver/ny_ic_download_button.png"
@Rohit4997 Check this as well

2023-08-01 07:58 UTC, kavya-shree-s commented on Frontend/ui-driver/src/Flow.purs
> +                  bannerTitleColor = if time2PmTo10Am then "#BF4A4E" else "#FCB700",
@Rohit4997 Why code colour is used directly ?

2023-08-01 07:58 UTC, kavya-shree-s commented on Frontend/ui-driver/src/Flow.purs
> +                  actionTextColor = if time2PmTo10Am then "#BF4A4E" else "#FCB700"
Here as well

2023-08-01 07:58 UTC, kavya-shree-s commented on Frontend/ui-driver/src/Flow.purs
> +                modifyScreenState $ AcknowledgementScreenType (\a -> a { data { title = Just (getString PAYMENT_PENDING), description = Just (getString PAYMENT_PENDING_DESC), primaryButtonText = Just
Use proper name other than "a"

2023-08-01 08:05 UTC, kavya-shree-s commented on Frontend/ui-driver/src/Strings/KN.js
> +  AADHAAR_LINKING_REQUIRED : "আধার লিঙ্ক করা আবশ্যক",
Change language

2023-08-01 08:06 UTC, kavya-shree-s commented on Frontend/ui-driver/src/Strings/HI.js
> +  ENTER_AADHAAR_NUMBER : "Enter Aadhaar Number/UID",
Add translation

2023-08-01 08:13 UTC, kavya-shree-s commented on Frontend/ui-driver/src/Strings/KN.js
> +  AADHAAR_LINKING_REQUIRED : "আধার লিঙ্ক করা আবশ্যক",
@Rohit4997

2023-08-01 09:44 UTC, kavya-shree-s approved these changes

2023-08-01 09:51 UTC, merged