frontend/fix: #2223 Multiple Messages Fix
nammayatri/nammayatri pull request #2230
Opened 2023-08-03 17:53 UTC by PraveenGongada

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Fixed Multiple Messages issue in chat

2023-08-03 18:27 UTC, ashishsingh101 requested changes

2023-08-03 18:27 UTC, ashishsingh101 commented on Frontend/ui-driver/index.js
> +    }
don't use PROXY_FN in any case, use defined callback function for all the cases

2023-08-03 18:27 UTC, ashishsingh101 commented on Frontend/ui-customer/index.js
> +    }
don't use PROXY_FN use our defined function to make it more clear and so that its easier to debug and for others to understand

2023-08-03 19:09 UTC, MercyQueen requested changes

2023-08-04 11:40 UTC, MercyQueen requested changes

2023-08-04 11:40 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +                        _ <- pure $ spy "ABCD" (state.data.messagesSize <> " " <> (show $ (length state.data.messages) - 1))
@PraveenGongada can you remove all the spy statements

2023-08-04 11:54 UTC, ashishsingh101 approved these changes

2023-08-04 12:04 UTC, MercyQueen approved these changes

2023-08-04 12:04 UTC, merged