frontend/fix/showlabel in special zone for ios and handle defaultPickupLocation from getting empty
nammayatri/nammayatri pull request #2259
Opened 2023-08-07 06:44 UTC by Shikhar-24

## Type of Change

- [x] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

- Showlabel for Special zone in rideScreen
- Handle defaultPickupLocation and confirmLocationCategory from getting empty in some cases.
- IOS related changes: [link](https://bitbucket.juspay.net/projects/BEC/repos/atlas-ios/pull-requests/101/overview)
- Demo video - [link](https://drive.google.com/file/d/1uIbasDWOGxSbs6ngfUYiNMphrgSmm5ce/view)

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-08-22 12:04 UTC, MercyQueen requested changes

2023-08-22 12:04 UTC, MercyQueen commented on Frontend/ui-customer/src/Flow.purs
> +          modifyScreenState $ HomeScreenStateType (\homeScreen -> bothLocationChangedState{data{polygonCoordinates = fromMaybe "" sourceServiceabilityResp.geoJson,nearByPickUpPoints=pickUpPoints},pro
@Shikhar-24 can you please use the if else condition only for defaultPickupPoint instead of putting this condition for modifyScreenState.

2023-08-22 12:14 UTC, ashishsingh101 requested changes

2023-08-22 12:14 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Flow.purs
> +    _ -> ""
can you use `abs` here

2023-08-22 12:28 UTC, ashishsingh101 requested changes

2023-08-22 12:28 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Flow.purs
> +fetchDefaultPickupPoint :: Array Location -> Number -> Number -> String
move this function to utils

2023-08-23 05:57 UTC, MercyQueen approved these changes

2023-08-23 06:11 UTC, MercyQueen requested changes
squash the commits

2023-08-23 07:10 UTC, MercyQueen approved these changes

2023-08-23 07:22 UTC, ashishsingh101 approved these changes

2023-08-23 08:50 UTC, merged