backend/feat: add disability option for customer
nammayatri/nammayatri pull request #2302
Opened 2023-08-08 09:17 UTC by hkmangla

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-08-10 09:09 UTC, 0utkarsh requested changes

2023-08-10 09:09 UTC, 0utkarsh commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Types/Person/DisabilityType.hs
> +{-# LANGUAGE DerivingStrategies #-}
Should be below copyright

2023-08-10 09:09 UTC, 0utkarsh commented on Backend/app/rider-platform/rider-app/Main/src/Storage/Beam/Person.hs
> +    disabilityId :: B.C f (Maybe Text),
Type should be `Id DisabilityType`

2023-08-17 11:31 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Storage/Queries/Person/DisabilityType.hs
> +            description = description,
Add `onBookingMessage`, `onArrivalMessage`, `onRideStartMessage`.

2023-09-19 16:10 UTC, closed without merging