frontend/fix/#2164 : Fixed bugs in yatri.
nammayatri/nammayatri pull request #2339
Opened 2023-08-09 06:16 UTC by prakharritik

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Fixed ui-bugs.

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-08-09 11:52 UTC, Vignesh-772 requested changes

2023-08-09 11:52 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Components/RecordAudioModel/View.purs
> +     , textSize FontSize.a_19
Can you append the font property array instead of hard coding.

2023-08-11 13:05 UTC, aryan-13 approved these changes

2023-09-20 17:52 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Components/QuoteListModel/View.purs
> +        -- , imageWithFallback $ "ny_ic_no_quotes_color," <> getAssetStoreLink FunctionCall  <> "ny_ic_no_quotes_color.png"
remove if it not required

2023-09-20 17:53 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +      _ = spy "quotes2" quoteList
remove `spy`

2023-09-20 17:57 UTC, Vignesh-772 requested changes

2023-09-20 17:57 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +  in
remove unwanted `spy` statements

2023-09-20 17:57 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Screens/RideHistoryScreen/ComponentConfig.purs
> +        imageUrl = if (getValueToLocalStore VEHICLE_VARIANT /= "AUTO_RICKSHAW") then "ny_ic_no_past_rides," <> (getCommonAssetStoreLink FunctionCall) <> "ny_ic_no_past_rides.png" else "ny_ic_no_past_
use proper function to get remote assets

2023-09-25 06:54 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +                    if (state.props.autoPayBanner && state.props.driverStatusSet == ST.Offline &&  (spy "xys" (getValueFromConfig "autoPayBanner")) ) then autoPayBannerView state push true else dummy
Remove Spy

2023-09-25 06:56 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +  _ = spy "zxc testing" state
Please remove logs

2023-09-25 07:02 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/ReferralScreen/Controller.purs
> +  if (state.props.enableReferralFlowCount >= 5 && (getMerchant FunctionCall) /= YATRI) then do
We need referralFlow for yatri

2023-09-25 07:05 UTC, MercyQueen requested changes

2023-09-25 07:05 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +          <> if state.data.rateCard.vehicleVariant == "AUTO_RICKSHAW" then [{key : "ERNAKULAM_LIMIT_CHARGE", val : (getString ERNAKULAM_LIMIT_CHARGE)}] else []
@prakharritik but this won't be valid for nammayatri

2023-09-25 07:05 UTC, MercyQueen commented on Frontend/ui-driver/src/Components/BottomNavBar/Controller.purs
> +    (if (getMerchant FunctionCall /= YATRISATHI) then [{
create a variable in configuration and use that instead of adding a merchant check.

2023-09-25 07:05 UTC, MercyQueen commented on Frontend/ui-driver/src/Components/BottomNavBar/Controller.purs
> +  ScreenNames.REFERRAL_SCREEN -> if (getMerchant FunctionCall == YATRI) then 2
make it configurable

2023-09-25 07:05 UTC, MercyQueen commented on Frontend/ui-driver/src/Flow.purs
> +  let currStage = if (getMerchant FunctionCall) == YATRI then do
remove merchant check from here as well.

2023-09-25 07:05 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +                    if (state.props.autoPayBanner && state.props.driverStatusSet == ST.Offline &&  (spy "xys" (getValueFromConfig "autoPayBanner")) ) then autoPayBannerView state push true else dummy
remove spy statements

2023-09-25 07:05 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/RideHistoryScreen/ComponentConfig.purs
> +import Prelude ((<>), (==), (/=))
remove unwanted imports (==)

2023-09-26 11:14 UTC, prakharritik commented on Frontend/ui-customer/src/Components/QuoteListModel/View.purs
> +        , imageWithFallback $ if state.vehicleVariant == "AUTO_RICKSHAW" then "ny_ic_no_quotes_auto," <> getAssetStoreLink FunctionCall  <> "ny_ic_no_quotes_auto.png" else "ny_ic_no_quotes_color," <>
moved to common

2023-09-28 09:55 UTC, ashishsingh101 submitted a review, later dismissed

2023-09-28 10:27 UTC, MercyQueen approved these changes

2023-09-28 10:32 UTC, Vignesh-772 commented on Frontend/android-native/mobility-customer/src/main/assets/juspay/v1-configuration.js
> +    "CUSTOMER_TIP" : {
can you update these values in CommonConfig.purs and update required v1-Configurations according

2023-09-28 10:32 UTC, Vignesh-772 commented on Frontend/ui-common/src/Components/RateCard/View.purs
> +          ]
Append the font props

2023-09-28 10:33 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +          <> if state.data.rateCard.vehicleVariant == "AUTO_RICKSHAW" && (MU.getMerchant FunctionCall) == MU.YATRI then [{key : "CHARGE_DESCRIPTION", val : (getString ERNAKULAM_LIMIT_CHARGE)}] else [
move this also to config don't add merchant checks

2023-09-28 10:34 UTC, Vignesh-772 requested changes
Resolve comments

2023-09-29 04:30 UTC, Vignesh-772 approved these changes

2023-10-03 18:36 UTC, ashishsingh101 requested changes

2023-10-03 18:36 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +      nightCharges = withinTimeRange nightShiftStart nightShiftEnd (convertUTCtoISC(getCurrentUTC "") "HH:mm:ss")
same thing we are doing for single estimate flow also, can you make it common

2023-10-03 21:18 UTC, ashishsingh101 requested changes

2023-10-03 21:18 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +getNightChargeInfo :: Array EstimateAPIEntity -> {nightShiftMultiplier :: Number, nightCharges :: Boolean}
define return `type` here with generic name

2023-10-03 21:18 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +getNightChargeInfo estimates =
since type are same for both cases, make return type of this function with almost all of the fields and we can use only fields which are required

2023-10-03 21:18 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +getNightChargeInfo estimates =
like it should return `pickupCharges`, `additionalCharges` ... which can we used by by single estimate flow for rate card

2023-10-09 04:39 UTC, MercyQueen submitted a review, later dismissed

2023-10-09 04:57 UTC, Vignesh-772 commented on Frontend/android-native/mobility-customer/src/main/assets/juspay/v1-configuration.js
> +    "showChargeDesc" : false,
can you remove the default values from the v1-configuration. Add only the values which is changing.

2023-10-09 04:59 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Helpers/Utils.purs
> +getVehicleSize unit = 90
can we move this to config?

2023-10-09 05:00 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +    let tipConfig = (getValueFromConfig "customerTip")
use config from state. try to reduce the use of `getValueFromConfig`.

2023-10-09 05:02 UTC, Vignesh-772 reviewed
Resolve the comments

2023-10-10 07:09 UTC, Rohit4997 requested changes

2023-10-10 07:09 UTC, Rohit4997 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +          {key : "DRIVER_ADDITIONS_ARE_CALCULATED_AT_RATE", val : (if (state.data.rateCard.vehicleVariant /= "AUTO_RICKSHAW")
I think we already have AUTO_RICKSHAW as enum, Can we use that ?

2023-10-10 07:09 UTC, Rohit4997 commented on Frontend/ui-customer/src/Services/Backend.purs
> +    srcMarker : if isPreviousVersion (getValueToLocalStore VERSION_NAME) (getPreviousVersion "") then "ny_ic_auto_map"
Can we check this version and remove this check if not required ?

2023-10-10 07:09 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/RideHistoryScreen/ComponentConfig.purs
> +        imageUrl = if (getValueToLocalStore VEHICLE_VARIANT /= "AUTO_RICKSHAW") then "ny_ic_no_past_rides," <> (getCommonAssetStoreLink FunctionCall) <> "ny_ic_no_past_rides.png" else "ny_ic_no_past_
Can we use VEHICLE_VARIANT as ENUM here ?

2023-10-10 07:09 UTC, Rohit4997 commented on Frontend/ui-driver/src/Components/RecordAudioModel/View.purs
> +          , textSize FontSize.a_14
Append fontstyle

2023-10-10 07:11 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/RideHistoryScreen/ComponentConfig.purs
> +        imageUrl = if (getValueToLocalStore VEHICLE_VARIANT /= "AUTO_RICKSHAW") then "ny_ic_no_past_rides," <> (getCommonAssetStoreLink FunctionCall) <> "ny_ic_no_past_rides.png" else "ny_ic_no_past_
Also check `getVehicleImage` can be used here ?

2023-10-10 07:29 UTC, MercyQueen approved these changes

2023-10-10 10:34 UTC, Rohit4997 approved these changes

2023-10-10 11:24 UTC, MercyQueen submitted a review, later dismissed

2023-10-10 11:25 UTC, Vignesh-772 approved these changes

2023-10-11 13:36 UTC, Rohit4997 approved these changes

2023-10-11 13:56 UTC, ashishsingh101 approved these changes

2023-10-11 13:56 UTC, merged