frontend/feature: #227 Driver-Alternate-Nu
nammayatri/nammayatri pull request #238
Opened 2023-03-21 11:19 UTC by mohdshoaib18169

mber

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-03-23 19:36 UTC, Vignesh-772 requested changes

2023-03-23 19:36 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Components/InAppKeyboardModal/View.purs
> +              , linearLayout
create a separate view function for this layout. it seems very long

2023-03-23 19:36 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Flow.purs
> +                 -- pure $ toast $ (decodeErrorCode errorPayload.response.errorCode)
remove commented lines

2023-03-23 19:36 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Screens/Types.purs
> +data KeyboardModalType = ALTERNATE_NUMBER | OTP | NONE
instead oh `ALTERNATE_NUMBER` make it `MOBILE_NUMBER` which makes it more generic.

2023-03-23 19:36 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Services/Backend.purs
> +--removeAlternateNumberBT :: RemoveAlternateNumberRequest -> FlowBT String RemoveAlternateNumberResp
remove commented lines from all place.

2023-03-30 07:35 UTC, Rohit4997 commented
@mohdshoaib18169  Can you rebase this PR

2023-04-03 06:38 UTC, Rohit4997 commented
> @mohdshoaib18169 Can you rebase this PR

@mohdshoaib18169  can you also add video attachment here ?

2023-04-13 18:01 UTC, Vignesh-772 requested changes

2023-04-13 18:01 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Screens/HomeScreen/Handler.purs
> +        props  { isEditAlternateMobile = false, keyboardModalType = MOBILE__NUMBER}})
change the state in Controller itself

2023-04-13 18:01 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +enterOtpState state = let
move config to componentConfig

2023-04-14 11:58 UTC, mohdshoaib18169 commented on Frontend/ui-driver/src/Components/InAppKeyboardModal/View.purs
> +otp :: forall w . (Action -> Effect Unit) -> InAppKeyboardModalState -> PrestoDOM (Effect Unit) w
changed bro

2023-04-14 11:59 UTC, mohdshoaib18169 commented on Frontend/ui-driver/src/Flow.purs
> +              modifyScreenState $ DriverDetailsScreenStateType (\driverDetailsScreen -> updatedState)
done

2023-04-14 11:59 UTC, mohdshoaib18169 commented on Frontend/ui-driver/src/Flow.purs
> +       let toast_value = (if (state.props.isEditAlternateMobile == false) then (getString NUMBER_ADDED_SUCCESSFULLY) else (getString NUMBER_EDITED_SUCCESSFULLY))
done

2023-04-14 11:59 UTC, mohdshoaib18169 commented on Frontend/ui-driver/src/Resource/Localizable/Language/KN.purs
> +  --APP_NOT_WORKING -> "ಅಪ್ಲಿಕೇಶನ್ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿಲ್ಲ"
done

2023-04-14 11:59 UTC, mohdshoaib18169 commented on Frontend/ui-driver/src/Screens/DriverDetailsScreen/Controller.purs
> +data ScreenOutput = GoBack DriverDetailsScreenState | ValidateAlternateNumber DriverDetailsScreenState | ResendAlternateNumberOTP DriverDetailsScreenState | VerifyAlternateNumberOTP DriverDetailsScre
done

2023-04-14 11:59 UTC, mohdshoaib18169 commented on Frontend/ui-driver/src/Screens/DriverDetailsScreen/View.purs
> +removeAlternateNumberConfig :: ST.DriverDetailsScreenState -> PopUpModalConfig.Config
done

2023-04-14 12:00 UTC, mohdshoaib18169 commented on Frontend/ui-driver/src/Screens/HomeScreen/Handler.purs
> +        props  { isEditAlternateMobile = false, keyboardModalType = MOBILE__NUMBER}})
did in flow.purs

2023-04-14 12:00 UTC, mohdshoaib18169 commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +enterOtpState state = let
done

2023-05-08 18:29 UTC, witcher-shailesh commented
Duplicate PR, changes already merged.

2023-05-08 18:29 UTC, closed without merging