Frontend feat 2361 Whatsapp OTP Flow added for YS
nammayatri/nammayatri pull request #2410
Opened 2023-08-11 11:08 UTC by S-PRAVINKUMAR

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-08-22 11:39 UTC, MercyQueen requested changes

2023-08-22 11:39 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/Controller.purs
> +    let newState = state {data {otpChannel = "WHATSAPP"}}
@S-PRAVINKUMAR can we create a data for otpChannel instead of using strings.

2023-08-22 11:39 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/ComponentConfig.purs
> +      , visibility = if (getMerchant FunctionCall) == YATRISATHI then VISIBLE else GONE
@S-PRAVINKUMAR use a config variable which can be fetched from v1-configuration and used , instead of adding merchant check.

2023-08-22 11:39 UTC, MercyQueen commented on Frontend/ui-common/src/Components/MobileNumberEditor/View.purs
> +        [ Anim.fadeIn config.countryCodeField.countryCodeOptionExpended
@S-PRAVINKUMAR please correct the spelling here.

2023-08-22 11:39 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/Controller.purs
> +    if  validatorResp == MVR.Valid then do
@S-PRAVINKUMAR put this condition inside a variable as it is being used thrice. `validatorResp == MVR.Valid`

2023-08-22 11:39 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/Controller.purs
> +    if validatorResp == MVR.Valid then do
@S-PRAVINKUMAR here also put the condition inside variable.

2023-08-22 11:39 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/View.purs
> +            , visibility  if state.props.countryCodeOptionExpended then GONE else VISIBLE
@S-PRAVINKUMAR use this condition to call the linear layout itself, instead of changing the visibility.

2023-08-23 06:09 UTC, MercyQueen reviewed
added comments

2023-08-23 06:09 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/ComponentConfig.purs
> +import MerchantConfig.Utils (getMerchant, Merchant(..))
@S-PRAVINKUMAR Remove unwanted comments.

2023-08-23 06:09 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/Controller.purs
> +eval (MobileNumberEditTextAction (MobileNumberEditorController.FocusChanged boolean)) state = continue state { props{ mNumberEdtFocused = boolean, countryCodeOptionExpanded = not boolean}}
give some meaningful name instead of `boolean`.

2023-08-23 06:51 UTC, MercyQueen approved these changes

2023-08-23 07:12 UTC, ashishsingh101 requested changes

2023-08-23 07:12 UTC, ashishsingh101 commented on Frontend/ui-common/src/Components/MobileNumberEditor/Controller.purs
> +    }
move this to Animation Config module

2023-08-23 07:12 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/View.purs
> +        , if (not state.props.countryCodeOptionExpanded) && state.data.config.internationalNumberEnabled then whatsAppOTPButtonView state push else (textView [height $ V 0])
rename textView to dummyView

2023-08-23 07:44 UTC, ashishsingh101 requested changes

2023-08-23 07:44 UTC, ashishsingh101 commented on Frontend/ui-common/src/Animation/Animation.purs
> +listExpandingAnimationConfig :: Boolean -> AnimConfig
please move it to animation's config.purs

2023-08-23 08:56 UTC, ashishsingh101 approved these changes

2023-08-23 09:27 UTC, merged