backend/feat: #1877 post ride safety
nammayatri/nammayatri pull request #2533
Opened 2023-08-18 12:50 UTC by PraveenGongada

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Added `is_safe` and `issue_id` fields to driver rating table for night ride safety

### Additional Changes

- [x] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-08-23 10:20 UTC, PraveenGongada commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Queries/Rating.hs
> +updateRating (Id ratingId) (Id driverId) newRatingValue newFeedbackDetails newIssueId newStatus = do
Here it is being used as text, why ID type when we are not using it as ID?

2023-09-05 08:05 UTC, 0utkarsh commented
- After completing a night ride (between 10 PM and 6 AM), customers will see a safety popup on their app screen.
- If the customer selects "Unsafe," the support center will be notified immediately.

The logics for above will be handled from frontend? What about the following?

- The customer will be given the option to select specific issues they encountered during the ride (e.g., inappropriate behavior, route deviation, reckless driving, etc.).

2023-09-05 08:06 UTC, 0utkarsh requested changes

2023-09-05 11:28 UTC, PraveenGongada commented on Backend/app/rider-platform/rider-app/Main/src/Storage/Beam/Issue.hs
> +    rideId :: B.C f (Maybe Text),
We can't use Id types here after KV changes right?

2023-09-05 12:03 UTC, 0utkarsh commented on Backend/app/rider-platform/rider-app/Main/src/Storage/Beam/Issue.hs
> +    rideId :: B.C f (Maybe Text),
Sure, I am approving this PR, can you answer the above comment too? We can merge it then

2023-09-05 12:03 UTC, 0utkarsh submitted a review, later dismissed

2023-09-06 11:54 UTC, PraveenGongada commented
> 

yes frontend will show pop up and send the specific issue in the sendIssue api

2023-09-07 10:19 UTC, hkmangla requested changes

2023-09-07 10:19 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/UI/Support.hs
> +  { issueId :: Text
Not a backward compatible change.

2023-09-12 09:36 UTC, soumyajit2304 approved these changes

2023-10-30 12:03 UTC, closed without merging