frontend/feat/#1063: added clevertap events for cust and driver
nammayatri/nammayatri pull request #2618
Opened 2023-08-22 15:36 UTC by ashkriti

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description
Added the Clevertap events for the customer and driver

## Motivation and Context
https://github.com/nammayatri/nammayatri/issues/1063

## How did you test it?
Tested Manually

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-08-29 10:13 UTC, ashishsingh101 requested changes

2023-08-29 10:13 UTC, ashishsingh101 commented on Frontend/ui-common/src/Engineering/Helpers/LogEvent.purs
> +    pure unit
use `void` and remove pure unit

2023-08-29 10:13 UTC, ashishsingh101 commented on Frontend/ui-common/src/Engineering/Helpers/LogEvent.purs
> +  pure unit
no need for `pure unit`

2023-08-29 10:25 UTC, ashishsingh101 requested changes

2023-08-29 10:25 UTC, ashishsingh101 commented on Frontend/ui-common/src/Engineering/Helpers/LogEvent.purs
> +}
don't define same `type` multiple times

2023-08-29 10:25 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Flow.purs
> +                                        let (FareBreakupAPIEntity fareBreakup) = fromMaybe HomeScreenData.dummyFareBreakUp (resp.fareBreakup !! 0)
remove if not using

2023-08-30 11:10 UTC, ashkriti commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/NotificationUtils.java
> +            {if (CANCELLED_PRODUCT.equals(notificationType)) {
Done

2023-08-30 11:11 UTC, ashkriti commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +export const cleverTapEvent = function(event){
Done

2023-09-01 08:52 UTC, Vignesh-772 requested changes

2023-09-01 08:52 UTC, Vignesh-772 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/NotificationUtils.java
> +            {if (CANCELLED_PRODUCT.equals(notificationType)) {
single function I meant will push the firebase log also. like we are doing in purescript.

2023-09-01 10:50 UTC, Vignesh-772 approved these changes

2023-09-01 12:20 UTC, kavya-shree-s approved these changes

2023-09-01 12:38 UTC, ashishsingh101 approved these changes

2023-09-01 12:38 UTC, merged