frontend/feat/#1063: added clevertap properties
nammayatri/nammayatri pull request #2721
Opened 2023-08-24 14:32 UTC by ashkriti

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Integrated API for the properties required for CleverTap
Added the push templets for CleverTap notification

## Motivation and Context
https://github.com/nammayatri/nammayatri/issues/1063

## How did you test it?
Tested Manually

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-09-20 18:00 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Flow.purs
> +      let currentTime = convertTo12HourFormat (convertUTCtoISC (getCurrentUTC "") "HH:mm:ss")
try to use `convertTo12HourFormat` existing function

2023-09-20 18:02 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Flow.purs
> +      (PersonStatsRes resp) <- Remote.getPersonStatsBT ""
move it to a separate function

2023-10-05 13:02 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/CustomerUtils/InvoiceScreen/Controller.purs
> +        let _ = unsafePerformEffect $ logEventWithMultipleParams state.data.logField "ny_user_invoice_download" $ [ { key : "Base fare", value : unsafeToForeign state.data.selectedItem.baseFare},
here unsafePerformEffect is not required

2023-10-11 08:25 UTC, Vignesh-772 approved these changes

2023-10-11 08:26 UTC, Vignesh-772 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/MobilityAppBridge.java
> +        if (clevertapDefaultInstance != null) {
can you set the clevertap instance if it null

2023-10-11 08:32 UTC, Vignesh-772 requested changes

2023-10-11 08:32 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Services/Backend.purs
> +getPersonStatsBT :: String -> FlowBT String PersonStatsRes
is it required as it is not used any where

2023-10-11 09:18 UTC, S-PRAVINKUMAR requested changes

2023-10-11 10:41 UTC, Vignesh-772 approved these changes

2023-10-12 09:29 UTC, Rohit4997 requested changes

2023-10-12 10:38 UTC, Vignesh-772 submitted a review, later dismissed

2023-10-12 10:43 UTC, Rohit4997 approved these changes

2023-10-12 13:35 UTC, S-PRAVINKUMAR approved these changes

2023-10-12 18:34 UTC, Vignesh-772 approved these changes

2023-10-12 18:52 UTC, merged