frontend/fix #2361 whatsapp otp configuration added
nammayatri/nammayatri pull request #2749
Opened 2023-08-25 14:17 UTC by S-PRAVINKUMAR

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-09-20 18:13 UTC, Vignesh-772 approved these changes

2023-09-30 19:07 UTC, ashishsingh101 requested changes

2023-09-30 19:07 UTC, ashishsingh101 commented on Frontend/android-native/app/src/user/jatriSaathi/assets/juspay/v1-configuration.js
> +  , "enableWhatsappOTP" : ["BD"]
can we remove this from `v1-configuration` and only add in Default config with Country code

2023-09-30 19:07 UTC, ashishsingh101 commented on Frontend/ui-customer/src/MerchantConfigs/CommonConfig.purs
> +        , enableWhatsappOTP : []
only `DefaultConfig` will work

2023-10-01 09:01 UTC, ashishsingh101 approved these changes

2023-10-01 09:05 UTC, merged