Frontend/feat/#2296 Accessibility changes to support talkback
nammayatri/nammayatri pull request #2773
Opened 2023-08-28 13:46 UTC by aryan-13

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Accessibility changes to support talkback

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-08-31 13:09 UTC, witcher-shailesh requested changes

2023-09-01 09:03 UTC, aryan-13 commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +  if (window.__OS == "IOS") {
Because we needed some small modification in `requestKeyboardShow` for android specifically, which was not required for IOS.

2023-09-01 09:08 UTC, aryan-13 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/MobilityAppBridge.java
> +                        dots[i].setContentDescription("Page Indicator, Page "  +( i+1) + " : Swipe or Tap To Go To Next Page\"");
On click on any of the 3 dots in carousel view, it would take us to corresponding page.

2023-09-01 11:11 UTC, kavya-shree-s approved these changes

2023-09-01 11:14 UTC, witcher-shailesh approved these changes

2023-09-01 11:17 UTC, merged