Frontend/fix: #2546 Payment History Screen fix
nammayatri/nammayatri pull request #2778
Opened 2023-08-28 15:26 UTC by Vignesh-772

## Type of Change

Payment History Screen fix for showing the all transaction

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-09-20 15:26 UTC, Rohit4997 submitted a review, later dismissed

2023-09-22 14:23 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/HomeScreen/ComponentConfig.purs
> +                          "EN_US" -> "To continue using Yatri Sathi, please complete your payment"
@Vignesh-772  if variable is removed then you can add it in translations.
No need to do like this

2023-09-22 14:31 UTC, kavya-shree-s commented on Frontend/ui-common/src/Engineering/Helpers/Utils.purs
> +loaderText mainTxt subTxt = void $ modifyState (\(GlobalState state) -> GlobalState state { loaderOverlay { data { title = mainTxt, subTitle = subTxt } } })
Why is check for IOS removed ?

2023-09-22 14:50 UTC, kavya-shree-s requested changes

2023-09-22 14:50 UTC, kavya-shree-s commented on Frontend/ui-driver/src/Screens/RideHistoryScreen/Transformer.purs
> +  Just a ->
Use proper variables

2023-09-22 14:50 UTC, kavya-shree-s commented on Frontend/ui-driver/src/Services/Accessor.purs
> +_orderId :: forall a b c. Newtype a { orderId :: b | c } => Lens' a b
Remove `_orderId` as it is not used

2023-09-22 14:52 UTC, Vignesh-772 commented on Frontend/ui-common/src/Engineering/Helpers/Utils.purs
> +loaderText mainTxt subTxt = void $ modifyState (\(GlobalState state) -> GlobalState state { loaderOverlay { data { title = mainTxt, subTitle = subTxt } } })
It is fixed no need of native loader

2023-09-22 14:52 UTC, Vignesh-772 commented on Frontend/ui-driver/spago.dhall
> -  , "lite-decode"
added back

2023-09-22 16:33 UTC, MercyQueen approved these changes

2023-09-23 06:11 UTC, kavya-shree-s approved these changes

2023-09-23 06:12 UTC, merged