frontend/feat/#1063: added push notification for clevertap for xiaomi…
nammayatri/nammayatri pull request #2814
Opened 2023-08-30 13:26 UTC by ashkriti

… and huawei

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Integrated CleverTap push notification for Xiaomi and Huawei

## Motivation and Context
https://github.com/nammayatri/nammayatri/issues/1063

## How did you test it?
Tested Manually

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-09-01 09:13 UTC, kavya-shree-s requested changes

2023-09-01 09:13 UTC, kavya-shree-s commented on Frontend/android-native/app/libs/MiPush_SDK_Client_5_1_5-G_3rd.aar
@ashkriti Why aar file is required, Looking like all the sdks are from remote

2023-09-01 10:38 UTC, ashkriti commented on Frontend/android-native/app/libs/MiPush_SDK_Client_5_1_5-G_3rd.aar
It is required to configure our app with CleverTap Xiaomi plugin according to their document

2023-09-20 18:27 UTC, Vignesh-772 requested changes

2023-09-20 18:27 UTC, Vignesh-772 commented on Frontend/android-native/mobility-app/src/main/AndroidManifest.xml
> +                <action android:name="com.huawei.push.action.MESSAGING_EVENT" />
these two permissions are not added 
```
    <permission
        android:name="yourpackage.permission.MIPUSH_RECEIVE"
        android:protectionLevel="signature" />
    <uses-permission android:name="yourpackage.permission.MIPUSH_RECEIVE" />
    <uses-permission android:name="android.permission.VIBRATE" />
```

2023-09-21 12:42 UTC, ashkriti commented on Frontend/android-native/mobility-app/src/main/AndroidManifest.xml
> +                <action android:name="com.huawei.push.action.MESSAGING_EVENT" />
It is already added in the .aar file

2023-10-05 12:57 UTC, Vignesh-772 submitted a review, later dismissed

2023-10-12 08:17 UTC, Rohit4997 requested changes

2023-10-12 08:17 UTC, Rohit4997 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/MyHmsMessageService.java
> +public class MyHmsMessageService extends HmsMessageService {
Please Rename `MyHmsMessageService`

2023-10-12 10:58 UTC, Rohit4997 approved these changes

2023-10-12 11:00 UTC, Rohit4997 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/HmsMessageService.java
> +package in.juspay.mobility.app;
Add Copyright

2023-10-12 11:00 UTC, Rohit4997 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/XiaomiMessageReceiver.java
> +package in.juspay.mobility.app;
Add Copyright

2023-10-12 11:29 UTC, ashkriti commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/XiaomiMessageReceiver.java
> +package in.juspay.mobility.app;
added

2023-10-12 11:29 UTC, ashkriti commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/HmsMessageService.java
> +package in.juspay.mobility.app;
added

2023-10-12 11:31 UTC, Rohit4997 approved these changes

2023-10-12 13:14 UTC, kavya-shree-s approved these changes

2023-10-12 13:15 UTC, merged