frontend/fix: #2698 Chat Related Fixes
nammayatri/nammayatri pull request #2816
Opened 2023-08-30 13:40 UTC by PraveenGongada

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

- Fixed chat scroll view on keyBoardOpen
- changed title of In-App Notification

Closes #2698

2023-09-20 12:35 UTC, Vignesh-772 requested changes
Do the changes as discussed

2023-09-20 18:29 UTC, Vignesh-772 approved these changes

2023-09-21 06:49 UTC, MercyQueen requested changes

2023-09-21 06:49 UTC, MercyQueen commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/ChatService.java
> +            case "Yatri Partner" :
@PraveenGongada the app_name for Yatri partner is `Yatri Driver` .

2023-09-21 06:49 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/HomeScreen/Controller.purs
> +    _ <- pure $ scrollToEnd (getNewIDWithTag "ChatScrollView") true
use void here and remove pure unit

2023-09-21 06:49 UTC, MercyQueen commented on Frontend/ui-driver/index.js
> +  } else if (event == "onKeyboardOpen") {
use `||` operator to combine the two else if statements

2023-09-21 06:49 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +    _ <- pure $ scrollToEnd (getNewIDWithTag "ChatScrollView") true
use void here as well.

2023-09-21 06:49 UTC, MercyQueen commented on Frontend/ui-customer/index.js
> +  } else if (event == "onKeyboardOpen") {
@PraveenGongada here also combine if else statements using `||` operator.

2023-09-21 09:36 UTC, MercyQueen submitted a review, later dismissed

2023-10-12 07:49 UTC, Rohit4997 requested changes

2023-10-12 07:49 UTC, Rohit4997 commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/MobilityCommonBridge.java
> +        if(onGlobalLayoutListener != null && bridgeComponents.getActivity() != null) {
This condition can be sinplified

2023-10-12 07:49 UTC, Rohit4997 commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/MobilityCommonBridge.java
> +                        onKeyboardVisibilityListener.onVisibilityChanged(isShown);
Can't we call simple callback here?
`                        String encoded = Base64.encodeToString("{}".getBytes(), Base64.NO_WRAP);
                        String command = String.format("window[\"onEvent'\"]('%s',atob('%s'))", visible ? "onKeyboardOpen" : "onKeyboardClose", encoded);
                        bridgeComponents.getJsCallback().addJsToWebView(command);`
                        
 What is the use of interface ?

2023-10-12 07:49 UTC, Rohit4997 commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +export const storeKeyBoardCallback = function (cb) {
Used uncurried function

2023-10-12 07:49 UTC, Rohit4997 commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.purs
> +foreign import storeKeyBoardCallback :: forall action. (action -> Effect Unit) -> (String -> action) -> Effect Unit
Use uncurried function

2023-10-12 07:49 UTC, Rohit4997 commented on Frontend/ui-customer/index.js
> +  } else if (event == "onKeyboardOpen" || event == "onKeyboardClose") {
`else if ((event == "onKeyboardOpen" || event == "onKeyboardClose") && window.keyBoardCallback)`
Simplify this

2023-10-12 09:39 UTC, Rohit4997 submitted a review, later dismissed

2023-10-12 10:39 UTC, Vignesh-772 submitted a review, later dismissed

2023-10-12 13:09 UTC, merged