frontend/feat/#2868/firebase_realtime_database_support : retrieval of…
nammayatri/nammayatri pull request #2869
Opened 2023-09-02 10:31 UTC by Anuragini-2506

… static data for kiosk locations from firebase

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-09-20 18:59 UTC, Vignesh-772 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/MainActivity.java
> +                ArrayList<KioskLocation> kioskLocations =  (ArrayList<KioskLocation>) dataSnapshot.getValue();
getting warnings in this line

2023-09-20 19:00 UTC, Vignesh-772 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/MainActivity.java
> +            public void onDataChange(DataSnapshot dataSnapshot) {
annotate with `@NonNull`

2023-09-20 19:01 UTC, Vignesh-772 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/MainActivity.java
> +    private void getFirebaseRealTimeDatabase(){
if possible try to move it to mobility-driver module

2023-09-20 19:01 UTC, Vignesh-772 requested changes
resolve comments

2023-09-21 04:47 UTC, Vignesh-772 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/MainActivity.java
> +                sharedPref.edit().putString("KIOSK_LOCATIONS", "" + jsArray).apply();
use `jsArray.toString()`

2023-12-07 11:24 UTC, witcher-shailesh commented
Not required, as of now. Could be replaced with RemoteConfigs in future

2023-12-07 11:24 UTC, closed without merging