frontend/fix: #298 Added new short ride distance flow modals
nammayatri/nammayatri pull request #300
Opened 2023-03-24 14:23 UTC by VD321

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Added new popup modals for short distance ride flow.
Rides <10 meter will not have book ride option
For Rides >10 different modal with book ride/ go back options will show up.

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-03-24 15:17 UTC, hkmangla requested changes

2023-03-24 15:17 UTC, hkmangla commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +    if state.props.distance < minDistThreshold then popUpConfig2' else popUpConfig1'
name configs properly. Instead of naming them 1 and 2.

2023-03-24 15:17 UTC, hkmangla commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +        { gravity = CENTER
Most the things in both configs are same. Please reuse common things. Instead of just creating the whole new view.

2023-03-24 19:58 UTC, ks-shree requested changes
@VD321 Can you attach screenshot the UI and Is it tested in IOS ?

2023-03-24 19:58 UTC, ks-shree commented on Frontend/ui-customer/src/Resources/Localizable/Language/KN.purs
> +  THE_DESTINATION_IS_TOO_CLOSE -> "ಆಟೋವನ್ನು ಬುಕ್ ಮಾಡಲು ತಲುಪಬೇಕಾದ ಸ್ಥಳವು ತುಂಬಾ ಹತ್ತಿರದಲ್ಲಿದೆ. ನೀವು ಬೇರೆ ಪಿಕಪ್ ಮತ್ತು ಡ್ರಾಪ್ ಹೊಂದಿರುವಿರಾ ಎಂಬುದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ."
Update this
"ಗಮ್ಯಸ್ಥಾನವು ತುಂಬಾ ಹತ್ತಿರದಲ್ಲಿದೆ. ನೀವು ಬೇರೆ ಪಿಕಪ್ ಮತ್ತು ಡ್ರಾಪ್ ಹೊಂದಿರುವಿರಾ ಎಂಬುದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ."

2023-03-24 19:58 UTC, ks-shree commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +        , margin = (Margin 24 0 24 0)
use `MarginHorizontal`

2023-03-24 19:58 UTC, ks-shree commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
>            , margin = (Margin 0 16 0 20)
Use MarginVertical

2023-03-24 19:58 UTC, ks-shree commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +        , margin = (Margin 12 0 0 0)
use MarginLeft

2023-04-02 08:10 UTC, Vignesh-772 requested changes

2023-04-02 08:10 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Services/Config.purs
> +getMinThresholdDist :: Int
Move this to `Constant.purs` file.

2023-04-02 08:10 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +  continue state{data {destination = ""},props{isSource = Just false, isPopUp = NoPopUp, rideRequestFlow = false, currentStage = SearchLocationModel, searchId = "", isSearchLocation = SearchLocation}
I think you have to clear lat, long of destination and destinationAddress also, if you are clearing destination address .

2023-04-11 19:25 UTC, Vignesh-772 approved these changes

2023-07-12 08:19 UTC, witcher-shailesh commented
Will re-open if further required in future

2023-07-12 08:19 UTC, closed without merging