frontend/#2999/open navigation with walk mode
nammayatri/nammayatri pull request #3000
Opened 2023-09-06 12:57 UTC by ashishsingh101

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-09-06 15:39 UTC, aryan-13 approved these changes

2023-09-06 19:51 UTC, witcher-shailesh requested changes
Is this change for walking towards pickup point?

2023-09-06 19:51 UTC, witcher-shailesh commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +            var query = mode == "WALK" ? window.appConfig.navigationAppConfig.walkQuery : window.appConfig.navigationAppConfig.query;
what if query is null? (not present in config)

2023-09-06 19:51 UTC, witcher-shailesh commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +            var query = mode == "WALK" ? window.appConfig.navigationAppConfig.walkQuery : window.appConfig.navigationAppConfig.query;
as I see you didn't added it for other merchants

2023-09-08 12:22 UTC, witcher-shailesh approved these changes

2023-09-08 12:22 UTC, merged