frontend/feat: #206 Added In-App Messaging
nammayatri/nammayatri pull request #301
Opened 2023-03-24 14:57 UTC by PraveenGongada

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Added In-App Messaging Feature

2023-04-11 12:32 UTC, Vignesh-772 requested changes

2023-04-11 13:11 UTC, PraveenGongada commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/CommonJsInterface.java
> +                                setKeysInSharedPrefs("CHAT_CHANNEL_ID", channelId);
Done

2023-04-12 16:22 UTC, Vignesh-772 requested changes

2023-04-12 16:22 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +  if ((isLocalStageOn RideAccepted) || (isLocalStageOn RideStarted) || (isLocalStageOn ChatWithDriver)) && ((getValueToLocalStore TRACKING_ID) == trackingId) then do
use `any`  function to handle this case

2023-04-12 16:22 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +          dstLat = if state.props.currentStage == RideAccepted || (isLocalStageOn ChatWithDriver) then state.data.driverInfoCardState.sourceLat else state.data.driverInfoCardState.destinationLat
one variable is checked in state one and another from local storage why?

2023-04-12 16:22 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Components/RideActionModal/View.purs
> +  [ width MATCH_PARENT
why this is `match_parent` ?

2023-04-12 16:22 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +  if (getValueToLocalStore RIDE_STATUS_POLLING) == "True" && (getValueToLocalStore RIDE_STATUS_POLLING_ID) == pollingId && (isLocalStageOn RideAccepted || isLocalStageOn ChatWithCustomer) then do
use `any` function

2023-04-12 16:23 UTC, Vignesh-772 commented
Resolve conflicts

2023-04-12 16:36 UTC, PraveenGongada commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/CommonJsInterface.java
> +                AlarmManager manager = (AlarmManager) context.getSystemService(Context.ALARM_SERVICE);
To start service for devices with android version 12+

2023-04-13 19:33 UTC, Vignesh-772 approved these changes

2023-04-13 19:33 UTC, Vignesh-772 commented
Squash the commits

2023-04-17 16:17 UTC, witcher-shailesh approved these changes

2023-04-17 16:18 UTC, merged