Frontend/fix: #305 Changed loader_line file created Polling Variables
nammayatri/nammayatri pull request #306
Opened 2023-03-24 16:31 UTC by Jai-01

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
android-native -> changed progress_loader_line.json file.
ui-customer -> added variables in localStorage for polling
                           1. TEST_MINIMUM_POLLING_COUNT
                           2. TEST_POLLING_INTERVAL
                           3. TEST_POLLING_COUNT

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-03-24 17:19 UTC, Vignesh-772 requested changes

2023-03-24 17:19 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Flow.purs
> +  _ <- pure $ setValueToLocalStore TEST_MINIMUM_POLLING_COUNT "9"
move this to `baseAppFlow`

2023-03-24 17:19 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +        let usableCount = if gotQuote == "TRUE" && count > (fromMaybe 0 (fromString (getValueToLocalStore TEST_MINIMUM_POLLING_COUNT))) then (fromMaybe 0 (fromString (getValueToLocalStore TEST_MINIMU
store this `(fromMaybe 0 (fromString (getValueToLocalStore TEST_MINIMUM_POLLING_COUNT)))` in a variable and use

2023-03-25 06:08 UTC, witcher-shailesh approved these changes

2023-03-25 06:09 UTC, Vignesh-772 approved these changes

2023-03-25 06:10 UTC, merged