frontend/fix: #161 added auto assign user flow
nammayatri/nammayatri pull request #308
Opened 2023-03-24 16:49 UTC by soumyajit2304

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Added auto assign flow.
Removed confirm API call when the auto assigned is enabled

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-03-24 17:10 UTC, Vignesh-772 approved these changes

2023-03-24 20:19 UTC, ks-shree commented on Frontend/ui-customer/src/Services/API.purs
> +data SelectListBookingReq = SelectListBookingReq String
@soumyajit2304 No need to types and instances , You can handle in the existing API itself

2023-03-24 20:20 UTC, ks-shree reviewed
Can you modifiy `estimate/{estimateId}/quotes` endpoint itself

2023-03-25 04:11 UTC, ks-shree requested changes
Update existing endpoint instead of adding new endpoint

2023-03-25 06:23 UTC, ks-shree approved these changes

2023-03-25 07:54 UTC, witcher-shailesh approved these changes

2023-03-25 07:54 UTC, merged