frontend-feat #3093 location disabled popup added
nammayatri/nammayatri pull request #3121
Opened 2023-09-11 17:08 UTC by S-PRAVINKUMAR

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-09-21 05:21 UTC, Vignesh-772 requested changes

2023-09-21 05:21 UTC, Vignesh-772 commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.purs
> +foreign import getLocationPermissionStatus :: Unit -> String
try to use in Uncurried form

2023-09-21 05:21 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/PermissionScreen/View.purs
> +     ][ if state.stage == "INTERNET_ACTION" then ErrorModal.view (push <<< ErrorModalActionController) (errorModalConfig state)
try to append the view instead of if else

2023-10-03 09:09 UTC, Vignesh-772 approved these changes

2023-10-05 10:29 UTC, Vignesh-772 submitted a review, later dismissed

2023-10-05 14:40 UTC, ashishsingh101 approved these changes

2023-10-05 14:43 UTC, Vignesh-772 approved these changes

2023-10-05 14:44 UTC, merged