frontend/feat/#1303-searchlocmodel ui enhancement
nammayatri/nammayatri pull request #3123
Opened 2023-09-12 08:05 UTC by ashkriti

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
searchlocmodel ui enhancement

## Motivation and Context
https://github.com/nammayatri/nammayatri/issues/1303

## How did you test it?
Tested Manually

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-09-18 06:21 UTC, kavya-shree-s commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +                                    , crossbtnsrcvisibility: state.props.crossbtnsrcvisibility
Use camel case variables

2023-09-18 06:23 UTC, kavya-shree-s commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +  exit $ UpdatedState state { data { source = name, sourceAddress = encodeAddress name [] state.props.sourcePlaceId}, props { sourceLat = lat, sourceLong = lng, crossbtnsrcvisibility = if (STR.length
This can be handled in better way , as (STR.length name) > 2 is already returning Boolean not need of if condition

2023-09-18 06:23 UTC, kavya-shree-s commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +eval (UpdateSourceName lat lon name) state = continue state {data{source = name, sourceAddress = encodeAddress name [] state.props.sourcePlaceId}, props{crossbtnsrcvisibility = if (STR.length name) >
Handle as mentioned above

2023-09-18 06:23 UTC, kavya-shree-s commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +  exit $ UpdateSavedLocation state { props { isSource = Just true, currentStage = SearchLocationModel, isSearchLocation = SearchLocation, crossbtnsrcvisibility = if (STR.length srcValue) > 2 then tru
Handle as mentioned above

2023-09-20 07:50 UTC, kavya-shree-s commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +        -- pure $ setText (getNewIDWithTag "SourceEditText") "Current Location"
Remove if not required

2023-09-20 07:51 UTC, kavya-shree-s commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +  continue state { data { source = "", recentSearchs {predictionArray = predicArray}, prevLocation = state.data.source}, props { isSource = Just true, isSrcServiceable = true, isRideServiceable = tru
@ashkriti this comment is yet to be resolved?

2023-09-20 08:07 UTC, kavya-shree-s commented
@ashkriti Is it tested in IOS and accessibility testing ?

2023-09-29 04:28 UTC, Vignesh-772 requested changes

2023-09-29 04:28 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Components/SearchLocationModel/View.purs
> +    , cornerRadius 8.0
Update the configs don't hardcode

2023-09-29 04:28 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Components/SearchLocationModel/View.purs
> +                            , fontStyle $ FontStyle.semiBold LanguageStyle
this is not required

2023-09-29 04:28 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Helpers/Utils.purs
> +getDistanceString :: Int -> String
send decimal point also as input so that it will be generic.

2023-09-29 04:28 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/Types.purs
> +  , isAutoComplete :: Boolean
can you move all the props and data regarding searchlocation model to a separate type like searchLocationModelData, searchLocationModelProps.

2023-10-11 08:55 UTC, Vignesh-772 requested changes

2023-10-11 08:55 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Components/SearchLocationModel/View.purs
> +                    , width $ V 30
make it WRAP_CONTENT and add padding to it.

2023-10-11 08:55 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Components/SearchLocationModel/View.purs
> +                  , layoutGravity "center"
`CENTER` is not working?

2023-10-11 08:55 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Components/SearchLocationModel/View.purs
> +            $ if (state.isSource == Just true && state.isSearchLocation /= LocateOnMap) then btnData1 state else btnData2 state
change the name to something relevant

2023-10-11 08:55 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +  continue state{ data{source = "Current Location"} ,props{ sourceSelectedOnMap = if (state.props.isSource == Just true) then false else state.props.sourceSelectedOnMap, searchLocationModelProps{isAu
use getString

2023-10-12 08:08 UTC, Rohit4997 requested changes

2023-10-12 08:08 UTC, Rohit4997 commented on Frontend/ui-customer/src/Components/SearchLocationModel/View.purs
> +  , visibility if state.showLoader == true then VISIBLE else GONE
`state.showLoader == true` is `state.showLoader` only

2023-10-12 08:08 UTC, Rohit4997 commented on Frontend/ui-customer/src/Components/SearchLocationModel/View.purs
> +  , visibility if state.isAutoComplete == false then VISIBLE else GONE
use `not state.isAutoComplete`

2023-10-12 10:57 UTC, Rohit4997 approved these changes

2023-10-12 14:12 UTC, kavya-shree-s approved these changes

2023-10-12 14:17 UTC, Vignesh-772 approved these changes

2023-10-12 14:23 UTC, merged