frontend/feat/#2990 Moved PP to Native
nammayatri/nammayatri pull request #3130
Opened 2023-09-12 14:46 UTC by Vignesh-772

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-11-15 15:42 UTC, witcher-shailesh requested changes

2023-11-15 15:42 UTC, witcher-shailesh commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/MobilityAppBridge.java
Can you create a separate class which will have all the PP related functions and import in bridge to use it further. Also do we want to keep it in AppBridge as of now? can we move it to just Driver's module as customer app will not have any payment flow in near future. So good to have in just driver

2023-11-15 15:42 UTC, witcher-shailesh commented on Frontend/ui-driver/index.js
> +    case "initiate_result" : window.isPPInitiated = true; break;
good to have proper indentation for better readability

2023-11-15 15:42 UTC, witcher-shailesh commented on Frontend/ui-driver/src/Flow.purs
> +  liftFlowBT $ runEffectFn1 initiatePPSingleInstance unit
both initiatePP and initiatePPSingleInstance will be required to called everytime? If yes, then good to have a wrapper which call both together

2023-11-16 08:15 UTC, witcher-shailesh commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/MobilityAppBridge.java
Create a new class, please

2023-11-16 08:22 UTC, Vignesh-772 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/MobilityAppBridge.java
It is done.

2023-11-23 11:33 UTC, witcher-shailesh approved these changes

2023-11-23 11:33 UTC, witcher-shailesh commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/PaymentPage.java
> +package in.juspay.mobility.common;
Add copyright message

2023-11-23 11:37 UTC, merged