adding hasDisabilty field in rideBookingListResponse
nammayatri/nammayatri pull request #3213
Opened 2023-09-15 07:20 UTC by Shikhar-24

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-10-03 07:03 UTC, 0utkarsh requested changes

2023-10-03 07:03 UTC, 0utkarsh commented on Backend/dev/migrations/dynamic-offer-driver-app/1162-add-wasOfferedAssistance-column-in-rating-table.sql
> +ALTER TABLE atlas_driver_offer_bpp.rating ADD was_offered_assistance boolean NOT NULL;
It is maybe above and mandatory here

2023-10-05 13:13 UTC, Shikhar-24 commented on Backend/dev/migrations/dynamic-offer-driver-app/1162-add-wasOfferedAssistance-column-in-rating-table.sql
> +ALTER TABLE atlas_driver_offer_bpp.rating ADD was_offered_assistance boolean NOT NULL;
done

2023-10-19 22:42 UTC, khuzema786 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Beckn/ACL/Rating.hs
> +  let wasOfferedAssistance = req.message.feedback_form !! 1
Instead of this can we use `find` and handle gracefully

2023-11-01 01:04 UTC, khuzema786 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Beckn/Rating.hs
> +      issueId = req.feedbackDetails !! 2
You can use (!?) this operator if you want to access index safely.

2023-11-01 01:08 UTC, khuzema786 commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/UI/Support.hs
> +        nightSafety = isJust nightSafety && fromMaybe False nightSafety,
`nightSafety = fromMaybe False nightSafety`
This much should be fine.

2023-11-01 01:16 UTC, khuzema786 commented on Backend/lib/beckn-spec/src/Beckn/Types/Core/Taxi/Rating.hs
> +    feedback_form :: [FeedbackForm]
@Shikhar-24 Did you test by hitting BPP directly and sending `feedback_form` as an Object without Array ?

2023-11-01 01:19 UTC, khuzema786 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Beckn/ACL/Rating.hs
> +        feedbackDetails =
You can shorten this
```
[ feedback_form >>= Just (.answer)
, wasOfferedAssistance >>= Just (.answer)
, mbIssueId >>= Just (.answer)
]
```

2023-12-06 07:09 UTC, khuzema786 submitted a review, later dismissed

2023-12-08 07:30 UTC, NikithShetty submitted a review, later dismissed

2023-12-08 09:08 UTC, hkmangla submitted a review, later dismissed

2023-12-11 12:23 UTC, 0utkarsh approved these changes

2023-12-12 10:56 UTC, NikithShetty approved these changes

2023-12-12 11:06 UTC, merged