Backend/feat/subscription scheduler final
nammayatri/nammayatri pull request #3252
Opened 2023-09-18 09:42 UTC by hkmangla

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-09-18 11:01 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Beam/Notification.hs
> +notificationTMod :: NotificationT (B.FieldModification (B.TableField NotificationT))
Remove this.

2023-09-19 04:43 UTC, 0utkarsh requested changes

2023-09-19 04:43 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/Mandate/Execution.hs
> +    executionDate' <- addUTCTime transporterConfig.driverAutoPayExecutionTime <$> getCurrentTime
Should be `getCurrentTime` only

2023-09-19 04:43 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/Mandate/Notification.hs
> +getRescheduledTime :: MonadTime m => TransporterConfig -> m UTCTime
We can use the already created one too

2023-09-19 04:43 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/Mandate/Notification.hs
> +  let dfExecutionTime = transporterConfig.driverAutoPayExecutionTime
`notificationTime + executionTime`

2023-09-19 06:53 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/DriverFeeUpdates/DriverFee.hs
> +        due = fromIntegral driverFee.govtCharges + fromIntegral driverFee.platformFee.fee + driverFee.platformFee.cgst + driverFee.platformFee.sgst
Recheck this as it will be always 0.

2023-09-19 06:53 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/DriverFeeUpdates/DriverFee.hs
> +      offers <- Payment.offerList merchantId (makeOfferReq feeWithoutDiscount driver plan dutyDate registrationDateLocal) -- handle UDFs
Lets add try, catch here. In case of error, lets not process that driverFee here.

2023-09-19 06:53 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/DriverFeeUpdates/DriverFee.hs
> +        offerApplyRequest' = mkApplyOfferRequest offerTxnId offerApplied due driverPlan dutyDate mandateSetupDate
Replace `due` with `feeWithoutDiscount`

2023-09-19 06:53 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/DriverFeeUpdates/DriverFee.hs
> +        due = fromIntegral driverFee.govtCharges + fromIntegral driverFee.platformFee.fee + driverFee.platformFee.cgst + driverFee.platformFee.sgst
Not needed.

2023-09-19 06:53 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/DriverFeeUpdates/DriverFee.hs
> +          updateStatus PAYMENT_PENDING now firstFee.id
We need to update the amount too of first fees.

2023-09-19 06:53 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/DriverFeeUpdates/DriverFee.hs
> +    dueInvoices <- QDF.findAllPendingAndDueDriverFeeByDriverId (cast driverFee.driverId) -- Problem with lazy evaluation?
rename to dueDriverFees.

2023-09-19 06:53 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/DriverFeeUpdates/DriverFee.hs
> +          updRestFees <- mapM (buildRestFees PAYMENT_OVERDUE RECURRING_INVOICE) restFees
Make restFees as ONGOING so that these can be picked in next round of scheduler.

2023-09-19 06:53 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/DriverFeeUpdates/DriverFee.hs
> +      Nothing -> throwError $ InternalError "No batch gap defined for driver fee calculator job"
If not gap is defined, make it `5 seconds` by default.

2023-09-19 06:53 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/Mandate/Notification.hs
> +        mandateIdAndDriverIdsToNotify <- mandateIdAndDriverId <$> QDP.findAllByDriverIdsAndPaymentMode (DI.driverId <$> activeSubscribedDrivers) Plan.AUTOPAY
What about the drivers who notification is scheduled but autopay is not active? We should push them to Manual.

2023-09-19 06:53 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/Mandate/Notification.hs
> +            Left _ -> logError ("Notification failed for driverFeeId" <> driverToNotify.driverFeeId.getId)
In fail case, it should go to Manual.

2023-09-19 07:33 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/UI/Driver.hs
> +             :<|> "ny-payments"
remove `ny` from here and make it `v2/payments`

2023-09-19 07:33 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/UI/Driver.hs
> +               :> Get '[JSON] DDriver.NYHistoryEntity
`v2/payments/history/{{invoiceId}}/entity`

2023-09-19 07:33 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +  allEntiresByInvoiceId <- QINV.findAllByInvoiceId manualInvoice.id
typo.

2023-09-19 07:33 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +  manualPayInvoices <- mapMaybeM (`mkManualPaymentEntity` mapDriverFeeByDriverFeeId) invoices
Where are we splitting manual and autoPays?

2023-09-19 07:33 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +  case invoiceId of
It should not be Maybe.

2023-09-19 07:33 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +      transporterConfig <- CQTC.findByMerchantId merchantId_ >>= fromMaybeM (InternalError "configs do not exist for user")
proper error type.

2023-09-19 07:33 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +              planAmount = 0, --- refactor
Fix this.

2023-09-19 07:33 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/DriverFeeUpdates/DriverFee.hs
> +      invoice <- mkInvoiceAgainstDriverFee driverFee
change order first invoice then notification

2023-09-19 15:23 UTC, 0utkarsh requested changes

2023-09-19 15:23 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/DriverOnboarding.hs
> +  return $ max 0 (freeTrialDays - fromInteger (diffDays driverEnablementDay (utctDay now)))
diffDays's params should be flipped

2023-09-19 16:09 UTC, merged

2023-09-19 19:47 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/Mandate/Notification.hs
> +  ----- added measure duration for debugging -------
We needed to catch exceptions here also like driverFee scheduler. cc: @aayushagarwal2001