frontend/feat/installReferrerImplementation
nammayatri/nammayatri pull request #3255
Opened 2023-09-18 12:39 UTC by Anuragini-2506

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-09-21 13:32 UTC, ashishsingh101 requested changes

2023-09-21 13:32 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Flow.purs
> +  _ <- pure $ extractReferrerUrl unit
should be called only once when we install the APK for the first time

2023-09-21 13:32 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Flow.purs
> +  _ <- pure $ extractReferrerUrl unit
please handle this case to avoid unnecessary API call

2023-09-27 15:31 UTC, Vignesh-772 requested changes

2023-09-27 15:31 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Flow.purs
> +  void $ pure $ firebaseLogEvent $ getValueToLocalStore REFERRER_URL
it can be `__failed` as it is async. can you make a new thread and make callback to log event. or call the `firebaseLogEvent` in native itself.

2023-10-23 10:18 UTC, witcher-shailesh commented
Not required as of now

2023-11-13 09:50 UTC, closed without merging