backend/feat/recording-collected-at
nammayatri/nammayatri pull request #3260
Opened 2023-09-18 18:34 UTC by piyushKumar-1

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-09-18 18:56 UTC, NikithShetty approved these changes

2023-09-19 04:16 UTC, 0utkarsh requested changes

2023-09-19 04:16 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Queries/DriverFee.hs
> +    [Se.Set BeamDF.status status, Se.Set BeamDF.updatedAt now, Se.Set BeamDF.collectedBy collectorId, Se.Set BeamDF.collectedAt (Just now)]
This query is called even if the status is `EXEMEPTED`. Can you add a check to only update in case of `COLLECTED_CASH`?

2023-09-19 04:16 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Queries/DriverFee.hs
> +        BeamDF.collectedAt = collectedAt,
Migration is missing for this

2023-09-22 06:02 UTC, NikithShetty approved these changes

2023-09-22 06:03 UTC, merged