frontend/feat/translations
nammayatri/nammayatri pull request #3338
Opened 2023-09-22 14:07 UTC by yashikakaushik

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-10-04 08:24 UTC, witcher-shailesh requested changes

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/TranslatorMLKit.java
> +            Translator translator = downloadModel(destinationLanguage);
create a constructor and use that translator for single instance/use

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/TranslatorMLKit.java
> +                                public synchronized void onSuccess(String translatedText) {
remove synchronized

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/TranslatorMLKit.java
> +                                    Log.d("hello world", "now");
remove this log, or add proper log line

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/TranslatorMLKit.java
> +
remove extra spaces within code

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/TranslatorMLKit.java
> +
on failure case return the string as it is, without translating. Not required in case of translating and updating text view

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/TranslatorMLKit.java
> +    public static void translateStringNew(String destinationAddress, String destinationLanguage, String callback, BridgeComponents bridgeComponents){
rename the function name

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/TranslatorMLKit.java
> +                            public void onFailure(@NonNull Exception e) {
send the same string without translating in this case as well

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/android-native/mobility-driver/src/main/java/in/juspay/mobility/driver/MobilityDriverBridge.java
> +        String lang = getKeysInSharedPref("LANGUAGE_KEY");
create constructor here as well, and then use it to translate string

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +      return function (toTranslate){
rename this to `value`

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +// export const translateString = function(destinationAddress)
remove commented code

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.purs
> +-- foreign import translateString :: String -> String -> String -> String
remove commented code

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/ui-driver/src/Components/RideActionModal/View.purs
> +  -- JB.translateString(config.destinationAddress.titleText, languageKey, getNewIDWithTag "sourceArea")
remove commented code

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/ui-driver/src/Flow.purs
> +        let x = (decodeAddress ride.fromLocation true) --ride.fromLocation
remove extra brackets

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/ui-driver/src/Flow.purs
> +            activeRide = (activeRideDetail state (RidesInfo ride))
check the flow here, if translations are happening properly here

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/ui-driver/src/Helpers/Utils.purs
> +import Debug (spy)
remove this import

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/ui-driver/src/Screens/HomeScreen/ComponentConfig.purs
> +    -- languageKey <- (getValueToLocalStore LANGUAGE_KEY)
remove commented code

2023-10-04 08:24 UTC, witcher-shailesh commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +                do
remove do and commented code

2023-10-12 10:40 UTC, witcher-shailesh approved these changes

2023-10-12 11:03 UTC, Rohit4997 requested changes

2023-10-12 11:53 UTC, witcher-shailesh commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/OverlaySheetService.java
> +            String useMLKit = sharedPref.getString("USE_ML_TRANSLATE", null);
it's good to have a null check like this

2023-10-12 12:14 UTC, witcher-shailesh submitted a review, later dismissed

2023-10-12 12:31 UTC, witcher-shailesh approved these changes

2023-10-12 12:41 UTC, merged