backend/feat/translations
nammayatri/nammayatri pull request #3467
Opened 2023-10-03 12:30 UTC by yashikakaushik

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-10-06 13:50 UTC, 0utkarsh requested changes

2023-10-06 13:50 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/SendSearchRequestToDrivers/Handle/Internal/SendSearchRequestToDrivers.hs
> +      return dict
We can remove do from everywhere except line 206 or we can make it like this:

```
case language `elem` transporterConfig.languagesToBeTranslated of
  False -> return dict
  True -> case M.lookup language dict of
    Just _ -> return dict
    Nothing -> do
      translatedSearchReq <- translateSearchReq searchReq language
      pure $ M.insert language translatedSearchReq dict
```

2023-10-06 13:50 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/SendSearchRequestToDrivers/Handle/Internal/SendSearchRequestToDrivers.hs
> +    Esq.EsqDBReplicaFlow m r
Why extra constraint? In fact remove the existing `EsqDBFlow m r` too

2023-11-16 11:12 UTC, witcher-shailesh commented on Backend/dev/migrations/dynamic-offer-driver-app/0279-add-translated-lang.sql
> +UPDATE atlas_driver_offer_bpp.transporter_config SET languages_to_be_translated = '{"MALAYALAM"}';
NOTE: Please add all languages in this array before PROD release.

2023-11-21 10:47 UTC, hkmangla approved these changes

2023-11-21 10:48 UTC, merged