frontend/fix: lottie change according to variant issue for yatri driver
nammayatri/nammayatri pull request #3548
Opened 2023-10-09 11:00 UTC by ashkriti

## Type of Change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
lottie change according to variant issue for yatri driver

## Motivation and Context
Bugfix

## How did you test it?

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-10-09 14:11 UTC, MercyQueen requested changes

2023-10-09 14:11 UTC, MercyQueen commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/OverlaySheetService.java
> +                rawResource = R.raw.ride_accepted_lottie;
by default it would use ride_accepted_lottie which is an auto animation.Can you handle it for other variants also.

2023-10-09 14:33 UTC, MercyQueen approved these changes

2023-10-11 20:39 UTC, ashishsingh101 approved these changes

2023-10-11 20:39 UTC, merged