backend/fix : Add-time-based-charge-in-ride-fare
nammayatri/nammayatri pull request #3655
Opened 2023-10-14 00:30 UTC by vsaimanohar

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [X] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
 Add-time-based-charge-in-ride-fare

### Additional Changes

- [X] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [X] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [X] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-10-14 22:03 UTC, 0utkarsh requested changes

2023-10-14 22:03 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/FareCalculator.hs
> +          timeBasedChargeInfo = calculateTimeBasedFare . (Money . (\avgSpeedOfVechile -> params.distance.getMeters `div` avgSpeedOfVechile) <$> (.getKilometers)) =<< averageSpeedOfVehicle
Fare is not Re. 1 for each min, so you need to multiply it by the fare/min

2023-10-14 22:03 UTC, 0utkarsh commented on Backend/dev/migrations/dynamic-offer-driver-app/0263-payment-nudge.sql
> -CREATE TABLE IF NOT EXISTS atlas_driver_offer_bpp.merchant_push_notification
Why is this file removed?

2023-10-14 22:35 UTC, vsaimanohar commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/FareCalculator.hs
> +          timeBasedChargeInfo = calculateTimeBasedFare . (Money . (\avgSpeedOfVechile -> params.distance.getMeters `div` avgSpeedOfVechile) <$> (.getKilometers)) =<< averageSpeedOfVehicle
> Also need to throw proper error when `avgSpeedOfVechile` is zero

avgSpeedOfVechile wont be zero its a const fare_policy value we would set it > 0

2023-10-14 23:09 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/FareCalculator.hs
> +          timeBasedChargeInfo = calculateTimeBasedFare . (Money . (\avgSpeedOfVechile -> params.distance.getMeters `div` avgSpeedOfVechile) <$> (.getKilometers)) =<< averageSpeedOfVehicle
We need to handle. If somebody sets it to zero, compilation will pass and we will start getting exceptions. Positive validation should be done

2023-10-16 00:44 UTC, 0utkarsh requested changes

2023-10-16 00:44 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/FareCalculator.hs
> +  unless (isJust (fp.averageSpeedOfVehicle) && fromJust (fp.averageSpeedOfVehicle) > 0) $ throwError AverageVehicleSpeedLessThanZero
Partial functions should be avoided even though you have an isJust check. Better to use case match

2023-10-18 17:07 UTC, hkmangla requested changes

2023-10-18 17:07 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/FareCalculator.hs
> +  case fp.averageSpeedOfVehicle of
Remove it from here.

2023-10-18 17:07 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/FareCalculator.hs
> +      let distancePerKilometer = realToFrac @_ @Double distance.getMeters / 1000
Rename variables correctly.

2023-10-18 17:07 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/FareCalculator.hs
> +    calculateTimeBasedFare distance timeBasedCharge rideDuration avgSpeedOfVehicle = do
have a check of avgSpeedOfVehicle.

2023-10-18 17:07 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/FareCalculator.hs
> +      let timeBasedCharge' = realToFrac @_ @Double (fromMaybe 1 timeBasedCharge).getHighPrecMoney
Default value should be `0`

2023-10-18 17:07 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/FareCalculator.hs
> +      let timeBasedFareInMinutes :: Int = round $ (distancePerKilometer / avgSpeedOfVehicle') * 60
estimatedTimeTakeInMinutes.

2023-10-18 20:05 UTC, 0utkarsh requested changes

2023-10-18 20:05 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/FareCalculator.hs
> +      let estimatedTimeTakeInMinutes :: Int = round $ (distanceInKilometer / avgSpeedOfVehicle') * 60
`avgSpeedOfVehicle'` can be zero. We are not checking this?

2023-10-18 20:05 UTC, 0utkarsh commented on Backend/dev/migrations/dynamic-offer-driver-app/0265-add-averageVechileSpeed-to-transport-config.sql
> +SET avg_speed_of_vehicle = '{"seda": 30, "suv": 30, "hatchback": null,"auto_rickshaw": null, "taxi" : null, "taxi_plus" : null}'::json
sedan typo

2023-10-19 05:56 UTC, hkmangla approved these changes

2023-10-19 05:56 UTC, merged