frontend/feat/#2319 : Add Subscription flow in Yatri Saathi
nammayatri/nammayatri pull request #3738
Opened 2023-10-16 12:56 UTC by prakharritik

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-10-17 06:47 UTC, Rohit4997 requested changes

2023-10-17 06:47 UTC, Rohit4997 commented on Frontend/android-native/app/src/driver/jatriSaathiDriver/assets/juspay/v1-configuration.js
> +      "NAMMA_YATRI_PLANS" : "Yatri Sathi Plans",
Rename this Key, as now it's not specific to namma yatri

2023-10-17 06:47 UTC, Rohit4997 commented on Frontend/ui-driver/src/Flow.purs
> +      getDriverInfoApiResp <- lift $ lift $ Remote.getDriverInfoApi (GetDriverInfoReq{})
Why API call in this function ?

2023-10-17 06:47 UTC, Rohit4997 commented on Frontend/ui-driver/src/Flow.purs
> +            case getDriverInfoApiResp of
use `isRight` here

2023-10-17 06:47 UTC, Rohit4997 commented on Frontend/ui-driver/src/Flow.purs
> +        Left _ -> pure unit
use `isRight` in such cases

2023-10-17 06:47 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/HomeScreen/Controller.purs
> +      _ <- pure $ incrementValueOfLocalStoreKey TIMES_OPENED_NEW_SUBSCRIPTION
Better to use void

2023-10-17 06:47 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +      -- , if state.data.paymentState.makePaymentModal && (not $ DA.any (_ == state.props.currentStage) [RideAccepted, RideStarted, ChatWithCustomer, RideCompleted]) then makePaymentModal push state
Remove if not used

2023-10-17 06:47 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/PaymentHistoryScreen/View.purs
> +                    -- "OFFER" -> if item.val /= "" then promoCodeView push (fromMaybe dummyPromoConfig ((getPromoConfig [OfferEntity {title : Just item.val, description : Nothing, tnc : Nothing, id
Remove this line if not used

2023-10-17 06:47 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/SubscriptionScreen/ComponentConfig.purs
> +    config = PrimaryButton.config
directly use 
`PrimaryButton.config {

}
`

To override existing config

2023-10-17 06:47 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/SubscriptionScreen/Controller.purs
>  eval (OptionsMenuAction (OptionsMenu.ItemClick item)) state = do
if let is removed then no need of do here

2023-10-17 06:47 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/SubscriptionScreen/Controller.purs
>  eval (OptionsMenuAction (OptionsMenu.BackgroundClick)) state = do
remove do as well

2023-10-17 06:47 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/SubscriptionScreen/Transformer.purs
> +dummyIntroductoryConfig :: LazyCheck -> PlanCardConfig
Better  change this function name if it is not dummy

2023-10-17 06:47 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/SubscriptionScreen/View.purs
> +                                        "EN_US" -> state.data.config.myPlanYoutubeLink
directly pass `state.data.config.myPlanYoutubeLink` 

No need for case match now

2023-10-17 06:47 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/SubscriptionScreen/View.purs
> +                              "EN_US" -> state.data.config.myPlanYoutubeLink
directly pass `state.data.config.myPlanYoutubeLink`

No need for case match now

2023-10-17 06:47 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/SubscriptionScreen/View.purs
> +lottieJsonAccordingToLang isOnFreeTrial = do
Remove do

2023-10-19 19:57 UTC, Rohit4997 commented on Frontend/ui-driver/src/Components/BottomNavBar/Controller.purs
> +          activeIcon: if (getMerchant FunctionCall == NAMMAYATRI) then "ny_ic_rides_active," <> (getCommonAssetStoreLink FunctionCall) <> "ny_ic_rides_active.png" else "ny_ic_cab_active,https://asset
We can make this activeIcon also configurable, So that we don't need to check on merchant. @witcher-shailesh

2023-10-19 19:57 UTC, Rohit4997 commented on Frontend/ui-driver/src/Flow.purs
> +                  Right resp -> modifyScreenState $ GlobalPropsType $ \glopalProps -> glopalProps{driverInformation = resp}
`glopalProps` please check spelling

2023-10-19 19:57 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/SubscriptionScreen/Controller.purs
> +              pspLogo = Const.getPspIcon payerVpa <> "," <> (getAssetStoreLink FunctionCall) <> (Const.getPspIcon payerVpa) <> ".png"
We can store `Const.getPspIcon payerVpa`  in a var and make function call only once

2023-10-20 10:27 UTC, Rohit4997 submitted a review, later dismissed

2023-10-23 06:31 UTC, witcher-shailesh commented on Frontend/ui-driver/src/Flow.purs
> +                getDriverInfoApiResp <- lift $ lift $ Remote.getDriverInfoApi (GetDriverInfoReq{})
update the value of driverInfo response in cache as well in GlobalProps

2023-10-23 07:07 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Helpers/Utils.purs
> +      let _ = runFn2 setValueToLocalStore (show key) (show (val + 1))
can you make it effect uncurried?

2023-10-23 07:18 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Screens/ReferralScreen/Controller.purs
> +      void $ pure $ incrementValueOfLocalStoreKey TIMES_OPENED_NEW_SUBSCRIPTION
use `liftFlowBT` instead of `pure`

2023-10-23 07:22 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Screens/SubscriptionScreen/Transformer.purs
> +            gradient : if item.title == Just "Freedom Offer: 96% off APPLIED-*$*-ಫ್ರೀಡಮ್ ಆಫರ್: 96% ರಷ್ಟು ರಿಯಾಯಿತಿ" then ["#FFE7C2", "#FFFFFF", "#DDFFEB"] else (fromMaybe {id : "", colors : []} gradie
remove the hard coded strings and use variables

2023-10-23 07:27 UTC, kavya-shree-s commented on Frontend/ui-driver/src/Components/BottomNavBar/Controller.purs
> +      processedNavOptions = DA.filter (\item -> item.isVisible == true) navdata
No need to compare boolean
Can be written as DA.filter (\item -> item.isVisible) navdata

2023-10-25 09:52 UTC, Vignesh-772 approved these changes

2023-10-25 09:52 UTC, witcher-shailesh approved these changes

2023-10-25 09:53 UTC, merged