backend/refactor:#148 moved external integration to nammayatri
nammayatri/nammayatri pull request #376
Opened 2023-03-29 16:59 UTC by Dwibedi-10

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description
Moved external integration from shared kernel to nammayatri repo.

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-03-29 17:38 UTC, roman-bodavskiy commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Beckn/ACL/Select.hs
> +-- import qualified Lib.Maps as Maps
redundant comment

2023-03-29 17:41 UTC, roman-bodavskiy commented on Backend/app/provider-platform/static-offer-driver-app/Main/src/Tools/Maps.hs
> +-- import qualified Lib.Maps as Maps
redundant comment

2023-03-29 17:44 UTC, roman-bodavskiy commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Tools/Verification.hs
> +-- getTask,
redundant comments

2023-03-29 17:57 UTC, roman-bodavskiy commented on Backend/lib/external-services/src/Lib/Maps/Google/MapsClient.hs
> +  ( module GoogleMaps,
Maybe `Services.Maps.Google.MapsClient `? @DonDokidon @hkmangla

2023-03-30 06:51 UTC, pavelzarubin commented on Backend/lib/external-services/src/Lib/Maps/MMI/MapsClient/Types.hs
I think you can delete the MapsClient folder and move the Types module to the MMI folder, as there is nothing in MapsClient except the Types module.

2023-04-04 14:18 UTC, DonDokidon requested changes

2023-04-04 14:18 UTC, DonDokidon commented on Backend/app/dashboard/CommonAPIs/src/Dashboard/Common/Message.hs
> -import Kernel.External.Types (Language)
Do not change pathes, save original structure

2023-08-22 07:50 UTC, closed without merging