frontend/fix/#3737/Try-Again-screen-car-icon-issue-in-ny
nammayatri/nammayatri pull request #3782
Opened 2023-10-17 09:06 UTC by Anuragini-2506

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-10-17 19:17 UTC, aryan-13 requested changes

2023-10-17 19:17 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +                , selectedEstimatesObject = estimatesInfo.defaultQuote
This is not required

2023-10-18 06:59 UTC, aryan-13 approved these changes

2023-10-18 12:36 UTC, Vignesh-772 approved these changes

2023-10-18 12:36 UTC, merged