(WIP) frontend/fix: #378 fix image in ios for driverinfocard
nammayatri/nammayatri pull request #381
Opened 2023-03-30 13:05 UTC by kapilJhalani1

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?
Pending

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-02 07:55 UTC, Vignesh-772 requested changes

2023-04-02 07:55 UTC, Vignesh-772 commented on Frontend/ui-common/src/Components/SourceToDestination/View.purs
> +        [ if os == "IOS" then imageWithFallback "ny_ic_line,https://assets.juspay.in/nammayatri/images/common/ny_ic_line.png" else imageUrl "ic_line"
instead of using `if..else` try appending the props to the array using `<>`

2023-04-02 07:55 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Components/IndividualRideCard/View.purs
> +      [ if os == "IOS" then imageWithFallback "ny_ic_line,https://assets.juspay.in/nammayatri/images/common/ny_ic_line.png" else imageUrl "ic_line"
same here

2023-04-05 19:18 UTC, ashishsingh101 reviewed
is it done and working well for both android and ios ?

2023-04-06 06:14 UTC, kapilJhalani1 commented
> is it done and working well for both android and ios ? since we are using xml for android

No in android we are not changing anything and use the existing xml file only. In ios we are facing issues in my rides section as image size is fixed but the distance bw source and destination textview is changing so image doesn't align properly.

2023-04-13 13:48 UTC, closed without merging