frontend/feature: #382 generate session token
nammayatri/nammayatri pull request #383
Opened 2023-03-30 14:17 UTC by chakri642

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-02 07:59 UTC, Vignesh-772 commented
resolve conflicts

2023-04-02 08:03 UTC, Vignesh-772 requested changes

2023-04-02 08:03 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Helpers/Storage.purs
> +  | UNIQUE_ID
rename it to `SESSION_ID`

2023-04-02 08:03 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Flow.purs
> +      _ <- pure $ setValueToLocalStore UNIQUE_ID (generateUId unit)
I think we are doing the `/rideSearch` api in two places in Flow file update the `session_id` in all places

2023-04-02 08:03 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Helpers/Utils.js
> +exports["generateUId"] = function () {
rename the function name to meaning full name

2023-04-02 08:03 UTC, Vignesh-772 commented
I can be merged once the backend changes for this are done

2023-04-05 13:48 UTC, Vignesh-772 requested changes

2023-04-05 13:48 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Services/Backend.purs
> +import JBridge (setKeyInSharedPrefKeys,toast,factoryResetApp, toggleLoader, stopLocationPollingAPI, Locations, getVersionName, generateSessionId)
remove unused import

2023-04-05 13:51 UTC, Vignesh-772 approved these changes

2023-04-05 19:16 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Flow.purs
> +  if ((getValueToLocalStore SESSION_ID == "__failed") || (getValueToLocalStore SESSION_ID == "(null)")) then do
if you want you can do something like 
`when (condition) $ do
      setValueToLocalStore SESSION_ID (generateSessionId unit)`

2023-04-05 19:16 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +                _ <- pure $ setValueToLocalStore SESSION_ID (generateSessionId unit)
do we want same session id for a single ride ? if yes then can we call it where we are searching for ride

2023-04-06 04:38 UTC, chakri642 commented on Frontend/ui-customer/src/Flow.purs
> +  if ((getValueToLocalStore SESSION_ID == "__failed") || (getValueToLocalStore SESSION_ID == "(null)")) then do
It is for IOS checking whether the value is in local storage or not

2023-04-06 07:51 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Flow.purs
> +  if ((getValueToLocalStore SESSION_ID == "__failed") || (getValueToLocalStore SESSION_ID == "(null)")) then do
okay

2023-04-14 08:19 UTC, witcher-shailesh approved these changes

2023-04-14 08:20 UTC, merged