backend/fix: #372 added gender in profile apis
nammayatri/nammayatri pull request #391
Opened 2023-03-31 06:38 UTC by soumyajit2304

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Added Gender response in Profile API
Added Gender update in Profile API

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-03-31 06:43 UTC, 0utkarsh commented
Can you add migrations?

2023-03-31 06:43 UTC, soumyajit2304 commented
> Can you add migrations?

Gender column already exits in the person table

2023-03-31 06:48 UTC, 0utkarsh approved these changes

2023-03-31 09:11 UTC, roman-bodavskiy approved these changes

2023-03-31 09:12 UTC, roman-bodavskiy commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/UI/Profile.hs
> +      (req.gender)
redundant brackets

2023-04-04 10:12 UTC, piyushKumar-1 approved these changes

2023-04-06 15:59 UTC, DonDokidon requested changes

2023-04-06 15:59 UTC, DonDokidon commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Types/Person.hs
> +data Gender = MALE | FEMALE | OTHER | UNKNOWN | PREFERNOTTOSAY
use snake case

2023-04-07 04:12 UTC, soumyajit2304 commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Types/Person.hs
> +data Gender = MALE | FEMALE | OTHER | UNKNOWN | PREFERNOTTOSAY
Done

2023-04-07 08:53 UTC, hkmangla approved these changes

2023-04-07 08:54 UTC, merged