frontend-fix #3918 fixed rating card crop issue
nammayatri/nammayatri pull request #3919
Opened 2023-10-23 08:21 UTC by S-PRAVINKUMAR

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-10-23 09:03 UTC, aryan-13 requested changes

2023-10-23 09:03 UTC, aryan-13 commented on Frontend/ui-common/src/Components/RideCompletedCard/View.purs
> +    ] <> if os == "IOS" then [id "topViewId"] else [])
If else is not required here. We can give the Id for both android and IOS

2023-10-23 12:30 UTC, ashishsingh101 commented on Frontend/ui-common/src/Components/RideCompletedCard/View.purs
> +    ] <> if os == "IOS" then [id "topViewId"] else [])
its good to use id with `getNewIDWithTag`, to store stringify integer

2023-10-25 07:19 UTC, aryan-13 approved these changes

2023-10-26 14:20 UTC, ashishsingh101 approved these changes

2023-10-26 14:24 UTC, merged