Frontend/feat/#1840 driver onboarding revamp changes
nammayatri/nammayatri pull request #4058
Opened 2023-10-30 06:58 UTC by ashkriti

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-11-16 09:23 UTC, witcher-shailesh requested changes

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/android-native/mobility-driver/src/main/java/in/juspay/mobility/driver/MobilityDriverBridge.java
> +
Make a separate class for all functions related to Camera/ Capture and move these functions in that class. Later create instance of the class and use those functions

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-common/src/Components/PopUpModal/Controller.purs
> +    coverVideoConfig :: CoverVideoConfig--,
remove this commented comma

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-common/src/Components/PopUpModal/Controller.purs
> +    -- , onBoardingButtonVisibility : false
remove comments;

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-common/src/Components/StepsHeaderModal/Controller.purs
unify this header component with the generic one

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-common/src/Components/StepsHeaderModal/View.purs
> +view :: forall w . (Action -> Effect Unit) -> Config -> PrestoDOM (Effect Unit) w
split view file with proper sub functions for better readability

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +    console.log("checkAndAskNotificationPermission");
remove this log

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +    const stringifiedData = window.JBridge.getSessionInfo();
give proper names to the variables

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +    console.log("coming_inside: ");
remove these logs

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +        if (window.onResumeListeners) {
can we have this check even before defining callbacks?

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +  console.log("in_js_2");
remove logs

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +export const onFocused = function(callback){
where is this being used?

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +    return JBridge.renderCameraProfilePicture(id);
add function check if exists

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +export const checkAndAskNotificationPermission = function (shouldAlwaysAsk) {
what's the requirement of `shouldAlwaysAsk` if we already created another function to check for permission?

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-common/src/MerchantConfig/Utils/Utils.js
> +import * as teluguStrings from "./../../src/Strings/TE.js";
verify the term used for telugu at backend

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/Controller.purs
> +        NonDisclosureAgreementAction -> trackAppActionClick appId (getScreen ENTER_MOBILE_NUMBER_SCREEN) "in_screen" "no_discloure_agreement"
have small and meaningful names for actions in a generic way

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/Controller.purs
> +        NonDisclosureAgreementAction -> trackAppActionClick appId (getScreen ENTER_MOBILE_NUMBER_SCREEN) "in_screen" "no_discloure_agreement"
Where is this action being used?

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/View.purs
> + ][ textView (
can we take advantage of the commonTextView here?

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/View.purs
> +                  _ <- JB.openUrlInApp $ getValueFromConfig "DOCUMENT_LINK"
use `void $` instead of `_ <-`

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/View.purs
> +        , text (" T&Cs")--getString NON_DISCLOUSER_AGREEMENT)
Remove hard-coded values and make translations for these

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Strings/TE.js
> +/** JUST FOR COMPILATION */
@ashkriti please update this file as provided, if not available @tejkranthi can you help with this

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-driver/src/App.purs
> +import Screens.OnBoardingSubscriptionScreen.ScreenData as OnBoardingSubscriptionScreenData
please fix the duplicates

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-driver/src/Components/MenuButton/View.purs
> +                , visibility if state.text.subtitle == "" then GONE else VISIBLE
use `null` instead of `== ""`

2023-11-16 09:23 UTC, witcher-shailesh commented on Frontend/ui-driver/src/Components/ValidateDocumentModal/Controller.purs
> +    imageBase64 : "ny_ic_profile_image,https://assets.juspay.in/nammayatri/images/common/ny_ic_profile_image.png",
use generic function to construct image URL

2023-11-28 07:00 UTC, Rohit4997 requested changes

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Components/ValidateDocumentModal/View.purs
> +    , orientation VERTICAL]
RelativeLayout doesn't need Orientation

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Components/ValidateDocumentModal/View.purs
> +        , visibility if (state.profilePictureCapture == true) then VISIBLE else GONE
`state.profilePictureCapture == true)` is `state.profilePictureCapture` only

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Components/ValidateDocumentModal/View.purs
> +      , if (state.profilePictureCapture == false) then (profilePictureLayout state push) else textView[]
`not state.profilePictureCapture`

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/ChooseCityScreen/Controller.purs
> +            -- | MenuButtonAction2 MenuButtonController.Action
Remove commented code

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/ChooseCityScreen/Controller.purs
> +-- eval (MenuButtonAction2 (MenuButtonController.OnSelection btnState)) state = continue state { data { locationSelected = btnState.text.value }}
Remove commented code from this file

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/ChooseCityScreen/Handler.purs
> +module Screens.ChooseCityScreen.Handler where
Add Copyright

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/ChooseCityScreen/ScreenData.purs
> +module Screens.ChooseCityScreen.ScreenData where
add Copyright

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/ChooseCityScreen/View.purs
> +              -- , linearLayout
Remove commented code from this whole file

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/ChooseCityScreen/View.purs
> +  , margin $ Margin 16 16 16 16
This line will not work because it's already written above, Remove one line

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/ChooseCityScreen/View.purs
> +
Remove extra space

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/ChooseCityScreen/View.purs
> +        --  , imageWithFallback $ "ny_driver_location_permission," <> (HU.getAssetStoreLink FunctionCall) <> "ny_driver_location_permission.png"
Remove this line

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/EnterMobileNumberScreen/ComponentConfig.purs
> +          -- , fontStyle = FontStyle.bold LanguageStyle
Remove commented lines

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/EnterMobileNumberScreen/ComponentConfig.purs
> +          --color = if state.props.mNumberEdtFocused then Color.black800 else Color.grey900
Remove

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/EnterMobileNumberScreen/View.purs
> +        -- _ <- requestKeyboardShow (getNewIDWithTag "EnterMobileNumberEditText")
Remove This is not used

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/EnterMobileNumberScreen/View.purs
> +      -- , textView (
Remove commented code from everywhere in this file

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/EnterOTPScreen/View.purs
> +
Remove extra space

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/EnterOTPScreen/View.purs
> +          ]
Add fontstyle, And use MarginHorizontal

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/EnterOTPScreen/View.purs
> +          ]
Add fontstyle, And use MarginHorizontal

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/EnterOTPScreen/View.purs
> +-- underlinedTextView :: ST.EnterOTPScreenState -> (Action -> Effect Unit) -> forall w . PrestoDOM (Effect Unit) w
Remove commented code in this file from everywhere

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/PermissionsScreen/ComponentConfig.purs
> +      , margin = Margin 15 0 15 30
`MarginHorizontal`

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/PermissionsScreen/Controller.purs
> +--   _ <- pure $ spy "location permission" isNotificationPermissionEnabled
Remove spy statement

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/PermissionsScreen/Controller.purs
> +  let _ = spy "Permission Request" isBatteryOptimizationEnabled
Remove logs

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/PermissionsScreen/View.purs
> +            Notifications -> "ny_ic_permission_notification"
Add proper indentation

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/RegistrationScreen/Controller.purs
> +  _ <- case merchant of
Do not use merchant check, Make it config

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/RegistrationScreen/View.purs
> +          , orientation VERTICAL
Not required

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/RegistrationScreen/View.purs
> +          , afterRender
simply use `, afterRender push $ const AfterRender`

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/RegistrationScreen/View.purs
> +                -- , visibility if state.props.logoutModalView then GONE else VISIBLE
One `linearLayout` can be reduced here, also remove commented code

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/RegistrationScreen/View.purs
> +                    , linearLayout
Better split the view in different different functions, instead for writing it in one function

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/RegistrationScreen/View.purs
> +                    -- , registrationHeader state
Remove commented code

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/RegistrationScreen/View.purs
> -    ] <> FontStyle.body5 TypoGraphy
Why fontStyle is removed here, Please always prefer to apend fontstyle

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/RegistrationScreen/View.purs
> +-- lottieLoaderView :: forall w. ST.RegistrationScreenState -> (Action -> Effect Unit)-> PrestoDOM (Effect Unit) w
Remove commented code

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/ScreenNames.purs
> +                | WELCOME_SCREEN
Add chooseCity Screen also

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/UploadDrivingLicenseScreen/ComponentConfig.purs
> +        , margin = Margin 16 0 16 0
`MarginHorizontal`

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/UploadDrivingLicenseScreen/ComponentConfig.purs
> +      , padding = Padding 15 10 15 10
`MarginHorizontal`

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/UploadDrivingLicenseScreen/Controller.purs
> +                      _ <- liftEffect $ uploadFile false
Better to use void

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/UploadDrivingLicenseScreen/Controller.purs
> +     _ <- liftEffect $ uploadFile false
Better use void

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/UploadDrivingLicenseScreen/View.purs
> +              if (initialState.props.validateProfilePicturePopUp == true)  then  lift $ lift $ doAff do liftEffect $ push $ AfterRender  else pure unit
`initialState.props.validateProfilePicturePopUp == true` is `initialState.props.validateProfilePicturePopUp` only

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/UploadDrivingLicenseScreen/View.purs
> +      , visibility $ if (DS.toLower(state.data.driver_license_number) /= DS.toLower(state.data.reEnterDriverLicenseNumber) && state.data.reEnterDriverLicenseNumber /= "") then VISIBLE else GONE
use `not null` instead of `/=`

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/UploadDrivingLicenseScreen/View.purs
> +                             else if state.data.errorMessage /= "" then ST.Failure
better use `not null` instead of `/=`

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/WelcomeScreen/View.purs
> +        , accessibility DISABLE
Do we need this line?

2023-11-28 07:00 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/WelcomeScreen/View.purs
> +    , accessibility DISABLE
This can be removed I guess

2023-11-28 13:32 UTC, witcher-shailesh commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/ResourceHandler.java
Can we add copyright text here @Vignesh-772

2023-11-28 13:32 UTC, witcher-shailesh commented on Frontend/android-native/app/src/main/res/drawable/ny_ic_splash_bg_trans.png
reduce image size

2023-11-28 13:32 UTC, witcher-shailesh commented on Frontend/android-native/app/src/user/nammaYatri/res/drawable/ic_auto_rickshaw_black_yellow.png
reduce image size

2023-11-28 13:32 UTC, witcher-shailesh commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/Utils.java
> +            case "TE_IN" :
This is done

2023-11-28 13:32 UTC, witcher-shailesh commented on Frontend/ui-driver/src/App.purs
> +import Screens.DriverSavedLocationScreen.ScreenData as DriverSavedLocationScreenData
@ashkriti can you fix the duplicate imports?

2023-11-29 06:52 UTC, merged