backend/feat: send dummy notification to driver via dashboard
nammayatri/nammayatri pull request #4161
Opened 2023-11-06 13:43 UTC by jaypalmudaliyar24

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-11-07 07:00 UTC, 0utkarsh commented
Can you mention why this feature is needed?

2023-11-07 07:22 UTC, jaypalmudaliyar24 commented
> Can you mention why this feature is needed?
It was needed to test FCM channel via dashboard.

2023-11-07 08:56 UTC, jaypalmudaliyar24 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Dashboard/Driver.hs
> +  _ <- TN.notifyOnNewSearchRequestAvailable merchantOperatingCity.id driver.id deviceToken entityData
Fixed.

2023-11-07 08:56 UTC, jaypalmudaliyar24 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Dashboard/Driver.hs
> +      searchRequestValidTill = addUTCTime thirtySeconds now
Fixed.

2023-11-07 08:56 UTC, jaypalmudaliyar24 commented on Backend/dev/migrations/provider-dashboard/0028-make-server-array-merchant.sql
> +SET server_names = ARRAY[server_name, 'DRIVER_OFFER_BPP_MANAGEMENT'];
Addee new migrations.

2023-11-21 11:13 UTC, hkmangla requested changes

2023-11-21 11:21 UTC, jaypalmudaliyar24 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Dashboard/Driver.hs
> +sendDummyNotificationToDriver :: ShortId DM.Merchant -> Context.City -> Id Common.Driver -> Flow APISuccess
Should i create a new module `Domain.Action.Dashboard.Driver.Notification` and move this function there?

2023-11-24 14:38 UTC, hkmangla approved these changes

2023-11-24 14:38 UTC, merged