frontend/#4273/feat added pickUp far from current location pop up
nammayatri/nammayatri pull request #4274
Opened 2023-11-09 21:09 UTC by MercyQueen

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

2023-11-13 07:03 UTC, ashishsingh101 requested changes

2023-11-13 07:03 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Flow.purs
> +                    else if response.distance < 500 && (getValueToLocalStore LOCAL_STAGE) /= "ShortDistance" && getValueToLocalStore LOCAL_STAGE /= "PickUpFarFromCurrentLocation" then do
if you want we can simplify this approach using inner hierarchical conditions or cases

2023-11-13 09:30 UTC, MercyQueen commented on Frontend/ui-customer/src/Flow.purs
> +            else if response.distance < 500 && getValueToLocalStore LOCAL_STAGE /= "ShortDistance" && getValueToLocalStore LOCAL_STAGE /= "PickUpFarFromCurrentLocation" then do
It can be replaced with `all`.

2023-11-14 04:18 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Flow.purs
> +            else if ( (response.distance < 500  || isDistMoreThanThreshold )&& Arr.all (_ /= getValueToLocalStore LOCAL_STAGE ) ["PickUpFarFromCurrentLocation", "ShortDistance"]) then do
try to use isLocalStageOn function to check currentStage. Instead of comparing hard coded string.

2023-11-14 04:20 UTC, Vignesh-772 requested changes
Resolve comments

2023-11-14 07:51 UTC, Vignesh-772 submitted a review, later dismissed

2023-11-16 08:10 UTC, witcher-shailesh commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +                _ <- pure $ removeMarker (getCurrentLocationMarker (getValueToLocalStore VERSION_NAME))
replace this also with `void $` and try to correct the same in other functions

2023-11-16 08:12 UTC, ashishsingh101 submitted a review, later dismissed

2023-11-16 08:22 UTC, witcher-shailesh approved these changes

2023-11-16 08:23 UTC, ashishsingh101 approved these changes

2023-11-16 08:26 UTC, merged