frontend/fix:#430 invoice pdf fix
nammayatri/nammayatri pull request #431
Opened 2023-04-05 07:29 UTC by dakshana-jayakumar

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Displaying the references lists in the invoice PDF from purescript instead of native side

2023-04-05 08:05 UTC, Vignesh-772 requested changes

2023-04-05 08:05 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/CustomerUtils/MyRidesScreen/Controller.purs
> +  , referenceString : ("1.5" <> (getString DAYTIME_CHARGES_APPLICABLE_AT_NIGHT)) <> "\n\n" <>
what about translations. In pdf we will show only English

2023-04-05 08:05 UTC, Vignesh-772 commented on Frontend/android-native/app/src/main/res/layout/invoice_template.xml
> +            android:id="@+id/referenceText"
I can't see any changes for removing fare break up if it is zero

2023-04-05 08:05 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/CustomerUtils/MyRidesScreen/Controller.purs
> +                        (getString DRIVERS_CAN_CHARGE_AN_ADDITIONAL_FARE_UPTO) <> "\n\n" <>
We should send the also reference if we don't have driver offered fares no need of showing this line. same for waiting charges

2023-04-06 07:46 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/CustomerUtils/MyRidesScreen/Controller.purs
> +  , referenceString : ("1.5" <> (getString DAYTIME_CHARGES_APPLICABLE_AT_NIGHT)) <> "\n\n" <>
Recheck this comment

2023-04-06 07:54 UTC, Vignesh-772 requested changes

2023-04-06 07:54 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/CustomerUtils/MyRidesScreen/Controller.purs
> +isHaveFare :: FareTypes -> Array FareComponent -> Boolean
move this to utils as this is defined in two screens

2023-04-06 07:54 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/Types.purs
> +, referenceString :: String
why is this required here . it is not used anywhere and we are going to deprecate this `Fares` type so add it separate

2023-04-06 07:54 UTC, Vignesh-772 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/CommonJsInterface.java
> +        if(fares.getString("nominalFare").equals("₹ 0.0")){
changing visibility is not a solution we may get more break ups from backend change this accordingly. and use `fareList` instead `fareBreakUpList`

2023-04-13 13:56 UTC, Vignesh-772 requested changes

2023-04-13 13:56 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/CustomerUtils/MyRidesScreen/Controller.purs
> +  , referenceString : "1.5" <> "x of daytime charges applicable at night from 10 PM to 5 AM"
don't hard code the string. Use data constructors itself

2023-04-13 13:56 UTC, Vignesh-772 commented on Frontend/android-native/app/src/main/res/layout/invoice_template.xml
> +                    android:id="@+id/relative_layout"
give proper id

2023-04-13 13:56 UTC, Vignesh-772 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/CommonJsInterface.java
> +                textViewText.setPadding(0, 0, 0, 7);
we are not defining text style?

2023-04-13 13:56 UTC, Vignesh-772 commented on Frontend/android-native/app/src/main/res/layout/invoice_template.xml
> +                    android:layout_width="match_parent"
it is not used in code

2023-04-13 17:30 UTC, Vignesh-772 commented
Validate the design with Figma and get the design review done from aman

2023-04-13 17:41 UTC, Vignesh-772 commented
squash the commits

2023-04-14 13:09 UTC, AmanMauryaXeno commented
The designs are good to go. The logic fix for the fare text update is pending on in-app invoice & invoice PDF

2023-04-14 13:34 UTC, Vignesh-772 requested changes

2023-04-14 13:34 UTC, Vignesh-772 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/CommonJsInterface.java
> +                if (key.equals("waitingCharges") || key.equals("nominalFare")) {
why this is required

2023-04-14 13:34 UTC, Vignesh-772 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/CommonJsInterface.java
> +                String key = fare.getString("fareType");
here also

2023-04-14 13:34 UTC, Vignesh-772 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/CommonJsInterface.java
> +            case ("DRIVER_SELECTED_FARE"):
why this is not having any return statement

2023-04-14 13:34 UTC, Vignesh-772 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/CommonJsInterface.java
> +                result = "Total Paid";
instead of storing in String directly you can return the string

2023-04-14 13:34 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/CustomerUtils/MyRidesScreen/Controller.purs
> +  "BASE_FARE" -> "BASE_FARE"
why this function is required and what is the use of this function

2023-04-14 13:34 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/CustomerUtils/MyRidesScreen/Controller.purs
>  getFareFromArray fareBreakUp fareType = (fromMaybe dummyFareBreakUp (head (filter (\fare -> fare^._description == (show fareType)) fareBreakUp)))^._amount
here fareType is already string why again show?

2023-04-20 15:47 UTC, Vignesh-772 approved these changes

2023-04-20 16:29 UTC, merged