Backend/spec-migration-phase-1/search on_search tags
nammayatri/nammayatri pull request #4315
Opened 2023-11-15 03:39 UTC by shreyaxh

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [x] ONDC Spec Migration

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-11-24 14:01 UTC, NikithShetty requested changes

2023-12-18 08:10 UTC, NikithShetty requested changes

2023-12-18 08:10 UTC, NikithShetty commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/Beckn/Init.hs
> +        case req of
this switch is supposed to happen based on flag and not the request type

2023-12-18 08:10 UTC, NikithShetty commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/Beckn/Search.hs
> +        case req of
same here, make switch case based on flag and not on request type everywhere else

2023-12-18 10:45 UTC, shreyaxh commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/UI/Confirm.hs
> -  logTagInfo ("BookingId-" <> getId booking.id) ("Cancellation reason " <> show DBCR.ByApplication)
Must have been removed accidentally, added it back

2023-12-18 10:46 UTC, shreyaxh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/Beckn/Confirm.hs
> +  case A.eitherDecodeStrict reqBS of
Done for all APIs

2024-06-27 09:39 UTC, closed without merging