frontend/fix/4xx-driver-arrived-at-pickup-api
nammayatri/nammayatri pull request #4421
Opened 2023-11-23 07:35 UTC by Anuragini-2506

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-11-23 07:42 UTC, aryan-13 requested changes

2023-11-23 07:42 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/HomeScreen/Controller.purs
> +      hello = spy "Hello world.. today was a bad day" (show driverLat <> " " <> show driverLong)
Remove logs

2023-11-23 07:45 UTC, Rohit4997 requested changes

2023-11-23 07:45 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/HomeScreen/Controller.purs
> +        let dist = (getDistanceBwCordinates (driverLat) (driverLong)  snapped.lat snapped.lon)
Remove extra brackets

2023-11-23 07:45 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/HomeScreen/Controller.purs
> +              let dist = getDistanceBwCordinates (lat) (lng) loc.lat loc.lon
Remove extra brackets

2023-11-23 07:50 UTC, Anuragini-2506 commented on Frontend/ui-driver/src/Screens/HomeScreen/Controller.purs
> +        let dist = (getDistanceBwCordinates (driverLat) (driverLong)  snapped.lat snapped.lon)
done

2023-11-23 07:50 UTC, Anuragini-2506 commented on Frontend/ui-driver/src/Screens/HomeScreen/Controller.purs
> +              let dist = getDistanceBwCordinates (lat) (lng) loc.lat loc.lon
done

2023-11-24 14:13 UTC, witcher-shailesh requested changes

2023-11-24 14:13 UTC, witcher-shailesh commented on Frontend/ui-driver/src/Screens/HomeScreen/Controller.purs
> +import Debug (spy)
remove redundant imports

2023-11-27 08:50 UTC, witcher-shailesh approved these changes

2023-11-27 08:50 UTC, merged