frontend/fix: #446 resolved bugs for customer and driver
nammayatri/nammayatri pull request #448
Opened 2023-04-06 07:28 UTC by ashkriti

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Resolved the bugs :
1. In driver and customer Empty Rides error msg should display in the chosen language (BUG_48)
2. When customer is on ride then book ride in my rides empty section should be removed (BUG_54)
3. User should not get Keypad after giving the grant access while login into the app (BUG_64)
4. When Driver trying to login for first time after app is installed, on permission screen driver should not get keypad (BUG_66)

## Motivation and Context
https://github.com/nammayatri/nammayatri/issues/446

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-13 17:14 UTC, Vignesh-772 requested changes

2023-04-13 17:14 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Flow.purs
> +  _ <- pure $ hideKeyboardOnNavigation true
did you check this change in search location model if you do like this keyboard will close for every input

2023-04-13 17:15 UTC, Vignesh-772 commented
get it tested

2023-04-14 06:00 UTC, witcher-shailesh requested changes

2023-04-14 07:01 UTC, ashkriti commented on Frontend/ui-customer/src/Screens/CustomerUtils/MyRidesScreen/ComponentConfig.purs
> +      , visibility = if (isLocalStageOn ST.HomeScreen) then VISIBLE else GONE
Earlier the book now button was visible in the MyRidesScreen when the ride was ongoing for the first time and was not completed or cancelled. So when the local stage is home screen then only it should be visible.

2023-04-14 07:01 UTC, ashkriti commented on Frontend/ui-customer/src/Screens/CustomerUtils/MyRidesScreen/ComponentConfig.purs
> +import Storage (isLocalStageOn)
Sure

2023-04-14 08:51 UTC, Vignesh-772 approved these changes

2023-04-19 11:52 UTC, witcher-shailesh approved these changes

2023-04-19 11:52 UTC, merged