frontend/fix: #446 resolved bugs in iOS
nammayatri/nammayatri pull request #457
Opened 2023-04-07 04:25 UTC by Jai-01

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
1. [iOS] While entering feedback in final fare screen keypad is hiding the text box and submit button (BUG_63)
    * added scrollview for rating ride component
2. [iOS] In my rides screen Repeat Ride button is highlighted when user is already in on-going ride (BUG_57)
    * added alpha in individual ride card

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-13 17:16 UTC, Vignesh-772 commented
add screenshot for second bug

2023-04-13 17:18 UTC, Vignesh-772 requested changes

2023-04-14 05:54 UTC, Jai-01 commented on Frontend/ui-customer/src/Components/RatingCard/View.purs
> +            , height if os == "IOS" && state.props.enableFeedback then (V 400) else WRAP_CONTENT
if i use adjustViewWithKeyboard, ratingcard view is not fitting into the display. so that i used scrollview.

2023-04-14 06:08 UTC, witcher-shailesh approved these changes

2023-04-14 06:09 UTC, merged