frontend/fix/#1840: added optional image upload for DL and RC
nammayatri/nammayatri pull request #4623
Opened 2023-12-06 10:32 UTC by ashkriti

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description
added optional image upload for DL and RC (for Chennai)

## Motivation and Context
#1840 

## How did you test it?
Tested Manually

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2023-12-06 10:49 UTC, Rohit4997 requested changes

2023-12-06 10:49 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/AddVehicleDetailsScreen/ComponentConfig.purs
> +      , margin = if (state.props.openHowToUploadManual&& (not state.data.cityConfig.uploadRCandDL)) then Margin 15 0 15 10 else Margin 15 0 15 30
use above `imageUploadCondition` variable 
`imageUploadCondition = state.props.openHowToUploadManual && not state.data.cityConfig.uploadRCandDL`

And remove `--getValueFromConfig "imageUploadOptional" || state.props.isValidState` commented code
It was added for this condition only

2023-12-06 10:49 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/AddVehicleDetailsScreen/View.purs
> +           , if (state.props.openHowToUploadManual && (not state.data.cityConfig.uploadRCandDL)) then skipButton push state else linearLayout[][]]
Remove unnecessary brackets

2023-12-06 10:49 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/UploadDrivingLicenseScreen/ComponentConfig.purs
> +      , margin = if (state.props.openHowToUploadManual && (not state.data.cityConfig.uploadRCandDL)) then Margin 15 0 15 10 else Margin 15 0 15 30
put `state.props.openHowToUploadManual && not state.data.cityConfig.uploadRCandDL` in a variable and remove brackets then use the variable

2023-12-06 11:34 UTC, Rohit4997 approved these changes

2023-12-08 10:50 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/AddVehicleDetailsScreen/View.purs
> +  , textSize FontSize.a_16
Remove This line

2023-12-14 10:22 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Screens/UploadDrivingLicenseScreen/View.purs
> +          , if state.props.openHowToUploadManual && not state.data.cityConfig.uploadRCandDL then skipButton push state else linearLayout[][]]
append the view instead of empty linear layout

2023-12-14 11:50 UTC, Rohit4997 approved these changes

2023-12-15 05:06 UTC, merged