[WIP] backend/refactor: Dynamic Fare Policy & Flow Type & Special Zone Tag
nammayatri/nammayatri pull request #474
Opened 2023-04-07 23:38 UTC by khuzema786

## Type of Change

- [] Bugfix
- [x] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-08 12:46 UTC, roman-bodavskiy commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Beckn/ACL/OnConfirm.hs
> +buildOnConfirmMessage :: (MonadFlow m, EsqDBFlow m r) => UTCTime -> DConfirm.DConfirmRes -> m OnConfirm.OnConfirmMessage
`MonadFlow m` is already included in `EsqDBFlow m r`

2023-04-24 17:20 UTC, DonDokidon requested changes

2023-04-24 17:20 UTC, DonDokidon commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Types/FareParameters.hs
> +    fareProductId :: Id DFP.FareProduct,
Why is this required?

2023-04-24 17:20 UTC, DonDokidon commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Types/FareProduct.hs
> +  deriving (Generic, Show, FromJSON, ToJSON)
Don't make  FromJSON, ToJSON instances for domain types

2023-04-24 17:20 UTC, DonDokidon commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Types/SpecialZoneCategoryPriority.hs
> +  deriving (Generic, Show, FromJSON, ToJSON)
Same

2023-04-24 17:20 UTC, DonDokidon commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Types/FareProduct.hs
> +data FareProduct = FareProduct
Could you describe why we need this table?

2023-04-24 17:20 UTC, DonDokidon commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Types/FareProduct.hs
> +data FlowType = NORMAL_RIDE_FLOW | RIDE_OTP_FLOW deriving (Generic, Eq, Show, Read, FromJSON, ToJSON)
What is this naming? Don't we have OTP in all rides? What is considered "Normal" here then?

2023-05-24 08:35 UTC, khuzema786 commented
Outdated, raised a new PR https://github.com/nammayatri/nammayatri/pull/978

2023-05-24 08:35 UTC, closed without merging