frontend/feat: Estimates screen unification and revamp
nammayatri/nammayatri pull request #4849
Opened 2023-12-21 06:57 UTC by aryan-13

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Estimates screen unification and revamp
FIGMA -> https://www.figma.com/file/4zT4QhImxqphGf56DpAjcV/Beckn-Release-Version?type=design&node-id=94705-19366&mode=design&t=ikazFVLwZLcg5HMp-4

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-01-05 08:59 UTC, MercyQueen commented on Frontend/ui-customer/src/Resources/Constants.purs
>            Just ST.TAXI -> getString ECONOMICAL <> " · " <>  "4 " <> getString PEOPLE
@aryan-13 make sure the design changes works with Yatri Sathi as well.

2024-01-05 08:59 UTC, MercyQueen commented on Frontend/ui-customer/src/Resources/Constants.purs
> +  -- _ ->    ""
remove commented code

2024-01-05 08:59 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +    , vehicleVariant = state.data.selectedEstimatesObject.vehicleVariant
put `state.data.selectedEstimatesObject` inside a variable and use that in place of `state.data.selectedEstimatesObject`

2024-01-05 08:59 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +eval (ChooseYourRideAction (ChooseYourRideController.OnIconClick autoAssign)) state = do
remove do

2024-01-05 08:59 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +  continue state{props{flowWithoutOffers = (show autoAssign) == "true"}}
use `toBool` function from MobilityPrelude

2024-01-05 08:59 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Transformer.purs
> +      , showInfo = (getMerchant FunctionCall) /= YATRISATHI
create a variable in config for this.

2024-01-08 09:25 UTC, Vignesh-772 requested changes

2024-01-08 09:25 UTC, Vignesh-772 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +primaryButtonRequestRideConfig :: HomeScreenState -> PrimaryButton.Config
move it to ComponentConfig

2024-01-09 14:21 UTC, kavya-shree-s submitted a review, later dismissed

2024-01-09 18:10 UTC, kavya-shree-s approved these changes

2024-01-09 18:20 UTC, merged