frontend/feature/#482-creating-a-completionOverlayScreen
nammayatri/nammayatri pull request #485
Opened 2023-04-10 10:00 UTC by saireddy2610

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
creating a completionOverlayScreen when the user registered for the very first time

2023-04-13 18:27 UTC, Vignesh-772 requested changes

2023-04-13 18:27 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Screens/UploadDrivingLicenseScreen/Controller.purs
> +  _ <- launchAff_ $ flowRunner $ runExceptT $ runBackT $ do
make `state.props.isNewUser` false once the overlay is removed

2023-04-13 18:28 UTC, Vignesh-772 commented
squash the commits

2023-07-12 08:20 UTC, witcher-shailesh commented
Will re-open if further required in future

2023-07-12 08:20 UTC, closed without merging