backend/feat : added verification message for dl and rc
nammayatri/nammayatri pull request #4902
Opened 2023-12-29 11:40 UTC by AshishSaini25

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

added verification message for dl and rc

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-01-02 13:50 UTC, piyushKumar-1 submitted a review, later dismissed

2024-01-04 06:13 UTC, hkmangla requested changes

2024-01-04 06:13 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/DriverOnboarding/DriverLicense.hs
> +      let rules = listToMaybe driverLicense.failedRules
Just add one more check if `driverLicense` is `INVALID` then throw error contact support. You driver license class of vehicles are not supported. If it is `VALID` then don't do anything and say `DLAlreadyUpdated`

2024-01-04 06:13 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/DriverOnboarding/DriverLicense.hs
> +  let failedRules = case output.status of
No need to put anything in failedRules.

2024-01-04 06:13 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/DriverOnboarding/Status.hs
> -      Just driverLicense -> return $ mapStatus driverLicense.verificationStatus
If DL or RC is there then throw invalid vehicle class error.

2024-01-04 06:13 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/DriverOnboarding/Status.hs
> +
In `verificationStatus` function, at `Just req` case, add one another case match on `req.status`. If req.status contains `id_not_found` id not found error message and similarly for source_down etc.

2024-01-05 11:52 UTC, hkmangla submitted a review, later dismissed

2024-01-05 12:17 UTC, khuzema786 approved these changes

2024-01-05 12:18 UTC, merged