backend/fix/jenkins/ nixified load test
nammayatri/nammayatri pull request #4928
Opened 2024-01-03 15:13 UTC by soumyajit2304

## Type of Change

- [X] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-01-09 05:09 UTC, srid requested changes
Gave offline feedback to @soumyajit2304 about refactoring this. 

(Will pair when in office, if necessary)

2024-01-09 12:37 UTC, soumyajit2304 commented
Update the PR with the required changes.

2024-01-09 14:13 UTC, srid reviewed
@soumyajit2304 Could you update `backend/README.md` with exact instructions to follow for running the load test in devShell, so that I can test your PR locally (to make sure that it is reproducible)?

2024-01-10 05:41 UTC, soumyajit2304 commented
I have updated the load-test Readme `Backend/load-test/README.md`.

2024-01-10 06:52 UTC, srid commented on Backend/load-test/README.md
> + , run-load-test-nix
Is this correct?

`, run-load-test-nix` just runs `nix run` which fails for me:

I can run the load-test on my machine:

<img width="635" alt="image" src="https://github.com/nammayatri/nammayatri/assets/3998/204a162b-77b5-4422-8bbd-2244f1370e4d">

2024-01-10 10:08 UTC, srid commented
@soumyajit2304 Now I'm seeing this - one process in the load-test group crashed:

<img width="1066" alt="image" src="https://github.com/nammayatri/nammayatri/assets/3998/99379c0f-51d1-49ea-a061-b471141add48">

2024-01-10 10:22 UTC, srid commented
Alright, that worked after I deleted the output folder. But now I get this. However this is not Nix's fault, so I don't think we should block this PR.

<img width="1066" alt="image" src="https://github.com/nammayatri/nammayatri/assets/3998/17007906-1021-4c55-a7d8-f85403f8e062">

2024-01-10 10:23 UTC, soumyajit2304 commented
> Alright, that worked after I deleted the output folder. But now I get this. However this is not Nix's fault, so I don't think we should block this PR.
> 
> <img alt="image" width="1066" src="https://private-user-images.githubusercontent.com/3998/295532421-17007906-1021-4c55-a7d8-f85403f8e062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODI0MzIsIm5iZiI6MTcwNDg4MjEzMiwicGF0aCI6Ii8zOTk4LzI5NTUzMjQyMS0xNzAwNzkwNi0xMDIxLTRjNTUtYTdkOC1mODU0MDNmOGUwNjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMTAyMjEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWQ5ZDM2OTExNmJhZTQ1MDRhNTg5MGY0ZDJmM2M1NDMzYjU3OTVmN2U4NjlkZWU3MDAyMTA5OGQxMjIwNDExZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9rOL0RKIOynJ6LWx6wKGwq3ue5AJeYFNw_jC9KZwhfY">

Yes this is fine and expected as entry are already made in the table. 
So next process will run once this goes to completed which are dependent on this

2024-01-10 10:39 UTC, srid commented
For reference, we are using derivations from:

- https://github.com/NixOS/nixpkgs/pull/185087 
- https://github.com/NixOS/nixpkgs/pull/199746 

Neither of these PRs were merged and they have been sitting there for a while.

2024-01-10 11:55 UTC, srid approved these changes

2024-01-10 12:03 UTC, merged