Frontend/fix: Moving due limits to RemoteConfigs
nammayatri/nammayatri pull request #4929
Opened 2024-01-03 15:40 UTC by Rohit4997

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Moving due limits to RemoteConfigs

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-01-05 08:38 UTC, Vignesh-772 requested changes

2024-01-05 08:38 UTC, Vignesh-772 commented on Frontend/ui-common/src/RemoteConfig/Utils/Utils.js
> +  }
return `""` if function is not there.

2024-01-05 08:38 UTC, Vignesh-772 commented on Frontend/ui-driver/src/RemoteConfigs/RemoteConfig.js
> +  const parsedConfig = JSON.parse(config);
add try catch for parsing.

2024-01-05 08:38 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Screens/HomeScreen/ScreenData.purs
> +        subsRemoteConfig : RC.defSubsRemoteConfig,
call this `subscriptionConfig` function instead of default Config,

2024-01-05 08:38 UTC, Vignesh-772 commented on Frontend/ui-driver/src/App.purs
> +  subsRemoteConfig : RC.defSubsRemoteConfig
here also.

2024-01-08 07:41 UTC, Vignesh-772 submitted a review, later dismissed

2024-01-11 09:48 UTC, witcher-shailesh approved these changes

2024-01-11 09:48 UTC, merged