frontend/fix: Driver Info Card UI Fixes
nammayatri/nammayatri pull request #4930
Opened 2024-01-03 19:50 UTC by PraveenGongada

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Driver info card UI fixes

2024-01-04 05:13 UTC, Vignesh-772 requested changes

2024-01-04 05:13 UTC, Vignesh-772 commented on Frontend/android-native/mobility-customer/src/main/user/mobility_pm/res/drawable/ny_ic_wallet_filled.png
remove all the three images.

2024-01-05 01:18 UTC, kavya-shree-s commented on Frontend/ui-customer/src/Resources/Localizable/EN.purs
> +        BOARD_THE_FIRST -> "Board the first taxi from"
Why taxi is hardcoded

2024-01-05 01:22 UTC, kavya-shree-s commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +       , if (not (os == "IOS" || state.props.enableChatWidget)) && ((any (_ == state.props.currentStage)) [ RideAccepted, ChatWithDriver]) then
Add a comment mentioning its a temp fix

2024-01-05 01:22 UTC, kavya-shree-s commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +        [ height $ V $ ((getInfoCardPeekHeight state) - if isWidgetVisible then 140 else 0)
Remove extra brackets

2024-01-05 07:56 UTC, kavya-shree-s approved these changes

2024-01-05 07:56 UTC, merged