Backend/fix/upwards recomptute
nammayatri/nammayatri pull request #497
Opened 2023-04-10 17:22 UTC by piyushKumar-1

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-10 17:38 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Beckn/ACL/Init.hs
> +  searchRequest <- Esq.runInReplica $ SR.findById res.searchRequestId
remove this.

2023-04-11 14:07 UTC, NikithShetty requested changes

2023-04-11 14:07 UTC, NikithShetty commented on Backend/dev/migrations/rider-app/1103-added-max-estimated-distance-in-search-request.sql
> +ALTER TABLE atlas_driver_offer_bpp.search_request ADD COLUMN max_distance double precision;
change to `atlas_app`

2023-04-11 14:21 UTC, NikithShetty approved these changes

2023-04-12 11:24 UTC, merged