frontend/feat/Rentals: #4998 RideScheduledScreen Added
nammayatri/nammayatri pull request #5008
Opened 2024-01-11 06:57 UTC by slow-codex

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-01-11 07:15 UTC, aryan-13 requested changes

2024-01-11 07:15 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RideScheduledScreen/View.purs
> +      [ linearLayout
Can we put this view in a view function as well

2024-01-11 07:15 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RideScheduledScreen/ScreenData.purs
> +  , source : "Juspay Technologies, Stallion Business Center, 444, 18th Main Rd, 6th Block, Koramangala, Bengaluru, Karnataka 560095"
Put empty strings in init data

2024-01-11 07:15 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RideScheduledScreen/View.purs
> +        , text $ "Driver will be assigned " <> state.driverAllocationTime <> " minutes before starting the ride"
Add translations

2024-01-16 07:10 UTC, witcher-shailesh approved these changes

2024-01-16 08:23 UTC, merged