frontend/feat/rentals: #4998 RentalScreen Added
nammayatri/nammayatri pull request #5058
Opened 2024-01-16 12:01 UTC by slow-codex

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-01-17 12:47 UTC, aryan-13 requested changes
Please attach output for both IOS and Android

2024-01-17 12:47 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/View.purs
> +        , text case description of
Can we move this case match to where clause and the get the String for both the text views

2024-01-17 12:47 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/Controller.purs
> +  let updatedDuration = if(state.data.rentalBookingData.baseDuration < state.props.maxDuration) then state.data.rentalBookingData.baseDuration + 1 else state.data.rentalBookingData.baseDuration
`(state.data.rentalBookingData.baseDuration < state.props.maxDuration) ` Put this in a variable and then use it wherever required

2024-01-17 12:47 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/Controller.purs
> +  let updatedDuration = if(state.data.rentalBookingData.baseDuration > state.props.minDuration) then state.data.rentalBookingData.baseDuration - 1 else state.data.rentalBookingData.baseDuration
Same here as well. Update it wherever required in this file

2024-01-17 12:47 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/ComponentConfig.purs
> +    , padding = Padding 0 5 0 0
use `PaddingTop`

2024-01-17 12:47 UTC, aryan-13 commented on Frontend/ui-customer/src/Components/IncrementDecrementModel/View.purs
> +    [ if (config.showHorizontal) then horizontalIncrementDecrement push config
Remove brackets

2024-01-17 13:33 UTC, MercyQueen requested changes

2024-01-17 13:33 UTC, MercyQueen commented on Frontend/ui-customer/src/Components/IncrementDecrementModel/Controller.purs
> +  , heading: "Select Duration"
@slow-codex remove dummy data from config.

2024-01-17 13:33 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/View.purs
> +      , weight 0.0
remove weight.

2024-01-17 13:33 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/View.purs
> +      , alignParentBottom "true, -1"
remove this property if not required.

2024-01-17 13:33 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/View.purs
> +emptyTextView = linearLayout [ width $ V 0, height $ V 0, visibility GONE ] []
rename to dummyView

2024-01-17 13:33 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/View.purs
> +            BookingDistance -> getString EXCESS_DISTANCE_CHARGE_DESCRIPTION <> " ₹18/km."
make the fare / km configurable.

2024-01-17 13:33 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/View.purs
> +            BaseFare -> (getString BASE_FARE) <> "₹150"
remove hardcoded strings

2024-01-17 13:33 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/View.purs
> +                if (item.index == item.activeIndex) then ChooseVehicle.view (\action -> pure unit) (item) else emptyTextView
remove extra parenthesis

2024-01-17 13:33 UTC, MercyQueen commented on Frontend/ui-customer/src/Components/IncrementDecrementModel/View.purs
> +    , width $ V 180
make this component more configurable.

2024-01-17 13:33 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/Controller.purs
> +  let _ = spy "DatePIcker Action" ""
remove logs

2024-01-19 08:11 UTC, MercyQueen commented on Frontend/ui-customer/src/Components/InputView/View.purs
> +    ( mapWithIndex
put the whole layout inside a function instead of just the imageView (prefixImageView)

2024-01-19 08:11 UTC, MercyQueen commented on Frontend/ui-customer/src/Components/InputView/View.purs
> +textViews push config =
rename this

2024-01-19 08:11 UTC, MercyQueen commented on Frontend/ui-customer/src/Components/InputView/View.purs
> +          , background "#303440"
use this colour as an import

2024-01-19 08:13 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/ComponentConfig.purs
> +          , visibility = if isSelectPackageStage then VISIBLE else GONE
use boolToVisibility

2024-01-24 12:23 UTC, aryan-13 requested changes

2024-01-24 12:23 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/RideHistoryScreen/View.purs
> +    , visibility if state.props.showDateTimePicker then VISIBLE else GONE
use `BoolToVisibility` here

2024-01-24 12:23 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/DriverEarningsScreen/View.purs
> +                                  void $ runEffectFn3 renderSlider push SliderCallback sliderConfig{ id= (getNewIDWithTag "ConvertCoinsSliderView"), sliderConversionRate= state.data.coinConversionRat
Please call `runEffectFn3` on `renderSliderImpl`

2024-01-24 12:23 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/View.purs
> +    , weight 0.0
Can we remove this if not required

2024-01-24 12:23 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/View.purs
> +        , (textView $ [
Remove extra brackets

2024-01-24 12:23 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/View.purs
> +        BookingTime -> if toShowTitle then getString BOOKING_ON <> state.data.rentalBookingData.selectedDate <> ", " <> state.data.rentalBookingData.selectedTime <> " (" <> (show state.data.rentalBoo
(show state.data.rentalBookingData.baseDuration) put this in a variable and use it as it is being called more than once

2024-01-24 12:23 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/View.purs
> +          [ text "12 hr"
Why is this hardcoded?

2024-01-24 12:23 UTC, aryan-13 commented on Frontend/ui-customer/src/Components/InputView/View.purs
> +emptyTextView :: forall w. PrestoDOM (Effect Unit) w
Can we create a common file in Utils for the commonly used view functions as these are being used everywhere

2024-08-12 06:57 UTC, closed without merging