Backend/fix/push-notification-language-specific-in-translations-table
nammayatri/nammayatri pull request #5088
Opened 2024-01-17 20:16 UTC by DwivediAman-exe

## Type of Change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-01-17 20:33 UTC, pius-1 requested changes

2024-01-17 20:33 UTC, pius-1 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Lib/DriverCoins/Coins.hs
> +    case driver.language of
make common function for this.

2024-01-17 20:33 UTC, pius-1 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Lib/DriverCoins/Coins.hs
> +                    _ -> ("", "")
don't have empty strings as default.

2024-01-17 20:33 UTC, pius-1 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Lib/DriverCoins/Types.hs
> +  | Other
do you have Other use-case ?

2024-01-18 10:54 UTC, VD321 approved these changes

2024-01-18 12:41 UTC, piyushKumar-1 approved these changes

2024-01-18 12:41 UTC, merged