Backend/feat: #87 adding drivers currently on ride in search pool
nammayatri/nammayatri pull request #524
Opened 2023-04-12 12:16 UTC by 2019UCP1350

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [x] This PR modifies the database schema (database migration added)
- [x] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## How did you test it?
using postman

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-13 07:20 UTC, hkmangla requested changes

2023-04-13 07:20 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Tabular/Merchant/DriverPoolConfig.hs
> +      driverToDestinationDuration Seconds
is it also threshold?

2023-04-13 07:20 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Queries/Person.hs
> +        &&. whenJust_ mbVariant (\var -> vehicleInfo ^. VehicleVariant ==. val var)
change this logic according to downgrade option added recently

2023-04-13 10:47 UTC, umangj-28 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/SendSearchRequestToDrivers/Handle/Internal/DriverPool.hs
> +      if transporter.includeDriverCurreltOnRide && (radiusStep - 1) > 0
typo `includeDriverCurreltOnRide`

2023-04-14 10:45 UTC, roman-bodavskiy commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Types/Merchant/DriverPoolConfig.hs
>    }
can you leave `createdAt` and `updatedAt` as last fields, for better readability?

2023-04-18 07:08 UTC, hkmangla requested changes

2023-04-18 07:22 UTC, umangj-28 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/DriverPool.hs
> +chanegeIntoDriverPoolResult DriverPoolResultCurrentlyOnRide {..} = DriverPoolResult {..}
typo `chanege`

2023-04-18 09:35 UTC, umangj-28 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/DriverPool.hs
> +    chanegeIntoDriverPoolResult,
please resolve typos `chanege`

2023-04-18 09:41 UTC, hkmangla approved these changes

2023-04-18 09:41 UTC, merged