[BKN-2300] Multiple exotel numbers
nammayatri/nammayatri pull request #53
Opened 2023-03-01 18:46 UTC by DonDokidon

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description

Attach random exotel number to booking

### Additional Changes

- [x] This PR modifies the database schema (database migration added)
- [x] This PR modifies dhall configs/environment variables
- [x] This PR contains API breaking changes

https://github.com/nammayatri/shared-kernel/pull/8

## Motivation and Context

https://juspay.atlassian.net/browse/BKN-2300

## How did you test it?

manually, no tests after rebase

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-03-06 08:08 UTC, pavelzarubin approved these changes

2023-03-06 16:04 UTC, roman-bodavskiy commented on Backend/app/dashboard/CommonAPIs/src/Dashboard/RiderPlatform/Merchant.hs
> +      -- validateField "exoPhones" exoPhones $ InMaybe P.mobileNumber,
removed validation

2023-03-10 16:54 UTC, hkmangla requested changes

2023-03-10 19:42 UTC, DonDokidon commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/UI/Call.hs
> +           :> MandatoryQueryParam "CallStatus" ExotelCallStatus
No? i just checked it with next rest-client call and it was working just fine

```
# @name test
GET {{driver-offer-bpp-host}}/ui/exotel/call/statusCallback?CallSid="asd"&DialCallStatus=queued&RecordingUrl="https://github.com/nammayatri/shared-kernel/pull/8/files"
token: {{token1}}
content-type: application/json

###
```

2023-03-14 10:52 UTC, hkmangla requested changes

2023-03-14 10:52 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Beckn/Init.hs
> +      exoPhone <- getRandomElement merchant.exoPhones
As of till now we were not having multiple exophones for the users, so in exophones we were saving exophone with its backup exophone in the array. Now, you have to change that. exophones should be array of object (primary: number, backup: number)

2023-03-14 10:52 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Beckn/Init.hs
> +            providerExoPhone = exoPhone,
here, send the primary exophone.

2023-03-14 12:30 UTC, roman-bodavskiy commented on Backend/app/rider-platform/rider-app/Main/src/Storage/Queries/Merchant.hs
> +findByExoPhone exoPhone = do
Is this exophone unique? Because if two merchants will have the same exoPhone, this query will throw an error

2023-03-14 19:48 UTC, hkmangla requested changes

2023-03-14 20:32 UTC, hkmangla approved these changes

2023-03-14 20:32 UTC, merged