Backend/fix: #5375 Added supportedVehicles in transporter config
nammayatri/nammayatri pull request #5376
Opened 2024-02-07 06:35 UTC by Rohit4997

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Use-Case : We have a use-case where for a specific city we need to allow specific vehicleVariants
ChangeLog : Added supportedVehicles in transporter config. and isVehicleSupported in driverInfoAPI

### Additional Changes

- [x] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-02-07 07:50 UTC, hkmangla requested changes

2024-02-07 14:13 UTC, Rohit4997 commented on Backend/dev/migrations/dynamic-offer-driver-app/0351-add-supported-vehicle-config.sql
> +alter table atlas_driver_offer_bpp.transporter_config add column supported_vehicles text[] default ARRAY['AUTO_RICKSHAW']; -- need to run update query
Done

2024-02-08 07:46 UTC, roman-bodavskiy approved these changes

2024-03-11 06:34 UTC, Rohit4997 commented
Not required any more so closing it

2024-03-11 06:34 UTC, closed without merging