registry changes for whitelisting logic
nammayatri/nammayatri pull request #5410
Opened 2024-02-08 15:28 UTC by chakri642

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-02-09 11:33 UTC, NikithShetty requested changes

2024-02-09 11:33 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Types/BlackListOrg.hs
>    = PROVIDER
`PROVIDER` is `BPP`

2024-02-09 11:33 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Types/WhiteListOrg.hs
>    = PROVIDER
`PROVIDER` is `BPP`

2024-02-09 11:58 UTC, roman-bodavskiy commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Types/BlackListOrg.hs
> +$(mkBeamInstancesForEnum ''Domain)
these instances can be derived in Kernel and so we avoid orphans

2024-02-13 08:36 UTC, NikithShetty submitted a review, later dismissed

2024-02-13 09:32 UTC, NikithShetty approved these changes

2024-02-13 09:41 UTC, merged