onCancel integration
nammayatri/nammayatri pull request #5455
Opened 2024-02-11 05:52 UTC by chakri642

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-02-12 07:40 UTC, NikithShetty requested changes

2024-02-12 07:40 UTC, NikithShetty commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Beckn/ACL/OnCancel.hs
> +              Spec.ConfirmReqMessage
can these be broken down into separate functions to make it more readable?
You can follow the approach taken [here](https://github.com/nammayatri/nammayatri/blob/main/Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Beckn/ACL/OnConfirm.hs#L192-L409)

2024-02-12 07:40 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/API/Beckn/OnCancel.hs
> +        Redis.whenWithLockRedis (onCancelProcessngLockKey messageId) 60 $
`Processng` typo

2024-02-12 07:40 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/API/Beckn/OnCancel.hs
> +      mbDOnSelectReq <- ACL.buildOnCancelReqV2 req
check the variable name `onSelectReq`

2024-02-12 07:40 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/Beckn/OnCancel.hs
> +  triggerBookingCancelledEvent BookingEventData {booking = booking{status = SRB.CANCELLED}}
should be removed from cancel API, else we'll send this notification twice

2024-02-12 07:40 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/Beckn/OnCancel.hs
> +  -- cancellationSource merchantId =
Remove unused comments

2024-02-15 16:11 UTC, RitikaHanish commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/Beckn/Cancel.hs
> +      if cancelReq.cancelStatus == Just "confirmCancel"
Use ENum status here.

2024-02-15 16:46 UTC, RitikaHanish commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/Beckn/Cancel.hs
> +              buildOnCancelMessageV2 <- ACL.buildOnCancelMessageV2 merchant (Just city) (Just country) "CANCELLED" (OU.BookingCancelledBuildReqV2 onCancelBuildReq)
Use Enums

2024-02-15 16:46 UTC, RitikaHanish commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/Beckn/Cancel.hs
> +        else do
case match for confirm cancel and for soft cancel, else error.

2024-02-15 16:46 UTC, RitikaHanish commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Beckn/ACL/OnCancel.hs
> +buildOnCancelReqV2 action domain messageId bppSubscriberId bppUri city country cancelStatus = \case
Remove case match

2024-02-15 16:46 UTC, RitikaHanish commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Beckn/ACL/OnCancel.hs
> +  OU.BookingCancelledBuildReqV2 OU.DBookingCancelledReqV2 {..} -> do
Make name proper

2024-02-16 13:11 UTC, NikithShetty approved these changes

2024-02-16 13:38 UTC, merged