frontend/fix: #214 added firebase event for first ride in customer
nammayatri/nammayatri pull request #546
Opened 2023-04-13 14:25 UTC by ashkriti

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Added firebase event for first ride in customer and removed the events from the notifications for customer.

## Motivation and Context
https://github.com/nammayatri/nammayatri/issues/522

## How did you test it?
Tested manually

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-13 18:06 UTC, Vignesh-772 requested changes

2023-04-13 18:06 UTC, Vignesh-772 commented on Frontend/android-native/app/src/main/java/in/juspay/mobility/utils/NotificationUtils.java
>              if (TRIP_CHANNEL_ID.equals(notificationType) ) {
squash the commits

2023-04-14 03:52 UTC, ks-shree commented on Frontend/ui-customer/src/Flow.purs
> +                                      (GetProfileRes response) <- Remote.getProfileBT ""
@ashkriti Why getProfile api needs to be called after every trip completion, Can you add check on api call ?

2023-04-14 03:52 UTC, ks-shree submitted a review, later dismissed
Check comments

2023-04-18 07:40 UTC, witcher-shailesh approved these changes

2023-04-18 07:40 UTC, merged