backend/fix: #40 added ride date in dashboard ride list api
nammayatri/nammayatri pull request #55
Opened 2023-03-02 07:15 UTC by Dwibedi-10

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
added ride date in dashboard ride list api

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?
 tested locally through postman.

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-03-02 14:25 UTC, roman-bodavskiy commented on Backend/app/dashboard/CommonAPIs/src/Dashboard/ProviderPlatform/Ride.hs
> +    date :: UTCTime
can we use more specific field name?

2023-03-04 13:14 UTC, hkmangla requested changes

2023-03-04 13:14 UTC, hkmangla commented on Backend/app/dashboard/CommonAPIs/src/Dashboard/ProviderPlatform/Ride.hs
> +    date :: UTCTime
Yeah. Rename field to rideCreatedAt.

2023-03-07 07:25 UTC, hkmangla approved these changes

2023-03-07 07:25 UTC, merged