Frontend/fix: #551 change BottomNavBar in Driver
nammayatri/nammayatri pull request #552
Opened 2023-04-14 05:51 UTC by Jai-01

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

1. Replaced Bottom Nav Bar Icons
2. removed navData from ScreenData file from HomeScreen, DriverProfileScreen, RideHistoryScreen
3. Removed screenName variable from BottomNavBarState

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-14 06:35 UTC, witcher-shailesh requested changes

2023-04-14 06:35 UTC, witcher-shailesh commented on Frontend/ui-driver/src/Components/BottomNavBar/Controller.purs
> +      activeIcon: "ny_ic_rides_active,https://assets.juspay.in/nammayatri/images/driver/ny_ic_rides_active.png",
Can you update all the new assets to AssetStore and mention the PR in this PR's description??

2023-04-18 06:00 UTC, witcher-shailesh commented
Can you resolve conflicts?

2023-04-18 06:28 UTC, Jai-01 commented
> Can you resolve conflicts?

@witcher-shailesh resolved conflicts

2023-04-20 09:24 UTC, witcher-shailesh approved these changes

2023-04-20 09:24 UTC, merged