backend/enhancement/move-tables-to-dsl
nammayatri/nammayatri pull request #5537
Opened 2024-02-15 10:33 UTC by vsaimanohar

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [X] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
move-tables-to-dsl

### Additional Changes

- [X] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [X] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [X] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-02-17 08:05 UTC, hkmangla requested changes

2024-02-17 08:05 UTC, hkmangla commented on Backend/dev/migrations-read-only/dynamic-offer-driver-app/cancellation_reason.sql
> +CREATE TABLE atlas_driver_offer_bpp.cancellation_reason ();
Please delete existing migrations for this in `migrations` folder.

2024-02-28 22:09 UTC, khuzema786 commented on Frontend/ui-customer/src/Flow.purs
Discard this change

2024-02-29 07:50 UTC, vsaimanohar commented on Frontend/ui-customer/src/Flow.purs
done

2024-03-04 13:43 UTC, hkmangla approved these changes

2024-03-04 14:00 UTC, hkmangla approved these changes

2024-03-04 14:08 UTC, hkmangla approved these changes

2024-03-04 14:08 UTC, merged