frontend/feat/rentals: #4998 HomeScreen Rental Banner, NightFare static data and RentalScreen Changes
nammayatri/nammayatri pull request #5542
Opened 2024-02-15 13:24 UTC by slow-codex

## Type of Change

- [x] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

- Added the new homescreen banner
- Added the explainer in the rental package selection screen
- RentalScreen RateCard changes

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-02-15 13:36 UTC, MercyQueen commented on Frontend/ui-common/src/Components/Banner/View.purs
> +            , textFromHtml $ if isJust config.actionTextBackgroundColor then "&darr;" else "&rarr;"
make this also configurable.

2024-02-15 13:37 UTC, aryan-13 requested changes

2024-02-15 13:37 UTC, aryan-13 commented on Frontend/ui-common/src/Components/Banner/Controller.purs
> +  actionTextBackgroundColor :: Maybe String,
Can we put image and actionText related items in their corresponding combined configs

2024-02-15 13:37 UTC, aryan-13 commented on Frontend/android-native/app/src/user/jatriSaathi/res/drawable/ny_ic_rental_banner.png
Can we compress this image

2024-02-15 13:37 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RentalBookingFlow/RentalScreen/View.purs
> +      , textFromHtml $ "<span>Every hour gets you <b>10 kms</b> in the package.<br>You can plan additional KMs upto a limit and save on extra costs if you end up exceeding the base distance.<br>You c
Add translation for this text

2024-02-16 12:53 UTC, MercyQueen approved these changes

2024-02-16 12:53 UTC, merged