backend/fix: added merchantOpCityId to stations list api
nammayatri/nammayatri pull request #5566
Opened 2024-02-16 15:38 UTC by VD321

## Type of Change

- [X] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-02-20 10:45 UTC, RitikaHanish requested changes

2024-02-20 10:45 UTC, RitikaHanish commented on Backend/app/rider-platform/rider-app/Main/spec/Storage/frfs-ticket.yaml
> +    getTicketPlacesByVehicleTypeAndMOCityId:
revert this change

2024-02-20 10:45 UTC, RitikaHanish commented on Backend/app/rider-platform/rider-app/Main/src-read-only/Storage/Queries/Station.hs
> +getTicketPlacesByVehicleTypeAndMOCityId :: (MonadFlow m, CacheFlow m r, EsqDBFlow m r) => Domain.Types.Station.FRFSVehicleType -> Kernel.Types.Id.Id Domain.Types.MerchantOperatingCity.MerchantOperati
revert

2024-02-20 10:50 UTC, RitikaHanish requested changes
Handle sending correct city in every beckn FRFS context.

2024-03-12 10:11 UTC, RitikaHanish commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/Beckn/FRFS/OnConfirm.hs
> +getMerchantOperatingCityFromBooking :: DFRFSTicketBooking.FRFSTicketBooking -> Environment.Flow DMOC.MerchantOperatingCity
Move this to Utils

2024-03-13 16:01 UTC, VD321 commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/Beckn/FRFS/OnConfirm.hs
> +getMerchantOperatingCityFromBooking :: DFRFSTicketBooking.FRFSTicketBooking -> Environment.Flow DMOC.MerchantOperatingCity
Done

2024-03-15 08:36 UTC, RitikaHanish approved these changes

2024-03-15 08:38 UTC, merged