special-pickup-zone
nammayatri/nammayatri pull request #5580
Opened 2024-02-19 06:20 UTC by DwivediAman-exe

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-02-19 07:17 UTC, MercyQueen requested changes

2024-02-19 07:17 UTC, MercyQueen commented on Frontend/ui-driver/src/Helpers/Utils.purs
> +      backgroundColor : "#53BB6F",
add this color in colour.purs file

2024-02-19 07:17 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +    , visibility if (DA.any (_ == state.props.currentStage) [RideAccepted, RideStarted, ChatWithCustomer] || not state.props.statusOnline) then GONE else VISIBLE
use boolToVisibility here.

2024-02-19 07:17 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +    -- , visibility according to 150 meter flag
Add TODO if required.

2024-02-19 07:17 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +specialMetoPickupZone push state =
rename this.

2024-02-19 07:17 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/HomeScreen/Controller.purs
> +                        else if isJust ride.driverGoHomeRequestId then Just "GOTO"
@DwivediAman-exe why is safety check removed here?

2024-02-19 07:17 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/HomeScreen/ComponentConfig.purs
> +  specialZonePickup = state.data.endRideData.specialZonePickup /= Nothing
use isNothing here.

2024-02-19 07:17 UTC, MercyQueen commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/OverlaySheetService.java
> +            System.out.println("zxc updateExtraChargesString" + model.getSpecialZoneExtraTip());
remove logs

2024-02-19 07:17 UTC, MercyQueen commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/OverlaySheetService.java
> +                String pickUpChargesWithZone = pickupChargesText += " and " + sharedPref.getString("CURRENCY", "₹") + " " + model.getSpecialZoneExtraTip() + " " + "Zone pickup extra";
add translations

2024-02-19 13:03 UTC, DwivediAman-exe commented on Frontend/ui-common/src/Components/RideCompletedCard/View.purs
> +    , imageWithFallback $ fetchImage FF_COMMON_ASSET $ fromMaybe "" config.topCard.topPill.icon
> raise a PR for assetStore for assets

there will be apk update :(

2024-02-19 13:35 UTC, DwivediAman-exe commented on Frontend/android-native/mobility-app/src/main/res/drawable/rectangle_9506.xml
I didn't add this image :(

2024-02-20 17:58 UTC, ashishsingh101 submitted a review, later dismissed

2024-10-19 20:35 UTC, DwivediAman-exe commented
This commit was used somewhere else.

2024-10-19 20:35 UTC, closed without merging