backend/feat: #555 return deployment version in search
nammayatri/nammayatri pull request #563
Opened 2023-04-16 18:06 UTC by roman-bodavskiy

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Use the deployment version of BAP created in this PR - https://github.com/nammayatri/nammayatri/pull/441 , return it in response header x-deployment-version of search request API.

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?
Tested locally. Not working if API returns error

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-17 03:24 UTC, pavelzarubin submitted a review, later dismissed

2023-05-17 10:53 UTC, umangj-28 submitted a review, later dismissed

2023-05-29 13:54 UTC, hkmangla requested changes

2023-05-29 15:43 UTC, srid commented on flake.nix
> +    shared-kernel.url = "github:nammayatri/shared-kernel/2d800a9bd774feec05de8714f4d2021351cc1fd7";
Yes, see https://github.com/nammayatri/nammayatri/tree/main/Backend#updating-flake-inputs

2023-05-29 16:01 UTC, roman-bodavskiy commented on flake.nix
> +    shared-kernel.url = "github:nammayatri/shared-kernel/2d800a9bd774feec05de8714f4d2021351cc1fd7";
Fixed. Now updated only lock file

2025-09-16 05:18 UTC, roman-bodavskiy commented
too much outdated

2025-09-16 05:18 UTC, closed without merging