frontend/feat: Added Rentals and Intercity Support
nammayatri/nammayatri pull request #5645
Opened 2024-02-21 08:01 UTC by aryan-13

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-02-27 14:28 UTC, hkmangla commented on Frontend/ui-common/src/Components/RateCard/Controller.purs
> +    primaryButtonConfig : {
ButtonConfig = NotVisible | Visible VisibleButtonConfig

VisibleButtonConfig = VisibleButtonConfig
{
}

2024-02-27 14:53 UTC, hkmangla commented on Frontend/ui-customer/src/Flow.purs
> +          isIntercity = any (_ == "*") [(fromMaybe "" sourceServiceabilityResp.currentCity), (fromMaybe "" sourceServiceabilityRespDest.currentCity)]
any (_ == Just "*") [sourceServiceabilityResp.currentCity, sourceServiceabilityRespDest.currentCity]

2024-05-20 11:19 UTC, ashishsingh101 requested changes

2024-05-20 12:44 UTC, ashishsingh101 requested changes

2024-05-20 12:44 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Flow.purs
> +--           Snapped points = response.points
remove this

2024-05-20 13:30 UTC, ashishsingh101 approved these changes

2024-05-20 13:42 UTC, ashishsingh101 submitted a review, later dismissed

2024-05-22 08:33 UTC, merged