frontend/fix/current-location-tag: fixed current location not visible, added edit button
nammayatri/nammayatri pull request #5752
Opened 2024-02-28 06:52 UTC by yashikakaushik

… on homescreen

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

https://github.com/nammayatri/nammayatri/assets/57990459/046b7551-9a9d-4911-911f-c784ac77b555

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-02-29 08:43 UTC, yashikakaushik commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +                  , text $ (if state.props.isSrcServiceable then state.data.source else getString NOT_SERVICEABLE)
if `(getString PICKUP_)` is kept, the address line looks too big and not appropriate

2024-03-13 11:33 UTC, aryan-13 requested changes

2024-03-13 11:33 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +  linearLayout
Is this view tested for IOS as well?

2024-03-13 11:33 UTC, aryan-13 commented on Frontend/ui-customer/src/Flow.purs
> +              if address.formattedAddress /= "NO_LOCATION_FOUND" then do
For better type safety, can we make this Nothing if there no address found("NO_LOCATION_FOUND"), instead of returning a string.

2024-03-14 09:34 UTC, aryan-13 submitted a review, later dismissed

2024-03-14 09:50 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +eval (SavedAddressClicked (LocationTagBarController.TagClick savedAddressType arrItem)) state = if not state.props.isSrcServiceable then continue state else tagClickEvent savedAddressType arrItem sta
@yashikakaushik can we put the events back

2024-03-14 09:58 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +      _ <- addMarker (getCurrentLocationMarker (getValueToLocalStore VERSION_NAME)) 9.9 9.9 160 (0.5) (0.9)
@yashikakaushik calling this function here will cause double marker issue. If the issue is with marker not being added in homeScreen then try calling it in MapReadyAction.

2024-03-14 09:59 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +currentLocationView :: forall w. (Action -> Effect Unit) -> HomeScreenState -> PrestoDOM (Effect Unit) w --to see
remove commented code if not required.

2024-03-14 10:01 UTC, MercyQueen reviewed
Resolve comments

2024-03-14 10:48 UTC, MercyQueen approved these changes

2024-03-19 08:03 UTC, witcher-shailesh approved these changes

2024-03-19 08:03 UTC, merged