frontend/#4155: edit Pickup location
nammayatri/nammayatri pull request #6122
Opened 2024-03-28 15:36 UTC by Shikhar-24

## Type of Change

- [ ] Bugfix
- x ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Edit pickup location native changes

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-04-01 07:08 UTC, aryan-13 requested changes

2024-04-01 07:08 UTC, aryan-13 commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/MobilityCommonBridge.java
> +    public void createCircle(LatLng source, float radius) {
Can we pass color to this function, strokeWidth, FillColor  to this function

2024-04-01 07:08 UTC, aryan-13 commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/MobilityCommonBridge.java
> +    protected Circle circle = null;
Will this support multiple circles on the map at a single point of time?

2024-07-18 06:48 UTC, MercyQueen commented on Frontend/ui-customer/src/MerchantConfigs/DefaultConfig.purs
> +            editPickUpRadius : 100.0 --in meters
can we use one of the two variables at all places instead of creating two different variables.

2024-07-18 06:50 UTC, MercyQueen commented on Frontend/android-native/mobility-customer/src/main/java/in/juspay/mobility/customer/MobilityCustomerBridge.java
> +                            currMarker.setAnchor(0.4f, 0.8f);
can we send the anchor also from purescript , instead of hardcoding it here.

2024-07-18 06:51 UTC, MercyQueen commented on Frontend/android-native/mobility-customer/src/main/java/in/juspay/mobility/customer/MobilityCustomerBridge.java
> +import com.google.android.gms.maps.model.Circle;
do we need these two imports?

2024-07-18 06:53 UTC, MercyQueen commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/MobilityCommonBridge.java
> +                    options.fromStrokeColor("#fcc32c");
can we send this color in config.

2024-07-18 06:55 UTC, MercyQueen commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/MobilityCommonBridge.java
> +                                    if (!EDIT_LOCATION) marker = CURRENT_LOCATION;
instead of adding this check we can send a flag from purescript which would decide if we want the marker to be drawn or not.

2024-07-18 06:56 UTC, MercyQueen commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/MobilityCommonBridge.java
> +                                    if (!EDIT_LOCATION) marker = CURRENT_LOCATION;
should line no.629 also be a part of if condition?

2024-07-18 06:56 UTC, MercyQueen commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/MobilityCommonBridge.java
> +         circle.updateCircle(config);
can we add null check here.

2024-07-18 06:57 UTC, MercyQueen commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/MobilityCommonBridge.java
> +                    circleRipples.put("edit_location_circle", circleRippleEffect);
add null check here also.

2024-07-18 06:58 UTC, MercyQueen commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/MobilityCommonBridge.java
> +                    LatLng source = new LatLng(Double.parseDouble(lat), Double.parseDouble(lon));
name this as location or something generic instead of source.

2024-07-18 07:00 UTC, MercyQueen commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/MobilityCommonBridge.java
> +                                if (googleMap != null) {
this check can be removed from here as already this check is added in line no 848.

2024-07-18 07:01 UTC, MercyQueen commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/MobilityCommonBridge.java
> +                                    options.radius(editPickupThreshold);
can we create a function which would return options.

2024-09-13 07:15 UTC, closed without merging