backend/feat: added customer client info with first ride case
nammayatri/nammayatri pull request #6254
Opened 2024-04-04 13:54 UTC by ashishsaini25

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

added customer client info with first ride cas

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-04-25 10:19 UTC, vijaygupta18 submitted a review, later dismissed

2024-04-25 13:29 UTC, piyushKumar-1 submitted a review, later dismissed

2024-04-25 13:44 UTC, ashishsaini25 commented on Backend/dev/migrations/rider-app/1256-add-client-id.sql
> +CREATE INDEX idx_client_person_info_person_id ON atlas_rider_app.client_person_info USING btree (person_id);
add unique constraint.

2024-04-25 13:44 UTC, ashishsaini25 commented on Backend/dev/migrations/dynamic-offer-driver-app/0399-add-average-speed-for-bike.sql
> +SET avg_speed_of_vehicle = '{"sedan": 30, "suv": 30, "hatchback": 0,"autorickshaw": 0, "taxi" : 0, "taxiplus" : 0, "bike" : 25}'::json where merchant_id='favorit0-0000-0000-0000-00000favorit'; -- rep
Add proper commented queries.

2024-04-25 13:46 UTC, ashishsaini25 commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/UI/Profile.hs
> +  hasTakenCabRide <- QCP.findByPersonIdAndVehicleCategory personId $ Just BecknConfig.CAB
find all then filter.

2024-04-26 06:48 UTC, hkmangla requested changes

2024-04-26 06:48 UTC, hkmangla commented on Backend/dev/migrations/rider-app/1256-add-client-id.sql
> +CREATE INDEX idx_client_person_info_person_id ON atlas_rider_app.client_person_info USING btree (person_id);
Still unresolved.

2024-04-26 12:25 UTC, hkmangla approved these changes

2024-04-26 12:25 UTC, merged