frontend/feat/rentals: Background Polling in HomeScreen
nammayatri/nammayatri pull request #6354
Opened 2024-04-10 12:49 UTC by slow-codex

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description

Added background polling for scheduled rides in HomeScreen in an interval of 120s.

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-04-10 13:27 UTC, aryan-13 requested changes

2024-04-10 13:27 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +  let bookingId = if (state.props.bookingId == "") then maybe "" (\bookingTime -> bookingTime.bookingId) $ head $ decodeBookingTimeList FunctionCall else state.props.bookingId
use DS.null

2024-04-10 13:27 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +      _ = spy "afdasfads" $ trackingId == (getValueToLocalStore TRACKING_ID)
Remove logs

2024-04-11 08:10 UTC, MercyQueen requested changes

2024-04-12 07:19 UTC, aryan-13 approved these changes

2024-04-12 07:20 UTC, merged