backend/feat: blocked routes & toll names
nammayatri/nammayatri pull request #6547
Opened 2024-04-25 05:22 UTC by khuzema786

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-05-03 09:52 UTC, hkmangla requested changes

2024-05-05 08:08 UTC, khuzema786 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Ride/EndRide.hs
> +               isRectifiedDistantPointsUponDistanceCalculationFailure = Just shouldRectifyDistantPointsSnapToRoadFailure
Done

2024-05-05 08:18 UTC, khuzema786 commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/Beckn/OnSearch.hs
> +    serviceTierShortDesc :: Maybe Text,
Done

2024-05-05 08:18 UTC, khuzema786 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Beckn/Search.hs
> +        mbTollChargesAndNames <- getTollInfoOnRoute merchantOpCityId Nothing serviceableRoute.routePoints
Not Required

2024-05-05 14:55 UTC, hkmangla approved these changes

2024-05-05 14:55 UTC, merged