Calculating driver speed
nammayatri/nammayatri pull request #66
Opened 2023-03-02 22:14 UTC by piyushKumar-1

## Type of Change
- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Added driver speed calculation (straight line distance based) using redis based on location updates.

### Additional Changes
- [ ] This PR modifies the database schema (database migration added)
- [x] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context
This will be used to deprioritize moving drivers while calculating driver pool for sending search requests.

## How did you test it?
tested locally by calling driver location API.

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-03-06 07:12 UTC, pavelzarubin approved these changes

2023-03-25 11:45 UTC, hkmangla requested changes

2023-03-28 09:37 UTC, hkmangla requested changes

2023-03-28 09:37 UTC, hkmangla commented on Backend/dev/migrations/dynamic-offer-driver-app/0133-added-driver-speed-configs.sql
> +ADD COLUMN speed_weightage_of_driver INT DEFAULT 5,
not tested in local. As column names are not matching with names in Persistent Table

2023-03-28 09:37 UTC, hkmangla commented on Backend/dev/migrations/dynamic-offer-driver-app/0133-added-driver-speed-configs.sql
> +ADD COLUMN driver_default_speed DOUBLE DEFAULT 27.0;
why default driver speed should be 27.0? Isn't it at higher side.

2023-04-05 10:01 UTC, hkmangla approved these changes

2023-04-05 10:23 UTC, merged