#526:replicated_firebase_logging_system
nammayatri/nammayatri pull request #661
Opened 2023-04-24 10:43 UTC by SanskarGubreley

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ x] Enhancement
- [ x] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?
i tested using firebase, and locally on logcats.

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-27 03:23 UTC, ks-shree commented
@SanskarGubreley 
Please follow guidelines while creating PR's
https://github.com/nammayatri/nammayatri/blob/main/docs/CONTRIBUTING.md

2023-04-27 03:24 UTC, ks-shree commented on Frontend/android-native/app/src/dev/assets/juspay/becknbase.html
> +    var url = "http://" + "192.168.11.227" + ":" + port;
@SanskarGubreley Don't commit your local ip

2023-04-27 03:25 UTC, ks-shree commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.purs
> +>>>>>>> Stashed changes
@SanskarGubreley 
What is Updated upstream , Stashed changes ?

2023-04-27 03:25 UTC, ks-shree commented on Frontend/ui-common/src/Engineering/Helpers/Log.purs
> +    _ <- pure $ spy "debugLog" "logEvent func"
Remove spy statements

2023-04-27 03:26 UTC, ks-shree commented on Frontend/ui-common/src/Engineering/Helpers/Log.purs
> +        x = insert "event" (encode event) empty
@SanskarGubreley Can you use proper variable name instead of x, y etc

2023-04-27 03:27 UTC, ks-shree commented on Frontend/ui-common/src/Engineering/Helpers/Log.purs
> +logEventWithParams event str1 str2 = do
Can you use proper variable name

2023-04-27 03:28 UTC, ks-shree commented on Frontend/ui-common/src/Engineering/Helpers/Log.purs
> +  let isFirebaseEnabled_ = true
@SanskarGubreley Why `isFirebaseEnabled_` is always true ?

2023-04-27 03:29 UTC, ks-shree commented on Frontend/ui-common/src/Engineering/Helpers/Log.purs
> +  let isFirebaseEnabled_ = true
Why is `isFirebaseEnabled_` is always true

2023-04-27 03:30 UTC, ks-shree commented on Frontend/ui-common/src/Engineering/Helpers/Log.purs
> +      lift $ lift $ liftFlow $ firebaseLogEventWithTwoParams event param1_str1 param1_str2 param2_str1 param2_str2
Rename variable

2023-04-27 03:31 UTC, ks-shree commented on Frontend/ui-customer/src/Components/SearchLocationModel/View.purs
> +<<<<<<< Updated upstream
@SanskarGubreley 
What is this line ?

2023-04-27 03:32 UTC, ks-shree commented on Frontend/ui-customer/src/Flow.purs
> +  _ <- pure $ spy "testing_inside_if" "8791"
@SanskarGubreley Remove spy

2023-04-27 03:33 UTC, ks-shree commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/Controller.purs
> +            launchAff_ $ flowRunner $ runExceptT $ runBackT $ do
What is the purpose of flowRunner here ?

2023-04-27 03:34 UTC, ks-shree commented on Frontend/ui-customer/src/Screens/OnBoardingFlow/EnterMobileNumberScreen/View.purs
> +import Debug.Trace (spy)
Remove import which is not used

2023-04-27 03:35 UTC, ks-shree commented on Backend/stack-hie.yaml.lock
@SanskarGubreley Why `stack-hie.yaml.lock` file is committed in frontend PR , Can you remove?

2023-04-27 03:37 UTC, ks-shree requested changes
Check comments and some comments are applicable for other files also , Please check and resolve .

2023-05-08 11:49 UTC, hkmangla commented
Please follow contribution guidelines in commit message and PR title.

2023-05-09 07:09 UTC, closed without merging