backend/feat: Monthly Leaderboard
nammayatri/nammayatri pull request #6782
Opened 2024-05-08 17:20 UTC by slow-codex

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Added Leaderboard Configs for monthly basis.

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

<img width="352" alt="image" src="https://github.com/nammayatri/nammayatri/assets/83444620/ee1acf63-071b-40e3-9e1e-6741871b72cd">

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-05-09 06:07 UTC, rupakkorde commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/LeaderBoard.hs
> +startMonthlyBackFill :: (Esq.EsqDBFlow m r, EncFlow m r, Redis.HedisFlow m r, CacheFlow m r) => Id DM.Merchant -> Id DMOC.MerchantOperatingCity -> Day -> Day -> m ()
Monthly backfill is not required as it is not in prod.

2024-05-09 06:34 UTC, 0utkarsh requested changes

2024-05-09 06:34 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/LeaderBoard.hs
> +  when (monthDiff < 0 || monthDiff > 3) $ throwError $ InvalidRequest "Month outside Range"
For this, you can use sets in config instead of hardcoding.

2024-05-09 06:34 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/LeaderBoard.hs
> +      return $ LeaderBoardRes (currDriverInfo : drivers') (Just now) (fromIntegral totalEligibleDrivers)
All this code looks repeated in each type of leaderboard, can be refactored

2024-05-09 06:34 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Ride/EndRide/Internal.hs
> +
These functions can be refactored

2024-05-09 06:34 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/LeaderBoard.hs
> +  when (inputMonthDiff /= 0 || fromDate /= RideEndInt.getStartDateMonth fromDate || toDate /= RideEndInt.getEndDateMonth toDate 1) $
Hmm. so no use of taking `fromDate` and `toDate` here as an input then? We could've just taken month number(1-12). Anyway, this is fine for now

2024-05-16 08:31 UTC, 0utkarsh approved these changes

2024-05-16 08:31 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Ride/EndRide/Internal.hs
>    let currentDate = localDay $ utcToLocalTime timeZoneIST time
All these type of functions are not correct, we'll have to take for US. cc: @hkmangla

2024-05-16 10:06 UTC, 0utkarsh approved these changes

2024-05-16 10:06 UTC, merged