frontend/feat: Monthly LeaderBoard
nammayatri/nammayatri pull request #6807
Opened 2024-05-09 18:29 UTC by slow-codex

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description

Added Monthly Leader Board, taken API definition from this PR : #6782 

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

Tested it manually.

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-06-25 10:29 UTC, spravinkumar9952 requested changes

2024-06-25 10:29 UTC, spravinkumar9952 commented on Frontend/ui-common/src/Engineering/Helpers/Commons.js
> +
Can you return empty array if it throws error? also why it needs try catch block?

2024-06-25 10:29 UTC, spravinkumar9952 commented on Frontend/ui-driver/src/Screens/ReferralScreen/Controller.purs
> +  if (any (_ == "") [state.props.selectedDay.utcDate, state.props.selectedWeek.utcStartDate, state.props.selectedWeek.utcEndDate, state.props.selectedMonth.utcDate]) then do
just we can call Data.String null 
`any DS.null [state.props.selectedDay.utcDate, state.props.selectedWeek.utcStartDate, state.props.selectedWeek.utcEndDate, state.props.selectedMonth.utcDate])`

2024-06-25 10:29 UTC, spravinkumar9952 commented on Frontend/ui-driver/src/Screens/ReferralScreen/View.purs
> +      , textSize FontSize.a_16
can you use the predefined fonts instead of giving property directly ?

2024-06-25 10:29 UTC, spravinkumar9952 commented on Frontend/ui-driver/src/Screens/ReferralScreen/View.purs
> +    , textSize FontSize.a_12
same here

2024-06-25 10:29 UTC, spravinkumar9952 commented on Frontend/ui-driver/src/Screens/ReferralScreen/View.purs
> +        , textSize FontSize.a_16
here also

2024-06-25 10:29 UTC, spravinkumar9952 commented on Frontend/ui-driver/src/Screens/ReferralScreen/View.purs
> +        , textSize FontSize.a_10
here also

2024-06-25 10:29 UTC, spravinkumar9952 commented on Frontend/ui-driver/src/Screens/ReferralScreen/View.purs
> +                              in MonthlyRequest selectedMonth.month
Same here. we can use DS.null  and we can also replace some brackets with $

2024-06-25 12:51 UTC, spravinkumar9952 submitted a review, later dismissed

2024-06-26 04:56 UTC, Vignesh-772 submitted a review, later dismissed

2024-07-29 10:55 UTC, ashishsingh101 approved these changes

2024-07-29 10:56 UTC, merged