frontend/fix/invoice-screen-fix
nammayatri/nammayatri pull request #6860
Opened 2024-05-14 08:06 UTC by Shikhar-24

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Base fare coming twice in Invoice screen.

2024-05-21 07:48 UTC, MercyQueen requested changes

2024-05-21 08:38 UTC, Shikhar-24 commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +export const differenceBetweenTwoUTCInMinutes = function (date1, date2) {
this function is already present in main

2024-05-24 10:40 UTC, MercyQueen approved these changes

2024-05-27 22:48 UTC, aryan-13 commented on Frontend/ui-customer/src/Screens/CustomerUtils/InvoiceScreen/View.purs
> +        "BASE_FARE" -> (getString BASE_FARES) -- <> if baseDistance' == "0 m" then "" else " (" <> baseDistance' <> ")"
Remove if not required

2024-05-28 13:06 UTC, Shikhar-24 commented on Frontend/ui-customer/src/Screens/CustomerUtils/InvoiceScreen/View.purs
> +        "BASE_FARE" -> (getString BASE_FARES) -- <> if baseDistance' == "0 m" then "" else " (" <> baseDistance' <> ")"
already in main branch
Took from there

2024-07-10 14:11 UTC, closed without merging