fare-breakup support chat added
nammayatri/nammayatri pull request #6865
Opened 2024-05-14 09:34 UTC by yashikakaushik

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-05-17 14:29 UTC, ashishsingh101 requested changes

2024-05-17 14:29 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Screens/CustomerUtils/RideSelectionScreen/Handler.purs
> +import Data.Maybe (fromMaybe)
not required

2024-05-17 14:29 UTC, ashishsingh101 commented on Backend/dev/migrations/rider-app/1262-adding-fare-breakup-chat.sql
> +UPDATE atlas_app.issue_message
can we include migration as separate backend PR

2024-05-20 13:29 UTC, ashishsingh101 approved these changes

2024-05-20 13:29 UTC, merged

2024-05-30 08:28 UTC, witcher-shailesh commented
Use proper contributing guidelines please - https://github.com/nammayatri/nammayatri/blob/d68c2b7df32b519b1e60beb9eed603a16829a3d3/docs/CONTRIBUTING.md

cc: @ashishsingh101