frontend/feat:forward booking ui
nammayatri/nammayatri pull request #6871
Opened 2024-05-14 21:41 UTC by aayushagarwal2001

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-05-27 13:14 UTC, aayushagarwal2001 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/NotificationUtils.java
> +        boolean useWidgetService = (sharedPref.getString("DRIVER_STATUS_N", "null").equals("Silent") && activityBasedChecks) || useSilentFCMForForwardBatch;
> boolean activityBasedChecks = Arrays.asList("onPause", "onDestroy").contains(sharedPref.getString("ACTIVITY_STATUS", "null"));
it's taken care in the above line

2024-06-06 06:43 UTC, aryan-13 commented on Frontend/ui-driver/src/Components/RideActionModal/View.purs
> +  let _ = spy "rideActionModalView" config
Spy statements can be removed

2024-06-06 06:43 UTC, aryan-13 commented on Frontend/android-native/app/src/driver/nammaYatriPartner/assets/juspay/index_bundle.js
Remove this

2024-06-06 06:43 UTC, aryan-13 commented on Frontend/ui-common/src/Components/PopUpModal/Controller.purs
> +      text : "Text2",
Can we keep default text as empty

2024-06-06 06:43 UTC, aryan-13 commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +    return function (coordinates) {
Please make this uncurried

2024-06-06 07:47 UTC, MercyQueen requested changes

2024-06-06 07:47 UTC, MercyQueen commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/MobilityCommonBridge.java
> +                System.out.println("marker keys in map" + markers.keySet());
remove commented code.

2024-06-06 07:47 UTC, MercyQueen commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/MobilityCommonBridge.java
> +        if (polylines != null) { return polylines.get(polyLineKey);}
give proper indentation here.

2024-06-06 07:47 UTC, MercyQueen commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/Utils.java
> +import android.annotation.SuppressLint;
remove the import if not required.

2024-06-06 07:47 UTC, MercyQueen commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.js
> +        for (let i = 0; i < configs.length; i++) {
@aayushagarwal2001 this loop would be terminated after the first execution as we are returning it inside the loop. Please handle the loop according to the requirement.

2024-06-06 07:47 UTC, MercyQueen commented on Frontend/ui-customer/src/MerchantConfigs/Types.purs
> +  , isAdvancedBookingEnabled :: Boolean
@aayushagarwal2001 can we put this inside feature object.

2024-06-06 07:47 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ScreenData.purs
> +  driversPreviousRideDropLocLat : Nothing,
create an object for this : driversPreviousRIdeDropLoc : {
lat : Number, lon : Number}

2024-06-06 07:47 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +                    case ((routeResp) !! 0), ((routeRespAdvanced) !! 0), hasCurrentLocAndPrevDropLoc of
use `head` instead of `!!0`

2024-06-06 07:47 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/HomeScreen/Controller.purs
> +    _ <- pure $ setValueToLocalStore LOCAL_STAGE (show $ fetchStageFromRideStatus activeRideData)
replace `_<-` with `void`

2024-06-06 07:47 UTC, MercyQueen commented on Frontend/ui-common/src/Components/PopUpModal/View.purs
> +parseConerRadius corners =
@aayushagarwal2001 can you rename this to parseCornerRadius. 
 And why are we not assigning the corner radius sent directly here?
 If we need only the radius then radius alone as number.

2024-06-06 14:53 UTC, witcher-shailesh approved these changes

2024-06-06 14:54 UTC, MercyQueen approved these changes

2024-06-06 14:54 UTC, MercyQueen commented on Frontend/ui-common/src/DecodeUtil/DecodeUtil.purs
> +    let _ = toastWithLog $ "Config Decode Failed - " <> ("Error for Key " <> "ErrorAtProperty " <> key <> show fnError)
@aayushagarwal2001 remove fnError

2024-06-06 15:18 UTC, MercyQueen approved these changes

2024-06-07 02:49 UTC, merged