frontend/#5460/Driver Interoperability Feature
nammayatri/nammayatri pull request #6891
Opened 2024-05-15 12:39 UTC by ashishsingh101

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

1. Driver Interoperability flow

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-05-16 09:01 UTC, Rohit4997 requested changes

2024-05-16 09:01 UTC, Rohit4997 commented on Frontend/android-native/mobility-customer/src/main/res/values-hi/strings.xml
> +    <string name="third_party_booking">"तीसरे पक्ष की बुकिंग"</string>
These strings are not used in mobility customer, Please remove from mobility-customer

2024-05-23 07:04 UTC, ashishsingh101 commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +        -- , if state.data.activeRide.bookingFromOtherPlatform then RideActionModal.bottomPlatformInfoBar VISIBLE else dummyTextView
need this

2024-05-23 07:06 UTC, ashishsingh101 commented on Frontend/ui-driver/src/Components/RideActionModal/View.purs
> +bottomPlatformInfoBar :: forall w. Visibility -> PrestoDOM (Effect Unit) w
commented as we may need this in future

2024-05-23 07:23 UTC, ashishsingh101 commented on Frontend/android-native/app/src/main/res/values-hi/strings.xml
> +    <string name="third_party_booking">"तीसरे पक्ष की बुकिंग"</string>
online articles prefer `तृतीय` so replaced with that

2024-05-23 07:37 UTC, ashishsingh101 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/OverlaySheetService.java
> +        if (isThirdPartyBooking) {
as per new design will have to show `nammaYatri` tag so removed this logic only

2024-06-07 08:05 UTC, MercyQueen requested changes

2024-06-07 08:05 UTC, MercyQueen commented on Frontend/ui-driver/src/Resource/Localizable/EN.purs
> +        MERCHANT_NAME _ -> "Namma Yatri"
use merchant name from config

2024-06-07 08:13 UTC, MercyQueen submitted a review, later dismissed

2024-06-07 08:22 UTC, aryan-13 approved these changes

2024-06-07 08:25 UTC, Rohit4997 approved these changes

2024-06-07 08:25 UTC, merged