frontend-feat-latest-may-changes
nammayatri/nammayatri pull request #6907
Opened 2024-05-16 13:42 UTC by spravinkumar9952

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

- Carousel Issue cards
- Toll popups
- other ui fixes

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-05-27 06:56 UTC, ashishsingh101 requested changes

2024-05-27 06:56 UTC, ashishsingh101 commented on Frontend/ui-driver/src/Screens/HomeScreen/ScreenData.purs
> +      , showTollChargeAmbigousPopup : false
we can create new object for toll and move both of them inside it

2024-05-27 06:56 UTC, ashishsingh101 commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +  , showScrollIndicator : true
it should be based on length of banners

2024-05-28 06:37 UTC, spravinkumar9952 commented on Frontend/ui-driver/src/Screens/HomeScreen/PopUpConfig.purs
Component Config is already growing too much. compilation time is increased. thats why. (like banner config)

2024-05-28 07:04 UTC, spravinkumar9952 commented on Frontend/ui-customer/src/Components/DriverInfoCard/View.purs
> +  , showScrollIndicator : true
be default we need this scroll indicator in all the places. thats why made it as true. in my case only its false.

2024-05-28 07:27 UTC, spravinkumar9952 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/PopUpConfigs.purs
Component Config is already growing too much. compilation time is increased. thats why. (like banner config)

2024-05-28 07:29 UTC, spravinkumar9952 commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +  , showScrollIndicator : true
thats handled internally

2024-05-28 15:16 UTC, ashishsingh101 submitted a review, later dismissed

2024-05-28 17:22 UTC, aryan-13 submitted a review, later dismissed

2024-05-29 06:18 UTC, Vignesh-772 submitted a review, later dismissed

2024-05-29 07:10 UTC, Vignesh-772 approved these changes

2024-05-29 07:10 UTC, merged