frontend/edit destination popup changes
nammayatri/nammayatri pull request #6920
Opened 2024-05-17 10:22 UTC by RitikaHanish

## Type of Change
frontend/edit destination popup changes

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
frontend/edit destination popup changes

2024-05-17 11:13 UTC, Rohit4997 requested changes

2024-05-17 11:13 UTC, Rohit4997 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/OverlayMessagingService.java
> +                                        public void run() {
This can be replaced with lambda function

2024-05-17 11:13 UTC, Rohit4997 commented on Frontend/android-native/mobility-app/src/main/java/in/juspay/mobility/app/OverlayMessagingService.java
> +            System.out.println("Exception in performDependentAction: "+ e);
Kindly add firebase logs to track exceptions 
Please check this in whole PR

2024-05-17 11:13 UTC, Rohit4997 commented on Frontend/android-native/mobility-app/src/main/res/layout/message_overlay.xml
> +                                            android:text="New Drop: Kempogowda International Airport bengaluru ............."
Kindly remove this dummy value
Check this in full file

2024-05-17 11:13 UTC, Rohit4997 commented on Frontend/android-native/mobility-app/src/main/res/layout/message_overlay.xml
> +                                        android:text="New fare: "
Translations

2024-05-20 14:35 UTC, Rohit4997 submitted a review, later dismissed

2024-05-21 10:09 UTC, witcher-shailesh approved these changes

2024-05-21 10:38 UTC, merged