feat frontend feat add contition to show pickup or waitingtime
nammayatri/nammayatri pull request #7004
Opened 2024-05-22 12:17 UTC by aryan010803

## Type of Change

- [x ] Enhancement

## Description
Added a condition to show PickUp distance or Wait time in driver side before starting the ride

2024-05-29 06:35 UTC, kavya-shree-s requested changes

2024-05-29 06:35 UTC, kavya-shree-s commented
@aryan010803 can you resolve comments and conflicts

2024-06-07 13:52 UTC, kavya-shree-s commented on Frontend/ui-driver/src/Components/RideActionModal/View.purs
> +          -- , if  isWaitingTimeStarted config || not (isPickUpDistanceZero config) then separator true else  separator false
Don't push commented code

2024-06-07 14:03 UTC, aryan-13 requested changes

2024-06-07 14:03 UTC, aryan-13 commented on Frontend/ui-driver/src/Components/RideActionModal/View.purs
> +    , visibility if config.distance /= 0  then VISIBLE else GONE
use `boolToVisibility`

2024-06-10 06:53 UTC, kavya-shree-s approved these changes

2024-06-10 06:54 UTC, merged