backend/feat : version control
nammayatri/nammayatri pull request #7050
Opened 2024-05-27 00:44 UTC by aayushagarwal2001

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-05-27 09:30 UTC, hkmangla submitted a review, later dismissed

2024-05-29 08:21 UTC, jaypalmudaliyar24 commented on Backend/app/rider-platform/rider-app/Main/src/Beckn/ACL/Select.hs
> +mkAutoAssignEnabledTagGroup res =
function name mismatch

2024-05-30 11:54 UTC, hkmangla requested changes

2024-05-30 11:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Ride.hs
> +        vehicleVariant = Just $ DP.castServiceTierToVariant booking.vehicleServiceTier
it should be vehicle.variant :)

2024-05-30 12:39 UTC, hkmangla approved these changes

2024-05-30 12:39 UTC, merged