Vehicle rate card
nammayatri/nammayatri pull request #7102
Opened 2024-05-31 06:28 UTC by Rohit4997

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-06-07 10:34 UTC, aryan-13 submitted a review, later dismissed

2024-06-07 10:34 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/BookingOptionsScreen/View.purs
> +          , background if peakTime then Color.green900 else Color.blue800
Use let and put all the props in an object and access it here

2024-06-07 10:34 UTC, aryan-13 commented on Frontend/ui-driver/src/Screens/RateCardScreen/View.purs
> +            , onClick push $ const $ OpenLink "https://www.youtube.com/shorts/NUTNKPzslpw"
Is this supposed to be hardcoded?

2024-06-07 10:58 UTC, MercyQueen requested changes

2024-06-07 10:58 UTC, MercyQueen commented on Frontend/ui-driver/src/Flow.purs
> +      modifyScreenState $ RateCardScreenStateType (\rateCardScreen -> rateCardScreen{props{ reRenderSlider = true }})
@Rohit4997 do we need to exit the screen to rerender slider? Can we remove this if not required.

2024-06-07 10:58 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/BookingOptionsScreen/Controller.purs
> +getPerKmRate :: API.ServiceTierType -> API.GetDriverRateCardRes -> Maybe Number
@Rohit4997 can we combine these three function.

2024-06-07 10:58 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/BookingOptionsScreen/Controller.purs
> +getVehicleMapping serviceTierType = case serviceTierType of
move this function to utils.

2024-06-07 10:58 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/RateCardScreen/Controller.purs
> +    show _ = ""
add logs for this screen.

2024-06-07 10:58 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/RateCardScreen/View.purs
> +    , globalEvents: [ (\push -> pure $ pure unit) ]
assign `[]` to global events

2024-06-07 12:14 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/RateCardScreen/View.purs
> +            , onClick push $ const $ OpenLink "https://www.youtube.com/shorts/NUTNKPzslpw"
Yes, We can hardcode

2024-06-07 12:19 UTC, MercyQueen commented on Frontend/ui-driver/src/Screens/BookingOptionsScreen/Controller.purs
> +eval (RateCardAction RateCard.Close) state = continue state { props { showRateCard = false } , data{rateCard{onFirstPage = false,currentRateCardType = CTA.DefaultRateCard}}}
create a common function for Close and BackPressed.

2024-06-10 07:42 UTC, MercyQueen approved these changes

2024-06-10 08:50 UTC, ashishsingh101 approved these changes

2024-06-10 08:50 UTC, merged