backend/fix: makes fulfillmentId consistent in on_update/on_status
nammayatri/nammayatri pull request #7120
Opened 2024-06-03 11:49 UTC by shreyaxh

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-06-03 11:55 UTC, jaypalmudaliyar24 approved these changes

2024-06-03 16:32 UTC, jaypalmudaliyar24 requested changes

2024-06-03 16:32 UTC, jaypalmudaliyar24 commented on Backend/dev/migrations-read-only/dynamic-offer-driver-app/bap_metadata.sql
> +ALTER TABLE atlas_driver_offer_bpp.bap_metadata ADD COLUMN subscriber_id text NOT NULL;
here `id` is `bap_subscriber_id` only, no need to add this new column.
Also merge drop not null queries by removing this change and regenrating.

2024-06-04 11:29 UTC, jaypalmudaliyar24 approved these changes

2024-06-04 12:03 UTC, NikithShetty commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Beckn/Search.hs
> +            name = "THIRD PARTY BAP",
you need to parse this as well from req

2024-06-04 12:25 UTC, merged