frontend/feat: HyperVerge Sdk Integration for Live selfie, Pan and Aa…
nammayatri/nammayatri pull request #7127
Opened 2024-06-03 16:42 UTC by ratnadeep-99

…dhaar flow.

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-06-07 13:37 UTC, Vignesh-772 commented on Frontend/ui-common/src/Engineering/Helpers/JBridge.purs
> +encodeToBase64Type url = makeAff \cb -> encodeToBase64 url (cb <<< Right) $> nonCanceler
Add a timeout to this function as it is main flow. Show a toast `Timed Out`

2024-06-18 14:05 UTC, Vignesh-772 requested changes

2024-06-18 14:05 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Helpers/Utils.js
> +export const setActivityResultListener = function (requestCode, cb) {
Why requestCode is required?

2024-06-18 14:05 UTC, Vignesh-772 commented on Frontend/ui-driver/src/Screens/RegistrationScreen/Controller.purs
> +          PROFILE_PHOTO -> continueWithCmd state [ pure $ CallHV "ny-selfie-flow" ""]
Make it configurable. As All the merchants wont use this.

2024-07-09 14:12 UTC, Rohit4997 requested changes

2024-07-09 14:12 UTC, Rohit4997 commented on Frontend/ui-driver/src/Flow.purs
> +      let expiry = runFn1 JB.makeSdkTokenExpiry 86400
`86400` Add it in constants

2024-07-09 14:12 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/AppUpdatePopUpScreen/Handler.purs
> +        NAMMAYATRI -> JB.openUrlInApp $ "https://play.google.com/store/apps/details?id=in.juspay.nammayatripartner&pcampaignid=web_share"
Add config here

2024-08-02 11:55 UTC, Rohit4997 requested changes

2024-08-02 11:55 UTC, Rohit4997 commented on Frontend/ui-driver/src/Screens/RegistrationScreen/View.purs
> +  let commonStatus = all (\docType -> statusCompOrManual (getStatus docType state)) item.dependencyDocumentType
Move this line to last case

2024-08-02 11:55 UTC, Rohit4997 commented on Frontend/ui-driver/src/Flow.purs
> +getHvErrorMsg :: Maybe String -> String
Move this function

2024-08-02 12:59 UTC, Rohit4997 approved these changes

2024-08-02 13:01 UTC, ashishsingh101 approved these changes

2024-08-02 13:03 UTC, merged