backend/feat: google maps metro integration
nammayatri/nammayatri pull request #7128
Opened 2024-06-03 17:11 UTC by jaypalmudaliyar24

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Adds changes related to google maps metro integration
- Adds api key based authentication
- Exposes FRFS config api for api key
- Exposes creating person and metro search for api key
- Exposes ticket list api for a `bookingId` for public ticket sharing.

### Additional Changes

- [x] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

Google maps metro ticket booking via webview.

## How did you test it?

Tested locally.

## Screenshot of test results

![image](https://github.com/nammayatri/nammayatri/assets/77069644/2f8c2679-a675-4853-8ab4-de936fcc0afd)

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [x] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-06-04 07:33 UTC, NikithShetty requested changes

2024-06-04 07:33 UTC, NikithShetty commented on Backend/dev/migrations-read-only/rider-app/partner_organization.sql
> +ALTER TABLE atlas_app.partner_organization ADD COLUMN api_key_hash text NOT NULL;
Let's also keep an encrypted version of the key, so that we can retrieve it later if required

2024-06-04 07:33 UTC, NikithShetty commented on Backend/dev/migrations-read-only/rider-app/station.sql
> +ALTER TABLE atlas_app.station ADD COLUMN gmm_station_name text ;
Let's create this as a separate table linking `partner_org` and the `station` table, instead of making this specific to GMM

2024-06-04 07:33 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/spec/Storage/PartnerOrganization.yaml
> +    config: PartnerOrganizationConfig
This table also requires a key to lookup the specific config, instead of loading everything?

2024-06-04 07:33 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/API/UI/PartnerOrganizationMetro.hs
> +    :> ( PartnerOrganizationAPIKey
Is this key hash or plain key?

2024-06-04 07:33 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/API/UI/PartnerOrganizationMetro.hs
> +                           :> Capture "fromGMMStationId" (Id DStation.GMMStation)
we can make this generic by looking up partner org instead of hardcoding GMM in query param?

2024-06-04 07:33 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/UI/PartnerOrganizationMetro.hs
> +    Redis.set ticketsExpiredForBookingKey True
Where are we setting the expire for this key?

2024-06-04 09:01 UTC, jaypalmudaliyar24 commented on Backend/app/rider-platform/rider-app/Main/src/API/UI/PartnerOrganizationMetro.hs
> +    :> ( PartnerOrganizationAPIKey
This is plain key

2024-06-14 16:30 UTC, NikithShetty approved these changes

2024-06-14 16:30 UTC, merged