Backend/fix: #624 Add merchant id column in few tables of BAP and BPP
nammayatri/nammayatri pull request #715
Opened 2023-04-27 15:00 UTC by vsaimanohar

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [X] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Added merchant id column in few tables of BAP and BPP

### Additional Changes

- [X] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Checklist

- [X] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [X] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-04-28 09:02 UTC, vsaimanohar commented
> Build is failing.

rebased, added a small error-fix to **beckn-test** module. All checks are passed now

2023-04-28 11:02 UTC, hkmangla requested changes

2023-04-28 11:20 UTC, vsaimanohar commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Tabular/Merchant.hs
> -      farePolicyType Domain.FarePolicyType
had to remove because of cyclic dependency between FareParameters and Merchant; added merchantId to FareParameters Table

2023-05-04 12:34 UTC, srid approved these changes

2023-05-04 12:34 UTC, srid commented on Backend/nix/arion-configuration.nix
> +        ports = [ "5435:5432" ];
👍🏿

2023-06-11 05:54 UTC, hkmangla requested changes

2023-06-11 05:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Ride/CancelRide.hs
> +          buildRideCancelationReason Nothing Nothing Nothing DBCR.ByMerchant ride (driver.merchantId)
why extra brackets?

2023-06-11 05:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Tabular/Ride/Table.hs
> +      merchantId MerchantTId
Make them Maybe type.

2023-06-11 05:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Tabular/DriverInformation.hs
> +      merchantId MerchantTId
Make then Maybe type.

2023-06-11 05:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Tabular/BookingCancellationReason.hs
> +      merchantId MerchantTId
Make then Maybe type.

2023-06-11 05:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Tabular/SearchRequestForDriver.hs
> +      merchantId MerchantTId
Make then Maybe type.

2023-06-11 05:54 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/Dashboard/Booking.hs
> +  let bcReasons = mkBookingCancellationReason (merchant.id) Common.bookingStuckCode Nothing <$> stuckBookingIds
remove extra brackets.

2023-06-11 05:54 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Storage/Tabular/BookingCancellationReason.hs
> +      merchantId MerchantTId
Make then Maybe type.

2023-06-11 05:54 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Storage/Tabular/DriverOffer.hs
> +      merchantId MerchantTId
Make then Maybe type.

2023-06-11 05:54 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Storage/Tabular/Estimate.hs
> +      merchantId MerchantTId
Make then Maybe type.

2023-06-11 05:54 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Storage/Tabular/Ride.hs
> +      merchantId MerchantTId
Make then Maybe type.

2023-06-11 05:55 UTC, hkmangla requested changes

2023-06-11 05:55 UTC, hkmangla commented on Backend/dev/migrations/rider-app/1125-add-merchantId-to-tables.sql
> +ALTER TABLE atlas_app.booking_cancellation_reason ADD COLUMN merchant_id character(36) NOT NULL REFERENCES atlas_app.merchant (id) DEFAULT 'da4e23a5-3ce6-4c37-8b9b-41377c3c1a51';
Just add merchantId as null in all tables without backfilling of data, as you have to make it Maybe in code. Also don't add any defaults.

2023-06-12 10:31 UTC, hkmangla approved these changes

2023-06-12 10:31 UTC, merged