Fronted-Fixes
nammayatri/nammayatri pull request #7174
Opened 2024-06-07 09:02 UTC by Kuldeepkumawat144

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [X ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Added Img for Cancel Ride on the basis of city
### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-06-07 11:02 UTC, MercyQueen approved these changes

2024-06-10 09:31 UTC, aryan-13 approved these changes

2024-06-10 10:03 UTC, ashishsingh101 requested changes

2024-06-10 10:03 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +    _ -> "ny_ic_driver_started_auto_bang_del"
this should be inside `Utils` file

2024-06-14 08:15 UTC, witcher-shailesh requested changes

2024-06-14 08:15 UTC, witcher-shailesh commented on Frontend/android-native/app/src/user/common/res/drawable/ny_ic_driver_near_auto_bang_del.png
instead of city name, assets should be of asset config names like black, yellow/green

2024-06-14 11:19 UTC, witcher-shailesh approved these changes

2024-06-14 11:24 UTC, Rohit4997 requested changes

2024-06-14 11:24 UTC, Rohit4997 commented on Frontend/android-native/app/src/user/jatriSaathiDriver/assets/juspay/juspay_assets.json
Please delete this file, This is not required, might be generated by wrong command

2024-06-14 11:29 UTC, Rohit4997 approved these changes

2024-06-14 11:52 UTC, ashishsingh101 approved these changes

2024-06-14 11:53 UTC, merged