frontend/fix: rental deadKmFare bug fix
nammayatri/nammayatri pull request #7246
Opened 2024-06-11 12:14 UTC by dhruv-1010

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

frontend fix for recent changes in rideSearch api for rental ride booking

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-06-11 13:19 UTC, aryan-13 approved these changes

2024-06-12 07:12 UTC, ashishsingh101 requested changes

2024-06-12 07:12 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Services/API.purs
> +
not required

2024-06-12 07:12 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Services/API.purs
> +instance encodeDeadKmFare  :: Encode DeadKmFare where encode = defaultEncode
we can remove other instance, we need only `show`

2024-06-12 07:30 UTC, ashishsingh101 approved these changes

2024-06-12 07:30 UTC, merged