frontend-fix: Fixed clever tab multiple onUserLogin issue
nammayatri/nammayatri pull request #7296
Opened 2024-06-13 06:09 UTC by spravinkumar9952

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-06-22 03:50 UTC, Vignesh-772 requested changes
Resolve the comments

2024-07-01 07:26 UTC, MercyQueen commented on Frontend/ui-driver/src/Flow.purs
> +    {key : "First ride taken", value : unsafeToForeign $ if fromMaybe 0 getDriverInfoResp.numberOfRides > 0 then true else false},
can we assign the expression itself, instead of true false explicitly.

2024-07-01 07:32 UTC, MercyQueen reviewed
resolve comments

2024-07-03 07:21 UTC, Vignesh-772 approved these changes

2024-07-03 07:32 UTC, merged