frontend/feat: Added Device Identifier
nammayatri/nammayatri pull request #7319
Opened 2024-06-13 14:46 UTC by PraveenGongada

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Added Device Identifier Class for Android

2024-06-13 14:53 UTC, MercyQueen commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/DeviceIdentifier.java
> +    private boolean isValid(String s) {
@PraveenGongada rename `s` to something intuitive

2024-06-13 14:54 UTC, MercyQueen commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/DeviceIdentifier.java
> +        return  s != null && !s.equals("") && !s.equals("null");
s != null and !s.equals("null") does the same thing right?

2024-06-14 04:54 UTC, Vignesh-772 requested changes

2024-06-14 04:54 UTC, Vignesh-772 commented on Frontend/android-native/mobility-common/src/main/java/in/juspay/mobility/common/DeviceIdentifier.java
> +        return  s != null && !s.equals("") && !s.equals("null");
Fix the warning in this file.

2024-06-14 08:11 UTC, Vignesh-772 approved these changes

2024-06-14 08:26 UTC, merged