Backend/feat/d2c referral
nammayatri/nammayatri pull request #7322
Opened 2024-06-13 18:14 UTC by prashant601

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-06-18 11:23 UTC, aayushagarwal2001 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src-read-only/API/Action/UI/ReferalPayout.hs
> +postPayoutCreateOrder a2 a1 = withFlowHandlerAPI $ Domain.Action.UI.ReferalPayout.postPayoutCreateOrder (Control.Lens.over Control.Lens._1 Kernel.Prelude.Just a2) a1
pls `postPayoutCreateOrder a2 a1`rename the parameters.

2024-06-18 11:23 UTC, aayushagarwal2001 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src-read-only/API/Action/UI/ReferalPayout.hs
> +getPayoutRegistration a1 = withFlowHandlerAPI $ Domain.Action.UI.ReferalPayout.getPayoutRegistration (Control.Lens.over Control.Lens._1 Kernel.Prelude.Just a1)
pls `getPayoutRegistration a1` rename the parameters.

2024-06-18 11:23 UTC, aayushagarwal2001 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src-read-only/API/Action/UI/ReferalPayout.hs
> +postDeleteVpa ::
pls `postDeleteVpa a1` rename the parameters.

2024-06-18 11:23 UTC, aayushagarwal2001 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Internal/DriverReferee.hs
> +  QDailyStats.updateReferralCount (dailyStats.referralCounts + 1) driverReferralLinkage.driverId (utctDay localTime)
is `updateReferralCount` is called at multiple locations if yes the put it in lock

2024-06-18 11:23 UTC, aayushagarwal2001 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +  invoices <- mapM (\fee_ -> runInReplica (QINV.findActiveManualInvoiceByFeeId fee_.id Domain.PAYOUT_REGISTRATION_INVOICE Domain.ACTIVE_INVOICE)) driverFee
`invoices <- mapM (\fee_ -> runInReplica (QINV.findActiveManualInvoiceByFeeId fee_.id Domain.PAYOUT_REGISTRATION_INVOICE Domain.ACTIVE_INVOICE)) driverFee`
should be 
`invoices <- mapM (\fee_ -> runInReplica (QINV.findActiveManualInvoiceByFeeId fee_.id (feeTypeToInvoicetype feeType) Domain.ACTIVE_INVOICE)) driverFee`

2024-06-18 11:23 UTC, aayushagarwal2001 commented on flake.nix
> +      # url = "github:nammayatri/shared-kernel";
pls revert this

2024-07-02 16:10 UTC, hkmangla requested changes

2024-07-02 16:10 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/ReferalPayout.hs
> +  vehicle <- QVeh.findById personId >>= fromMaybeM (DriverWithoutVehicle personId.getId)
What if driver had vehicle but later he removed his vehicle? Why should we break this API?

2024-07-02 16:10 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/ReferalPayout.hs
> +  payoutConfig <- CPC.findByPrimaryKey merchantOpCityId vehicle.variant >>= fromMaybeM (InternalError "Payout config not present")
Please resolve hlint errors, so that it could be reviewed properly.

2024-07-02 16:10 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Ride/EndRide/Internal.hs
> +            unencryptedMobileNumber <- decrypt riderDetails.mobileNumber
You can directly get hash.

2024-07-02 16:10 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/UI/Profile.hs
> +          personsWithSameDeviceId <- maybe (return []) (QPerson.findAllByDeviceId . Just) person.deviceId
We may need to add index on person.deviceId too 😅

2024-07-02 16:10 UTC, hkmangla commented on Backend/lib/payment/spec/Storage/Payouts.yaml
> +PayoutOrders:
PayoutOrder

2024-07-02 16:10 UTC, hkmangla commented on Backend/lib/payment/spec/Storage/Payouts.yaml
> +    amount : HighPrecMoney
Make it Price.

2024-07-02 16:10 UTC, hkmangla commented on Backend/lib/payment/spec/Storage/Payouts.yaml
> +    customerEmail : Text
Is it mandatory? And Hashed.

2024-07-02 16:10 UTC, hkmangla commented on Backend/lib/payment/spec/Storage/Payouts.yaml
> +    mobileNo : Text
encrypted.

2024-07-02 16:10 UTC, hkmangla commented on Backend/lib/payment/spec/Storage/Payouts.yaml
> +PayoutTransactions:
PayoutTransaction

2024-07-03 15:06 UTC, hkmangla approved these changes

2024-07-03 15:20 UTC, merged