contact support popup for YatriSathi
nammayatri/nammayatri pull request #7451
Opened 2024-06-21 10:57 UTC by yashikakaushik

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-06-24 10:20 UTC, MercyQueen requested changes

2024-06-24 10:20 UTC, MercyQueen commented on Frontend/ui-customer/src/Components/SettingSideBar/View.purs
> +                                                                                                      YATRISATHI -> getString CONTACT_SUPPORT
can we make this a config change?

2024-06-24 10:20 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/CustomerUtils/TripDetailsScreen/ComponentConfig.purs
> +          , margin = Margin 0 0 0 10
use marginBottom here.

2024-06-24 10:20 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/CustomerUtils/TripDetailsScreen/Controller.purs
> +eval (ContactSupportPopUpAction (PopUpModalController.OnButton2Click)) state = continue state{props{isContactSupportPopUp = false}}
call DismissPopUp action instead of duplicating the eval here.

2024-06-24 10:20 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/ComponentConfig.purs
> +contactSupportPopUpConfig state =
put this component inside commonComponentConfig. As it is being declared in TripDetailsScreen also.

2024-06-24 10:20 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +eval (ContactSupportAction (PopUpModal.OnButton2Click)) state = continue state{props{isContactSupportPopUp = false}}
direct user to DismissPopUp action here also.

2024-06-24 10:20 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +            , if (state.props.isContactSupportPopUp) then (contactSupportPopUpView push state) else emptyTextView state
remove `()`

2024-06-26 05:04 UTC, Vignesh-772 commented on Frontend/android-native/app/src/user/jatriSaathi/assets/juspay/v1-configuration.js
> +  , "enableHelpAndSupport" : false
Is it different support. There is already a key present to enable and disable support. can we reuse that?

2024-06-26 14:09 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/CustomerUtils/TripDetailsScreen/ComponentConfig.purs
> +import PrestoDOM (Length(..), Margin(..), Padding(..), Visibility(..), Gravity(..))
remove imports if not required.

2024-06-26 14:48 UTC, MercyQueen submitted a review, later dismissed

2024-06-28 14:45 UTC, MercyQueen approved these changes

2024-07-01 07:17 UTC, aryan-13 approved these changes

2024-07-03 08:13 UTC, Vignesh-772 approved these changes

2024-07-03 08:21 UTC, merged