backend/feat: #755/get-driver-leaderboard
nammayatri/nammayatri pull request #756
Opened 2023-05-02 19:37 UTC by vikrantkm1997

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [x] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-05 08:58 UTC, hkmangla requested changes

2023-05-05 08:58 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/LeaderBoard.hs
> +  merchant <- QM.findById person.merchantId >>= fromMaybeM (MerchantNotFound person.merchantId.getId)
Fetch config directly with fetching `merchant`. Anyways if merchant doesn't exist config will also be not there. So, we don't need to check for merchant separately.

2023-05-05 08:58 UTC, hkmangla commented on Backend/dev/migrations/dynamic-offer-driver-app/0157-add-colums-to-driverStats.sql
> +    WHERE ride_counts.DriverId = rideStats.DriverId;
shouldn't it be `driver_id`?

2023-05-05 08:58 UTC, hkmangla commented on Backend/dev/migrations/dynamic-offer-driver-app/0157-add-colums-to-driverStats.sql
> +-- Add column in Transporter Configs
Add `not null` constraint also to `total_rides` and `total_distance` field after updated value.

2023-05-05 10:47 UTC, 0utkarsh commented on Backend/dev/migrations/dynamic-offer-driver-app/0157-add-colums-to-driverStats.sql
> +    WHERE ride_counts.DriverId = rideStats.DriverId;
ride_stats too

2023-05-05 10:49 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/LeaderBoard.hs
> +      Just a -> return a
mb rename `a`?

2023-05-09 06:11 UTC, ashishsingh101 commented
@vikrantkm1997 are we sending current driver info also in the response ?

2023-05-09 12:42 UTC, hkmangla approved these changes

2023-05-09 12:42 UTC, merged