backend/feat/Ambulance Ride Flow
nammayatri/nammayatri pull request #7564
Opened 2024-06-26 10:28 UTC by 0utkarsh

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

<img width="271" alt="Screenshot 2024-06-26 at 3 00 54 PM" src="https://github.com/nammayatri/nammayatri/assets/33424495/b6b3b6b4-35a4-4717-a8fb-463376ef20e5">

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-06-30 09:20 UTC, hkmangla requested changes

2024-06-30 09:20 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Beckn/Status.hs
> +          vehicle <- QVeh.findById ride.driverId >>= fromMaybeM (DriverWithoutVehicle ride.driverId.getId)
Why vehicle is required here? If vehicle is being remove from the driver at time on on-status being called? Or it got changed in b/w?

2024-07-05 09:54 UTC, hkmangla requested changes

2024-07-05 09:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Beckn/OnDemand/Utils/Common.hs
> +mkVehicleAgeTagGroupV2 :: Maybe Double -> Maybe [Spec.TagGroup]
Use Piyush way of adding tags.

2024-07-05 09:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Beckn/Search.hs
> +  (minFareParams, maxFareParams) <- do
Move to Estimate.

2024-07-05 09:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Beckn/Status.hs
> +          vehicle <- QVeh.findById ride.driverId
Store the age in `RideDetails`.

2024-07-05 09:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +      QFP.updateFareParameters fareParams fareParams.id -- this must not be working?
Remove from here.

2024-07-05 09:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +  farePolicy <- getFarePolicyByEstOrQuoteId merchantOpCityId booking.tripCategory booking.vehicleServiceTier booking.area quoteId Nothing (Just (TransactionId (Id booking.transactionId)))
Not needed.

2024-07-05 09:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/DriverOnboarding/VehicleRegistrationCertificate.hs
> +          mYManufacturing = convertTextToDay (rcVerificationResponse.mYManufacturing <> Just "-15"),
add comment for -15

2024-07-05 09:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/LeaderBoard.hs
> +import Domain.Types.Common
remove this.

2024-07-05 09:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Ride.hs
> +    vehicleAge :: Maybe Double,
It should be in `Months` and also move it to RideDetails.

2024-07-05 09:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Types/FarePolicy/FarePolicyAmbulanceDetails.hs
> +    vehicleAge :: Double,
Months.

2024-07-05 09:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Types/Quote.hs
> +    minEstimatedFare :: Maybe HighPrecMoney,
Remove this.

2024-07-05 09:54 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/SendSearchRequestToDrivers/Handle/Internal/SendSearchRequestToDrivers.hs
> +      farePolicy <- getFarePolicyByEstOrQuoteId searchReq.merchantOperatingCityId tripQuoteDetail.tripCategory dpRes.serviceTier searchReq.area searchTry.estimateId Nothing (Just (TransactionId (Id s
Move it to case match and also create a function which will return baseFare

2024-07-08 09:03 UTC, hkmangla requested changes

2024-07-08 09:20 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Ride/EndRide.hs
> +  vehicleAge <-
We fetch `RiderDetails`, not `RideDetails`

2024-07-08 09:20 UTC, 0utkarsh commented on Backend/dev/migrations/rider-app/1281-ambulance.sql
> +INSERT INTO atlas_app.beckn_config(
beckn_config is per vehicle category. Since I have added new category `AMBULANCE`, added it

2024-07-09 08:56 UTC, hkmangla approved these changes

2024-07-09 08:57 UTC, merged