added Drop Down Card
nammayatri/nammayatri pull request #7598
Opened 2024-06-28 13:42 UTC by AyushMittal42

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-06-28 13:56 UTC, MercyQueen requested changes

2024-06-28 13:56 UTC, MercyQueen commented on Frontend/ui-common/src/Components/DropDownCard/View.purs
> +        , visibility if config.open then VISIBLE else GONE
use `boolToVisibility` here.

2024-06-28 13:56 UTC, MercyQueen commented on Frontend/ui-common/src/Components/DropDownCard/View.purs
> +        , imageWithFallback $ if config.open then fetchImage FF_COMMON_ASSET "ny_ic_arrow_up" else fetchImage FF_COMMON_ASSET "ny_ic_arrow_down"
can we use this image also from config.

2024-07-01 06:59 UTC, kavya-shree-s approved these changes

2024-07-01 07:00 UTC, merged

2024-07-01 08:21 UTC, MercyQueen commented on Frontend/ui-common/src/Components/DropDownCard/DropDownCard.purs
> +-- odule Components.BottomDrawerList (module Reexport) where
remove commented code.