backend/enhancement/fix-exotel-call-sync-issues
nammayatri/nammayatri pull request #7654
Opened 2024-07-02 11:35 UTC by vsaimanohar

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [X] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [X] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [X] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [X] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-07-04 10:08 UTC, prashant601 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Tools/Notifications.hs
> +  transporterConfig <- findByMerchantOpCityId merchantOpCityId (Just (DriverId (cast personId))) >>= fromMaybeM (TransporterConfigNotFound merchantOpCityId.getId)
use `notifyDriverOnEvents` instead of creating this new function, also this title and body can be configurable in `merchantPushNotification` table

2024-07-04 10:47 UTC, prashant601 commented on Backend/app/rider-platform/rider-app/Main/src/Tools/Notifications.hs
> +notifyDirectCall ::
same as driver side

2024-07-04 10:49 UTC, prashant601 commented on Backend/dhall-configs/dev/dynamic-offer-driver-app.dhall
>      }
please add scheduler job type in dhall

2024-07-18 09:39 UTC, hkmangla requested changes

2024-07-18 09:39 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Beckn/OnDemand/Transformer/OnUpdate.hs
> +  OU.CallServiceDownBuildReq OU.DCallServiceDownReq {..} -> do
Name it `PhoneCallRequest`

2024-07-18 09:39 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Internal/CallCustomerFCM.hs
> +        Just token -> notifyDriver customer.merchantOperatingCityId FCM.CALL_SERVICE_DOWN "Try Direct Calling Option" "Customer is Trying to Reach You" customer (Just token)
We have a table for FCM title and body.

2024-07-18 09:39 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Internal/CallCustomerFCM.hs
> +        Just token -> notifyDriver customer.merchantOperatingCityId FCM.CALL_SERVICE_DOWN "Try Direct Calling Option" "Customer is Trying to Reach You" customer (Just token)
`merchant_push_notification`

2024-07-18 09:39 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Call.hs
> +            callFromNumber = driver.mobileNumber,
handle alternate number flow.

2024-07-18 09:39 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Call.hs
> +  activeRide <- runInReplica (QRide.getActiveByDriverId driver.id) >>= maybe (throwCallError callSid (RideForDriverNotFound $ getId driver.id) (Just exophone.merchantId.getId) (Just exophone.callServ
Don't fetch CallStatus until you get rideId

2024-07-19 10:32 UTC, hkmangla requested changes

2024-07-19 10:32 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Call.hs
> +  exophone <- CQExophone.findByPhone to >>= fromMaybeM (ExophoneDoesNotExist callTo)
Too much cleaning.

2024-07-19 10:32 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Call.hs
> +        Just _ -> return ()
update CallSId.

2024-07-19 10:32 UTC, hkmangla commented on Backend/dev/migrations/rider-app/1287-add-fcms-to-merchant-push-notification.sql
> +    'PHONE_CALL_REQUEST',
FCM_CHAT_MESSAGE

2024-07-19 10:32 UTC, hkmangla commented on Backend/dev/migrations/dynamic-offer-driver-app/0474-add-new-notification-to-push-notification.sql
> +    'ENGLISH',
translations

2024-07-24 03:46 UTC, hkmangla approved these changes

2024-07-24 03:46 UTC, merged