backend/feature/: #760 added date filter for rideList API for BPP das…
nammayatri/nammayatri pull request #766
Opened 2023-05-03 15:18 UTC by saurav2401

…hboard

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
added date filter for rideList API for BPP dashboard

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-05 10:41 UTC, 0utkarsh requested changes

2023-05-05 10:41 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Queries/Ride.hs
> +        &&. whenJust_ mbTo (\defaultTo -> ride ^. RideCreatedAt >=. val defaultTo)
Should be `<=.`

2023-05-05 10:41 UTC, 0utkarsh commented on Backend/app/provider-platform/static-offer-driver-app/Main/src/Domain/Action/Dashboard/Ride.hs
> +rideList merchantShortId mbLimit mbOffset mbBookingStatus mbReqShortRideId mbCustomerPhone mbDriverPhone mbFareDiff from to = do
We can have `mb` as prefix for these too

2023-05-05 10:41 UTC, 0utkarsh commented on Backend/app/provider-platform/static-offer-driver-app/Main/src/API/Dashboard/Ride.hs
> +rideList merchantShortId mbLimit mbOffset mbBookingStatus mbShortRideId mbCustomerPhone mbFareDiff from to =
same

2023-05-05 10:41 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Dashboard/Ride.hs
> +rideList merchantShortId mbLimit mbOffset mbBookingStatus mbReqShortRideId mbCustomerPhone mbDriverPhone mbFareDiff from to = do
same

2023-05-05 10:41 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/Dashboard/Ride.hs
> +rideList merchantShortId mbLimit mbOffset mbBookingStatus mbShortRideId mbCustomerPhone mbFareDiff from to =
mb

2023-05-05 10:41 UTC, 0utkarsh commented on Backend/app/dashboard/provider-dashboard/src/API/ProviderPlatform/StaticOfferDriver/Ride.hs
> +rideList merchantShortId apiTokenInfo mbLimit mbOffset mbBookingStatus mbShortRideId mbCustomerPhone mbDriverPhone mbFareDiff from to = withFlowHandlerAPI $ do
mb

2023-05-05 10:41 UTC, 0utkarsh commented on Backend/app/dashboard/provider-dashboard/src/API/ProviderPlatform/DynamicOfferDriver/Ride.hs
> +rideList merchantShortId apiTokenInfo mbLimit mbOffset mbBookingStatus mbShortRideId mbCustomerPhone mbDriverPhone mbFareDiff from to = withFlowHandlerAPI $ do
mb

2023-05-17 10:07 UTC, hkmangla approved these changes

2023-05-17 10:09 UTC, merged