[BKN-2806] ARDU reallocations
nammayatri/nammayatri pull request #77
Opened 2023-03-03 14:40 UTC by DonDokidon

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Reallocate ARDU ride on cancellation

### Additional Changes

- [x] This PR modifies the database schema (database migration added)
- [x] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

https://juspay.atlassian.net/browse/BKN-2806

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-03-06 08:26 UTC, pavelzarubin approved these changes

2023-03-21 11:39 UTC, hkmangla requested changes

2023-03-21 11:39 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Environment.hs
> +    searchRepeatLimit :: Int
Let's not add any config in dhall. Move it to TransportConfig.

2023-03-21 11:39 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/Beckn/OnUpdate.hs
> +  merchant <- QMerch.findById booking.merchantId >>= fromMaybeM (MerchantNotFound booking.merchantId.getId)
It is already remove in your last PR, right?

2023-03-21 12:53 UTC, hkmangla requested changes

2023-03-21 12:53 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/Beckn/OnUpdate.hs
> +    QRide.updateStatus ride.id SRide.CANCELLED
Lets make a new type reallocate instead of cancelled in this case.

2023-03-21 22:45 UTC, hkmangla approved these changes

2023-03-21 22:45 UTC, merged