frontend/fix-added estimates stage
nammayatri/nammayatri pull request #7942
Opened 2024-07-19 13:03 UTC by MercyQueen

- Added estimates stage in between rentalScreen and quotes Screen
https://github.com/user-attachments/assets/018a6c97-d0bc-4f6d-a913-0b015f17360e

2024-07-19 13:11 UTC, aryan-13 approved these changes

2024-07-22 07:33 UTC, spravinkumar9952 requested changes

2024-07-22 07:33 UTC, spravinkumar9952 commented on Frontend/ui-customer/src/Screens/SearchLocationFlow/SearchLocationScreen/ComponentConfig.purs
> +
here let and in is not needed. we can directly override the values

autoAnimConfig :: AnimConfig.AnimConfig
autoAnimConfig = AnimConfig.animConfig
        { duration = 400
        , toScaleX = 1.0
        , toScaleY = 1.0
        }

2024-07-22 07:33 UTC, spravinkumar9952 commented on Frontend/ui-customer/src/Screens/SearchLocationFlow/SearchLocationScreen/View.purs
> +              [ text (getString PAY_DRIVER_USING_CASH_OR_UPI)
$

2024-07-22 07:33 UTC, spravinkumar9952 commented on Frontend/ui-customer/src/Screens/SearchLocationFlow/SearchLocationScreen/View.purs
> +    [ id (EHC.getNewIDWithTag "lottieLoaderSearchLocationScreen")
$

2024-07-22 07:33 UTC, spravinkumar9952 commented on Frontend/ui-customer/src/Screens/SearchLocationFlow/SearchLocationScreen/View.purs
> +              , padding (Padding 5 20 0 16)
$

2024-07-22 07:33 UTC, spravinkumar9952 commented on Frontend/ui-customer/src/Screens/SearchLocationFlow/SearchLocationScreen/View.purs
> +        ( \action -> do
can we shadow the action. also the do and pure unit are not necessary.

2024-09-28 01:54 UTC, closed without merging