backend/feat/send_end_otp_sms
nammayatri/nammayatri pull request #7979
Opened 2024-07-23 09:52 UTC by 0utkarsh

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-07-23 11:56 UTC, hkmangla requested changes

2024-07-23 11:56 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/Beckn/Common.hs
> +    DRB.InterCityDetails details -> unless (isNothing details.otpCode) $ sendRideEndOTPMessage "Rental"
Rental or intercity?

2024-07-23 11:56 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/Beckn/Common.hs
> +      case booking.specialLocationTag of
Why only for special location?

2024-07-23 13:05 UTC, 0utkarsh commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/Beckn/Common.hs
> +      case booking.specialLocationTag of
We don't send SMS in other cases

2024-07-26 10:45 UTC, hkmangla approved these changes

2024-07-26 10:45 UTC, merged