backend/fix: book any fix for auto assign false
nammayatri/nammayatri pull request #7994
Opened 2024-07-24 12:54 UTC by chakri642

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-07-24 13:31 UTC, khuzema786 approved these changes

2024-07-24 13:46 UTC, hkmangla requested changes

2024-07-24 13:46 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Storage/Queries/QuoteExtra.hs
> +  allQuotes <- findAllWithKV [Se.Is BeamQ.requestId $ Se.Eq srId]
add status check too.

2024-07-25 10:01 UTC, hkmangla approved these changes

2024-07-25 10:01 UTC, merged