#526:replicated_firebase_logging_system
nammayatri/nammayatri pull request #807
Opened 2023-05-08 14:00 UTC by SanskarGubreley

## Type of Change

- [ ] Bugfix
- [ x] New feature
- [ x] Enhancement
- [ x] Refactoring
- [ ] Dependency updates

## Description

Replicated the logging functions 

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-08 14:23 UTC, ks-shree commented
Please follow contribution guidelines in commit message and PR title.

2023-05-08 14:24 UTC, ks-shree commented on Frontend/ui-common/src/Engineering/Helpers/Commons.purs
> +import Effect.Aff (Aff, makeAff, nonCanceler, try, launchAff_)
@SanskarGubreley Can you check imports if not used

2023-05-09 03:51 UTC, khuzema786 commented
Also, why is my commit being reflecting in your PR. Can you correct it to have only your 1 commit.

2023-05-09 12:41 UTC, ks-shree commented
@SanskarGubreley Why your PR has all other changes ? Can you rebase and squash into one single commit

2023-05-09 12:42 UTC, ks-shree requested changes
Rebase and squash into single commit

2023-05-31 10:21 UTC, closed without merging