backend/feat/driver cancellation rate rolling window
nammayatri/nammayatri pull request #8071
Opened 2024-07-30 15:41 UTC by shreyaxh

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-08-02 10:34 UTC, enigma-commits submitted a review, later dismissed

2024-08-02 10:34 UTC, enigma-commits commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/CancellationRate.hs
> +{-# OPTIONS_GHC -Wno-deprecations #-}
![image](https://github.com/user-attachments/assets/8ac19ff4-4b46-4685-8ae8-6597c8cc526e)

2024-08-02 10:42 UTC, piyushKumar-1 requested changes

2024-08-02 10:42 UTC, piyushKumar-1 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/CancellationRate.hs
> +  merchantConfig <- CQTC.getTransporterConfigFromDB mocId >>= fromMaybeM (TransporterConfigNotFound mocId.getId)
use getTransporterConfig from CAC files.

2024-08-02 10:42 UTC, piyushKumar-1 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/CancellationRate.hs
> +getAssignedCount windowSize driverId = fmap catMaybes . Redis.withCrossAppRedis $ SWC.getCurrentWindowValuesUptoLast windowSize (mkRideAssignedKey driverId.getId) (SWC.SlidingWindowOptions 15 SWC.Day
use `getCurrentWindowCount` function.

2024-08-02 10:42 UTC, piyushKumar-1 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/CancellationRate.hs
> +getWindowSize :: (MonadFlow m, EsqDBFlow m r, CacheFlow m r) => Id DMOC.MerchantOperatingCity -> m Integer
not required i guess

2024-08-02 10:42 UTC, piyushKumar-1 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/CancellationRate.hs
> +getCancellationCount windowSize driverId = fmap catMaybes . Redis.withCrossAppRedis $ SWC.getCurrentWindowValuesUptoLast windowSize (mkRideCancelledKey driverId.getId) (SWC.SlidingWindowOptions 15 SW
don't hard code these window values, use the same `windowSize` thing instead of 15

2024-08-02 10:42 UTC, piyushKumar-1 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/CancellationRate.hs
> +mkRideAssignedKey driverId = "driver-offer:CancellationRate:ride-assigned-to-driverId:" <> driverId
make these keys small, maybe abbreviate

2024-08-02 10:42 UTC, piyushKumar-1 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Ride.hs
>      DS.driverScoreEventHandler booking.merchantOperatingCityId DST.OnNewRideAssigned {merchantId = merchantId, driverId = ride.driverId, currency = ride.currency, distanceUnit = booking.distanceUnit}
do this inside `driverScoreEventHandler`

2024-08-08 11:21 UTC, piyushKumar-1 submitted a review, later dismissed

2024-08-08 13:33 UTC, sidsethu approved these changes

2024-08-08 13:33 UTC, merged