backend/ench : allowed blocked users to login and added extra option …
nammayatri/nammayatri pull request #8098
Opened 2024-07-31 15:01 UTC by VD321

…filtering logic

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [X] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
1. Changed auth logic to allow blocked users to login.
2. Added allowedRideStatuses field to IssueCategory
3. Added IssueOption filtering based on RideStatuses.
4. Filtered out Fare Breakup option in case if estimated fare and actual fare is same.
5. Dashboard api changes to allow addition of new fields.

### Additional Changes

- [X] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [X] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [X] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [X] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-09-16 07:48 UTC, hkmangla requested changes

2024-09-16 07:48 UTC, hkmangla commented on Backend/lib/shared-services/src/IssueManagement/Common/Dashboard/Issue.hs
> +-- import Options.Applicative (Parser)
remove this.

2024-09-16 07:48 UTC, hkmangla commented on Backend/lib/shared-services/src/IssueManagement/Common.hs
> +data RideStatus = R_NEW | R_INPROGRESS | R_COMPLETED | R_CANCELLED | R_UPCOMING
check if there is any template for the same.

2024-09-16 14:58 UTC, hkmangla submitted a review, later dismissed

2024-09-26 15:02 UTC, NikithShetty approved these changes

2024-09-26 15:02 UTC, merged