backend/feat integrate cac
nammayatri/nammayatri pull request #8168
Opened 2024-08-06 13:34 UTC by Jayanth-Parthsarathy

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [x] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-08-07 04:27 UTC, enigma-commits submitted a review, later dismissed

2024-08-07 13:30 UTC, enigma-commits approved these changes

2024-08-26 07:25 UTC, enigma-commits requested changes

2024-08-26 07:25 UTC, enigma-commits commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/spec/API/Cac.yaml
> + # POST /driver/getUiConfigs
can we remove this line

2024-08-26 07:43 UTC, hkmangla approved these changes

2024-08-29 09:36 UTC, piyushKumar-1 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +  frntndfgs <- if useCACConfig then getFrontendConfigs merchantOpCityId toss tnant' context' else return $ Just DAKM.empty
do this string conversion inside the `getFrontendConfigs` function.

2024-08-29 10:42 UTC, merged