backend/enh: stripe ineg in ride flow
nammayatri/nammayatri pull request #8252
Opened 2024-08-14 08:28 UTC by chakri642

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-08-20 09:32 UTC, DwivediAman-exe submitted a review, later dismissed

2024-08-23 10:49 UTC, NikithShetty requested changes

2024-08-23 10:49 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/UI/RidePayment.hs
> -    customerPaymentId <- person.customerPaymentId & fromMaybeM (PersonFieldNotPresent "customerPaymentId")
if the tip is added after the scheduler run, then tip should be charged separately

2024-08-23 10:49 UTC, NikithShetty commented on Backend/lib/payment/src/Lib/Payment/Domain/Action.hs
> +  -- let cardFixedCharges = HighPrecMoney 0.3 -- 30 cents, we have to fix it later properly
Remove commented out code

2024-09-04 11:50 UTC, NikithShetty requested changes

2024-09-04 11:50 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/UI/RidePayment.hs
> +  Redis.withWaitOnLockRedisWithExpiry paymentJobExecLockKey 60 60 $ do
Update to 10, 20 durations

2024-09-04 11:50 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/SharedLogic/Scheduler/Jobs/ExecutePaymentIntent.hs
> +    paymentJobExecLockKey :: Text
move this to common place

2024-09-04 11:50 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/UI/RidePayment.hs
> +        let cardPercentageCharges = 0.029 -- 2.9%
Make application fee computation common

2024-09-04 11:50 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/SharedLogic/Scheduler/Jobs/ExecutePaymentIntent.hs
> +sendExecutePaymentIntent Job {id, jobInfo} = withLogTag ("JobId-" <> id.getId) do
rename to `executePaymentIntentJob`

2024-09-04 11:50 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/SharedLogic/Scheduler/Jobs/ExecutePaymentIntent.hs
> +    void $ SPayment.chargePaymentIntent booking.merchantId booking.merchantOperatingCityId paymentIntentResp.paymentIntentId
Update `chargePaymentIntent` to return charge status and then update the payment status accordingly

2024-09-04 11:50 UTC, NikithShetty commented on Backend/app/rider-platform/rider-app/Main/src/SharedLogic/Scheduler/Jobs/ExecutePaymentIntent.hs
> +  void $ SPayment.makeCancellationPayment booking.merchantId booking.merchantOperatingCityId order.paymentServiceOrderId cancellationAmount.amount
Need to check `makeCancellationPayment` status to update payment status

2024-09-27 10:39 UTC, NikithShetty approved these changes

2024-09-27 10:39 UTC, merged