Frontend/new-screen/Driver profile
nammayatri/nammayatri pull request #8265
Opened 2024-08-14 12:57 UTC by ROHIT-43

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

I have added a new driver profile screen for both user and driver. This screen made in ui-common. 

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

Manually

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-08-23 12:23 UTC, kavya-shree-s requested changes

2024-08-23 12:23 UTC, kavya-shree-s commented on Frontend/ui-common/src/Engineering/Helpers/Commons.js
undo formating

2024-08-23 12:23 UTC, kavya-shree-s commented on Frontend/ui-common/src/Font/Style.purs
> +body32 ::  LazyCheck ->  forall properties. (Array (Prop properties))
Remove

2024-08-23 12:23 UTC, kavya-shree-s commented on Frontend/ui-common/src/Screens/DriverProfileScreen/Controller.purs
> +  let _ = spy "getImage state" state
Remove spy in all the files

2024-08-23 12:23 UTC, kavya-shree-s commented on Frontend/ui-common/src/Screens/DriverProfileScreen/ScreenData.purs
> +driverReview1 :: DriverReview
Remove all dummy name have keep empty string

2024-08-23 12:23 UTC, kavya-shree-s commented on Frontend/ui-common/src/Screens/DriverProfileScreen/View.purs
> +        Left _ -> void $ pure $ JB.toast "Not available at this moment"
use getString

2024-08-23 12:23 UTC, kavya-shree-s commented on Frontend/ui-common/src/Screens/DriverProfileScreen/View.purs
> +                        , margin $ Margin 0 0 5 0
marginRight

2024-08-29 09:20 UTC, Vignesh-772 commented on Frontend/ui-common/src/Screens/DriverProfileScreen/View.purs
> +            , fontStyle $ FontStyle.regular LanguageStyle
Append fontStyles instead of hardcoded.

2024-08-29 09:21 UTC, Vignesh-772 commented on Frontend/ui-common/src/Screens/DriverProfileScreen/View.purs
> +                , text $ "🚗    "<> show (fromMaybe 0 state.data.drivingSince) <>" Yrs of Driving"
Handle translations.

2024-08-29 09:48 UTC, Vignesh-772 commented on Frontend/ui-common/src/Services/Backend.purs
> +module Services.Common.Backend where
Common Backend file is not required. Keep these functions in Driver and customer folders

2024-11-06 01:53 UTC, closed without merging