backend/fix : Lo Feedback fix hotpush
nammayatri/nammayatri pull request #8532
Opened 2024-09-09 13:37 UTC by dushyant-2002

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-09-09 15:00 UTC, rupakkorde requested changes

2024-09-09 15:00 UTC, rupakkorde commented on Backend/lib/shared-services/src/IssueManagement/Domain/Action/UI/Issue.hs
> +  let isLOFeedback = (identifier == CUSTOMER) && not (T.null description) && maybe False (any (\word -> T.toLower word `T.isInfixOf` T.toLower description)) (config.sensitiveWords)
Either we can keep 'sensitiveWords' as Not Null in domain type and maybe in beam.
Or
If you're using it here only then pass sensitive words as empty list to checkSensitiveWords function so you don't have to write "maybe False" in both things

2024-09-11 16:11 UTC, khuzema786 approved these changes

2024-09-11 18:40 UTC, khuzema786 approved these changes

2024-09-11 18:40 UTC, merged