frontend/feat: Ambulance Flow Changes
nammayatri/nammayatri pull request #8595
Opened 2024-09-13 08:01 UTC by Kuldeepkumawat144

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-09-16 12:28 UTC, ashishsingh101 requested changes

2024-09-16 12:28 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Flow.purs
> +                _ = spy "FarePoductType is" $ state.data.fareProductType
remove spy

2024-09-16 12:28 UTC, ashishsingh101 commented on Frontend/ui-customer/src/RemoteConfigs/Types.purs
> +data ServiceType = INSTANT | TRANSIT | INTERCITY | RENTAL | DELIVERY | INTERCITY_BUS | AMBULANCE_
rename it to `AMBULANCE_SERVICE`

2024-09-16 12:28 UTC, ashishsingh101 commented on Frontend/ui-customer/src/RemoteConfigs/Utils.purs
> +  ambulanceVentilator : [0, 20, 30, 0],
keep it empty for ambulance

2024-09-16 12:28 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Screens/CustomerUtils/InvoiceScreen/View.purs
> +            ambulanceWaitingCharges
use Fareproduct type here

2024-09-16 12:28 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Screens/CustomerUtils/MyRidesScreen/Controller.purs
> +    ambulanceWaitingCharges = if rideType == FPT.RENTAL then cityConfig.rentalWaitingChargeConfig.ambulance else cityConfig.waitingChargeConfig.ambulance
please check this case again

2024-09-16 12:28 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Screens/CustomerUtils/RideSelectionScreen/Controller.purs
> +import Helpers.Utils (FetchImageFrom(..), fetchImage, isHaveFare, setEnabled, setRefreshing, withinTimeRange,fetchVehicleVariant)
remove unused imports, from other places as well

2024-09-16 12:28 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Screens/CustomerUtils/TripDetailsScreen/View.purs
> +              [ textFromHtml if state.data.vehicleVariant == Just ST.AMBULANCE_VENTILATOR then "Ventilator" else rideTypeWithAc
add translations

2024-09-16 12:28 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/Controller.purs
> +    quoteList = spy "debug quotes quoteList" $ filter (\item -> item.providerType == ONUS || (item.providerType == OFFUS && state.data.currentCityConfig.iopConfig.enable)) allQuoteListWithUpdatedInde
remove logs

2024-09-16 18:59 UTC, slow-codex commented on Frontend/ui-driver/src/Resource/Constants.purs
> +    false,Just true,"Ventilator" ->  "Ventilator"
`false, Just _, "Ventilator" -> "Ventilator"`
We can reduce the  case matchings of such cases

2024-09-16 18:59 UTC, slow-codex commented on Frontend/ui-driver/src/Helpers/Utils.purs
> +        YATRISATHI -> case spy "varient is" variant of
We must not use specific `YATRISATHI` checks in such cases because after the sync with main these have been removed already.

2024-09-16 18:59 UTC, slow-codex commented on Frontend/ui-customer/src/Screens/RideBookingFlow/HomeScreen/View.purs
> +      firstName = fromMaybe "Yatri " (head (DS.split (DS.Pattern " ") if appName == "Yatri Sathi" then "More" else appName))
Can we update in config instead of doing a hard coded check on `"Yatri Sathi"`

2024-09-16 18:59 UTC, slow-codex commented on Frontend/ui-customer/src/Services/Backend.purs
> +        { "contents" : AmbulanceSearchRequest
Can we unify this with `makeRideSearchReq` as this is totally similar just a check on `FareproductType`

2024-09-18 08:22 UTC, ashishsingh101 commented on Frontend/ui-driver/src/Components/RideActionModal/View.purs
> +        tierImage = if config.serviceTierAndAC == "Ventilator" then "ny_ic_ventilator_blue" else if config.acRide == Maybe.Just true then "ny_ic_ac_white" else if config.acRide == Maybe.Just false th
use vehicle variant here

2024-09-20 09:50 UTC, Kuldeepkumawat144 commented on Frontend/ui-customer/src/RemoteConfigs/Utils.purs
> +  suvPlus : [0, 20, 30, 0],
No removed 5 by mistake

2024-11-30 02:00 UTC, closed without merging