backend/enhancement : Added rideAssigned FCM and reminder for schedul…
nammayatri/nammayatri pull request #8644
Opened 2024-09-18 09:49 UTC by dushyant-2002

…edRides

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

<img width="590" alt="Screenshot 2024-09-18 at 3 19 00 PM" src="https://github.com/user-attachments/assets/17f30c05-7484-47c0-8d8c-731db3407c59">

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-09-18 10:27 UTC, aayushagarwal2001 requested changes

2024-09-18 10:27 UTC, aayushagarwal2001 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/ScheduledRides/ScheduledRideAssignedOnUpdate.hs
> +              let isAllJust = (maybe False (\t -> isJust (t.avgSpeedOfVehicle)) mbtransporterConfig) && isJust driverInfo.latestScheduledBooking
we can use `mbtransporterConfig >>= (.avgSpeedOfVehicle) `
and` let isAllJust = any isNothing [driverInfo.latestScheduledBooking, mbtransporterConfig >>= (.avgSpeedOfVehicle) ]`

2024-09-23 20:43 UTC, DwivediAman-exe requested changes

2024-09-23 20:43 UTC, DwivediAman-exe commented on Backend/app/rider-platform/rider-app/Main/src/Tools/Notifications.hs
> +      -- <XYZ> will be the driver for your scheduled trip starting at hh:mm , dd/mmm
remove comment.

2024-09-23 20:43 UTC, DwivediAman-exe commented on Backend/app/rider-platform/rider-app/Main/src/SharedLogic/Scheduler/Jobs/ScheduledRidePopupToRider.hs
> +  booking <- QBooking.findById bookingId >>= fromMaybeM (BookingDoesNotExist bookingId.getId)
run query in replica.

2024-09-24 09:47 UTC, khuzema786 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/ScheduledRides/ScheduledRideAssignedOnUpdate.hs
> +                  let cReason = "Ride is Reallocated transporterConfig  Or driverInfo.latestScheduledBooking is Nothing"
Fix this text, it can be an error message in Tools.Error

2024-09-24 09:47 UTC, khuzema786 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/ScheduledRides/ScheduledRideAssignedOnUpdate.hs
> +      let transporterConfig = fromJust mbtransporterConfig
Avoid using `fromJust`

2024-09-24 09:48 UTC, khuzema786 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/ScheduledRides/ScheduledRideAssignedOnUpdate.hs
> +          scheduledPickupTime = fromJust driverInfo.latestScheduledBooking
Remove all `fromJust`

2024-09-24 09:53 UTC, khuzema786 approved these changes

2024-09-24 09:54 UTC, merged