Frontend/Enhancement/Truck-onBoarding-Flow
nammayatri/nammayatri pull request #8681
Opened 2024-09-21 21:39 UTC by Kuldeepkumawat144

## Type of Change

- [ ] Bugfix
- [X ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-09-25 13:46 UTC, Rohit4997 requested changes

2024-09-25 13:46 UTC, Rohit4997 commented on Frontend/android-native/app/src/driver/jatriSaathiDriver/res/drawable/ny_ic_truck_not_supported.png
This asset can be driver/common

2024-09-25 13:46 UTC, Rohit4997 commented on Frontend/android-native/app/src/driver/jatriSaathiDriver/res/drawable/ny_ic_truck_side.png
Please put this asset in driver/common, Else for other apps It will show empty and try to keep assets common as much as possible

2024-09-25 17:29 UTC, Rohit4997 submitted a review, later dismissed

2024-09-26 05:52 UTC, slow-codex approved these changes

2024-11-06 10:18 UTC, slow-codex approved these changes

2024-11-06 10:20 UTC, prakharritik approved these changes

2024-11-07 11:38 UTC, Vignesh-772 approved these changes

2024-11-07 12:07 UTC, merged