Backend/enh/refund-registration-amount-for-d2r
nammayatri/nammayatri pull request #8691
Opened 2024-09-23 11:12 UTC by prashant601

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-09-23 20:28 UTC, DwivediAman-exe requested changes

2024-09-23 20:28 UTC, DwivediAman-exe commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Payout.hs
> +      driverInfo <- QDriverInfo.findById (Id driverId) >>= fromMaybeM DriverInfoNotFound
Please run this query in replica, also do the same for other queries.

2024-09-24 09:40 UTC, DwivediAman-exe submitted a review, later dismissed

2024-09-24 09:57 UTC, khuzema786 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Dashboard/Management/Payout.hs
> +  mapM_ deletePayoutVpaAndStatus req.driverIds
If more drivers then can be changed to Bulk delete query later

2024-09-24 10:00 UTC, khuzema786 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Allocator/Jobs/Payout/DriverReferralPayout.hs
> +          mbDriverFee <- QDF.findLatestByFeeTypeAndStatusWithServiceName DF.PAYOUT_REGISTRATION [DF.CLEARED] driverId DPlan.YATRI_SUBSCRIPTION
to be improved

2024-09-25 12:11 UTC, VD321 approved these changes

2024-09-26 08:57 UTC, hkmangla approved these changes

2024-10-04 10:38 UTC, khuzema786 approved these changes

2024-10-04 10:38 UTC, merged