backend:fix/edit-destination-simplified
nammayatri/nammayatri pull request #8818
Opened 2024-10-01 13:56 UTC by vijaygupta18

## Type of Change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results
<img width="813" alt="image" src="https://github.com/user-attachments/assets/4ef17c4a-ffb6-402f-9b4b-0f34459e94a0">

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-10-03 10:14 UTC, hkmangla requested changes

2024-10-03 10:14 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Beckn/Update.hs
> +                  (failed', snappedLatLongs') <- snapToRoad latlons merchantId merchanOperatingCityId
snapToRoadWithFallback

2024-10-04 12:07 UTC, RitikaHanish commented on Backend/lib/location-updates/src/Lib/LocationUpdates/Internal.hs
> +  Hedis.expire key 172800 -- 2 days
1 day is enough

2024-10-04 14:11 UTC, piyushKumar-1 approved these changes

2024-10-04 14:16 UTC, merged