backend/dashboard/partial_cash_collection_and_exemption
nammayatri/nammayatri pull request #8858
Opened 2024-10-03 14:35 UTC by AarushiSharma05

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-10-04 07:13 UTC, aayushagarwal2001 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/Dashboard/Management/Subscription.hs
> +  let abc =
can we rename the variable to something more contextual

2024-10-04 07:22 UTC, aayushagarwal2001 requested changes

2024-10-04 07:22 UTC, aayushagarwal2001 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/Dashboard/Management/Subscription.hs
> +  _x <- Driver.clearDriverDues (cast driverId, m.id, mOCityId) req.serviceName (Just abc) Nothing
same here

2024-10-07 09:12 UTC, closed without merging

2024-10-07 09:21 UTC, aayushagarwal2001 requested changes

2024-10-07 09:21 UTC, aayushagarwal2001 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/Dashboard/Management/Subscription.hs
> +            messageKey = Nothing
pass key here WHATSAPP_MANUAL_PAYMENT

2024-10-07 09:25 UTC, AarushiSharma05 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/Dashboard/Management/Subscription.hs
> +  _resp <- Driver.clearDriverDues (cast driverId, m.id, mOCityId) req.serviceName (Just dataClearManualSelectedDues) Nothing
It was throwing error.

2024-10-07 09:56 UTC, aayushagarwal2001 submitted a review, later dismissed

2024-10-07 13:00 UTC, NikithShetty commented on Backend/dev/migrations-read-only/provider-dashboard/API_RideBooking_Driver.sql
this will be removed after `migrate` key in yaml

2024-10-17 13:04 UTC, NikithShetty requested changes

2024-10-17 13:04 UTC, NikithShetty commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/API/Dashboard/Management/Subscription.hs
> +    serviceName :: DPlan.ServiceNames
follow the api format as before. Move `serviceName` to url

2024-10-17 14:24 UTC, NikithShetty approved these changes