frontend-CugFix-RideCompleted
nammayatri/nammayatri pull request #8943
Opened 2024-10-08 16:51 UTC by ROHIT-43

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

Added a crousel on Ride Completed Screen and Fixed some bugs

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

Manually

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-10-08 17:01 UTC, witcher-shailesh approved these changes

2024-10-09 06:17 UTC, prakharritik commented on Frontend/ui-customer/src/Screens/RideBookingFlow/RiderRideCompletedCard/View.purs
> +      , customerIssueCards : spy "issueReportBannerConfigs" $ issueReportBannerConfigs state
remove spy

2024-10-09 06:25 UTC, prakharritik requested changes

2024-10-09 06:25 UTC, prakharritik commented on Frontend/ui-customer/src/Services/Backend.purs
> +makeFeedBackReqs rating rideId feedback favDriver audio nightSafety wasOfferedAssistance = FeedbackReq
Looks like we are still not using this, we are passing nothing in the request

2024-10-09 06:25 UTC, prakharritik commented on Frontend/ui-driver/src/Resource/Localizable/BN.purs
> +        WHY_NY variant -> "আমি কেন "<> (if variant == "AutoCategory" then getBN AUTO else getBN CAB) <>" চালানোর সিদ্ধান্ত নিলাম?"
Lets not do this like this, we can make a function to get variant name and pass it wherever we are using this constructor. Other cases like bike ambulance are also there

2024-10-09 06:25 UTC, prakharritik commented on Frontend/ui-customer/src/Screens/RideBookingFlow/RiderRideCompletedCard/ComponentConfig.purs
> +issueReportBannersTransformer  :: Array CustomerIssueCard -> Array (Record IssueReportBannerProps)
Can you confirm if these functions are present at two places? If so We can remove from other or use that only

2024-10-09 13:49 UTC, prakharritik approved these changes

2024-10-11 06:50 UTC, prakharritik commented on Frontend/ui-customer/src/Screens/RideBookingFlow/RiderRideCompletedCard/View.purs
> +    _ = spy "Here with length == 1" config
Remove spy

2024-10-11 11:17 UTC, prakharritik approved these changes

2024-10-11 11:29 UTC, merged