frontend/feat/enabled_events
nammayatri/nammayatri pull request #8964
Opened 2024-10-09 15:48 UTC by RahulGupta0706

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-10-09 16:10 UTC, slow-codex requested changes

2024-10-09 16:12 UTC, slow-codex requested changes

2024-10-09 16:12 UTC, slow-codex commented on Frontend/ui-driver/src/Flow.purs
> +                        (Vehicle value) -> case value.category of
Can we remove this many case matches and use fromMaybe like:
`let (Vehicle linkedVehicle) = fromMaybe dummyVehicleObject getDriverInfoResp.linkedVehicle`

2024-10-11 13:16 UTC, slow-codex approved these changes

2024-10-14 05:15 UTC, ashishsingh101 approved these changes

2024-10-14 05:16 UTC, merged