backend/fix/#870 update response of flowstatus api
nammayatri/nammayatri pull request #897
Opened 2023-05-16 13:19 UTC by kapilJhalani1

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-17 05:20 UTC, roman-bodavskiy commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/Beckn/OnUpdate.hs
> +      QPFS.updateStatus _booking.riderId DPFS.RIDE_PICKUP {rideId = ride.id, bookingId = _booking.id, trackingUrl = Nothing, otp = ride.otp, vehicleNumber = ride.vehicleNumber, fromLocation = Maps.ge
we can use `arrivalTime` from `DriverArrivedReq`

2023-05-17 05:20 UTC, roman-bodavskiy approved these changes

2023-05-17 10:13 UTC, hkmangla requested changes

2023-05-17 10:13 UTC, hkmangla commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/Beckn/OnUpdate.hs
> +      QPFS.updateStatus _booking.riderId DPFS.RIDE_PICKUP {rideId = ride.id, bookingId = _booking.id, trackingUrl = Nothing, otp = ride.otp, vehicleNumber = ride.vehicleNumber, fromLocation = Maps.ge
Lets create a new status for DRIVER_ARRIVED.

2023-06-01 09:22 UTC, vsaimanohar approved these changes

2023-06-27 07:30 UTC, hkmangla approved these changes

2023-06-27 07:55 UTC, merged