Backend/feat:new-operating-city-configs-from-base-city
nammayatri/nammayatri pull request #8999
Opened 2024-10-11 11:30 UTC by blaze-198

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

While copying configs from the base operating city to the merchant's operating city, certain issues were identified on both the BAP and BPP sides:

BAP: The merchant service config, Exophone config, and Beckn config were not being copied for the new merchant operating city.
BPP: The merchant push notification config was not being copied for the new merchant operating city.

I have fixed this issue and additionally, I have made the API idempotent. This ensures that if any part of the process fails or some configurations aren't copied due to an error, the issue can be fixed, and the API can be retriggered to successfully copy the remaining configurations without duplicating previously copied ones.

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-10-11 18:22 UTC, khuzema786 approved these changes

2024-10-16 22:49 UTC, khuzema786 requested changes

2024-10-16 22:49 UTC, khuzema786 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Dashboard/Management/Merchant.hs
> +  mbNewOperatingCity <-
This can be Pure with let binding

2024-10-16 22:49 UTC, khuzema786 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Dashboard/Management/Merchant.hs
> +    try @_ @SomeException (CGHC.findByMerchantOpCityId newMerchantOperatingCityId Nothing) >>= \case
why is try required ?

2024-10-17 08:58 UTC, blaze-198 commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Dashboard/Management/Merchant.hs
> +  mbNewOperatingCity <-
Done with the suggested changes

2024-10-17 20:09 UTC, khuzema786 approved these changes

2024-10-17 20:09 UTC, merged