Frontend/event-enabled/driver-online-mode
nammayatri/nammayatri pull request #9032
Opened 2024-10-15 10:20 UTC by RahulGupta0706

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-10-17 11:04 UTC, ashishsingh101 requested changes

2024-10-17 11:04 UTC, ashishsingh101 commented on Frontend/ui-driver/src/Flow.purs
> +          firstTimeOnboardingStatus = getValueToLocalStore FIRST_TIME_ONBOARDING
please handle this using a global state instead of local storage

2024-10-21 12:58 UTC, ashishsingh101 approved these changes

2024-10-21 13:03 UTC, slow-codex approved these changes

2024-10-21 13:15 UTC, merged