frontend/#9065/select contact screen
nammayatri/nammayatri pull request #9066
Opened 2024-10-17 10:39 UTC by ashishsingh101

## Type of Change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-10-17 12:03 UTC, max-keviv commented
@ashishsingh101, is this screen support available only on the customer's side? If so, can we make it common between the driver and the customer?

2024-10-17 12:16 UTC, max-keviv requested changes

2024-10-17 12:16 UTC, max-keviv commented on Frontend/ui-customer/src/Screens/SelectContactsFlow/SelectContactsScreen/View.purs
> +showEmergencyContact :: forall w. PrestoList.ListItem -> (Action -> Effect Unit) -> SelectContactsScreenState -> PrestoDOM (Effect Unit) w
@ashishsingh101 let's not hardcode the emergency words here

2024-10-17 12:16 UTC, max-keviv commented on Frontend/ui-customer/src/Screens/SelectContactsFlow/SelectContactsScreen/ComponentConfig.purs
> +          , accessibilityHint = (if enableBtn then (getString CONFIRM_EMERGENCY_CONTACTS) else (getString SELECT_CONTACTS)) <> " : Button"
lets not hard code emergency strings too

2024-10-17 12:35 UTC, max-keviv commented on Frontend/ui-customer/src/Screens/SelectContactsFlow/SelectContactsScreen/ComponentConfig.purs
> +          , accessibilityHint = if state.props.showContacts then (show (length state.data.contacts) <> " Of " <> (show state.data.contactSelectionLimit) <> " " <> (getString CONTACTS_SELECTED)) else
lets not hardcode Emergency

2024-10-18 07:34 UTC, max-keviv commented on Frontend/ui-customer/src/Screens/ParcelDeliveryFlow/ParcelDeliveryScreen/Controller.purs
@ashishsingh101 please have this line added in the controller as there is an edge case when
someone selects a contact and edit the text and then again selects the same contact then the updated value is not getting rendered
`
eval (DeliveryDetailAction (PopUpModalController.PersonName PrimaryEditTextController.TextImageClicked)) state = do
  let updatedState = if state.data.currentStage == ST.SENDER_DETAILS then state {data { senderDetails { name = state.props.editDetails.name, phone = state.props.editDetails.phone}}} else state {data { receiverDetails { name = state.props.editDetails.name, phone = state.props.editDetails.phone}}}
  updateAndExit updatedState $ GoToSelectContact updatedState

eval (DeliveryDetailAction (PopUpModalController.PersonMobile PrimaryEditTextController.TextImageClicked)) state = do
  let updatedState = if state.data.currentStage == ST.SENDER_DETAILS then state {data { senderDetails { name = state.props.editDetails.name, phone = state.props.editDetails.phone}}} else state {data { receiverDetails { name = state.props.editDetails.name, phone = state.props.editDetails.phone}}}
  updateAndExit updatedState $ GoToSelectContact updatedState
`

2024-10-21 07:36 UTC, max-keviv approved these changes

2024-10-21 07:59 UTC, slow-codex submitted a review, later dismissed

2024-10-21 11:10 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/SelectContactsFlow/SelectContactsScreen/Controller.purs
> +startsWith :: String -> String -> Boolean
this function is already present in mobilityPrelude can we use it from there.

2024-10-21 11:16 UTC, MercyQueen commented on Frontend/ui-customer/src/Screens/ParcelDeliveryFlow/ParcelDeliveryScreen/Controller.purs
> +  let updatedState = if state.data.currentStage == ST.SENDER_DETAILS then state {data { senderDetails { name = state.props.editDetails.name, phone = state.props.editDetails.phone}}} else state {data
create a common action and redirect to that instead of repeating twice.

2024-10-21 12:39 UTC, MercyQueen approved these changes

2024-10-21 12:50 UTC, Vignesh-772 approved these changes

2024-10-21 12:50 UTC, merged