Backend/enh/coins-on-vehicle-category-level
nammayatri/nammayatri pull request #9274
Opened 2024-11-08 18:27 UTC by DwivediAman-exe

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-11-16 17:53 UTC, hkmangla requested changes

2024-11-16 17:53 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Dashboard/Management/DriverCoins.hs
> +      vehCategory <-
In most the places in data vehicleCategory is nothing, so instead of that using vehicleVariant convert it into vehicleCategory

2024-11-16 17:53 UTC, hkmangla commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/CachedQueries/CoinsConfig.hs
> +    Nothing -> cacheCoinConfig eventType merchantOpCityId vehicleCategory /=<< Queries.fetchFunctionsOnEventbasis eventType merchantId merchantOpCityId (Just vehicleCategory)
What if data based on vehicleCategory is not available e.g. older tables will not have vehicleCategory.

2024-12-11 09:06 UTC, RitikaHanish commented on flake.lock
> +        "narHash": "sha256-Bgu7oCSexoIWqojwtKCFC8IYdt0nL1dEN129LHwmPTQ=",
update It

2024-12-11 09:53 UTC, merged