Frontend/feat/ys ticket operational changes
nammayatri/nammayatri pull request #9291
Opened 2024-11-12 14:25 UTC by max-keviv

## Type of Change

- [x] Enhancement

## Description
added Operational Date support for yatri saathi ticketing service 

## Screenshot of test results

2024-11-13 05:05 UTC, slow-codex submitted a review, later dismissed

2024-11-13 05:05 UTC, slow-codex commented on Frontend/ui-customer/src/Screens/TicketBookingFlow/PlaceDetails/View.purs
> +    else if (state.props.currentStage == ST.ChooseTicketStage) && (not $ isVisitDateWithinOperationalDate state) then (headerBannerView push state ("The selected date is outside the available booking
@max-keviv Should we add translations here? Previously also no one added any translations for these texts.

2024-11-13 07:22 UTC, ashishsingh101 requested changes

2024-11-13 07:22 UTC, ashishsingh101 commented on Frontend/ui-customer/src/Services/Accessor.purs
> +_operationalDate = lens (unwrap >>> _.operationalDate) (\oldRec newVal -> wrap ((unwrap oldRec) { operationalDate = newVal }))
we can remove it and its import in other modules if not using

2024-11-14 12:28 UTC, ashishsingh101 approved these changes

2024-11-14 12:44 UTC, slow-codex approved these changes

2024-11-14 13:07 UTC, merged