backend/enhancement : Added Scheduled bookings in redis
nammayatri/nammayatri pull request #9374
Opened 2024-11-19 18:47 UTC by dushyant-2002

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-11-25 22:27 UTC, 0utkarsh requested changes

2024-11-25 22:27 UTC, 0utkarsh commented on Backend/dev/migrations-read-only/dynamic-offer-driver-app/transporter_config.sql
> +ALTER TABLE atlas_driver_offer_bpp.transporter_config ADD COLUMN disable_list_scheduled_booking_api boolean  default false;
Make this true now?

2024-11-25 22:27 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Booking.hs
> +secondsRemainingInDay currentTime =
`ceiling $ 86400 - utctDayTime currentTime` only this is enough

2024-11-25 22:27 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/SharedLogic/Cancel.hs
> +        void $ Redis.hSetExp redisKeyForHset newBooking.id.getId newBooking expirationSeconds
This code is repeated during booking creation. Can be refactored

2024-11-25 22:27 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/UI/Driver.hs
> +        else pure []
Both these functions are very similar. Can you create one common function for these?

2024-11-25 22:27 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Beckn/Init.hs
> +          let score = ceiling $ calculateSortedSetScore booking.startTime
Are we not including lat long in score calculation?

2024-11-26 09:21 UTC, arjuna92 approved these changes

2024-11-27 09:15 UTC, 0utkarsh approved these changes

2024-11-27 09:15 UTC, merged