frontend/fix: added lost and found reminder audio on ride end
nammayatri/nammayatri pull request #9393
Opened 2024-11-21 09:03 UTC by VD321

## Type of Change

- [X] Bugfix
- [] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
Added lost and found reminder audio on ride end.

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-11-22 05:39 UTC, prakharritik submitted a review, later dismissed

2024-11-27 09:13 UTC, spravinkumar9952 requested changes

2024-11-27 09:13 UTC, spravinkumar9952 commented on Frontend/ui-driver/src/RemoteConfigs/Utils.purs
> +      getCityBasedConfig value $ toLower city
if condition not needed here

2024-11-27 09:13 UTC, spravinkumar9952 commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +                                  void $ launchAff $ EHC.flowRunner defaultGlobalState $ playAudioOnRideEnd push
can you move currentStage check to top level, then we can check the when case

2024-11-27 09:13 UTC, spravinkumar9952 commented on Frontend/ui-driver/src/Screens/HomeScreen/View.purs
> +                                  void $ launchAff $ EHC.flowRunner defaultGlobalState $ playAudioOnRideEnd push
even if user close and open also the audio will play. that's expected here ?

2024-11-28 14:05 UTC, VD321 commented on Frontend/ui-driver/src/RemoteConfigs/Utils.purs
> +      getCityBasedConfig value $ toLower city
Removed

2025-01-15 09:03 UTC, prakharritik approved these changes

2025-01-15 09:26 UTC, merged