backend/feat/bbps
nammayatri/nammayatri pull request #9528
Opened 2024-12-02 22:57 UTC by ErasedSoul

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2025-01-10 00:49 UTC, khuzema786 submitted a review, later dismissed

2025-01-10 00:49 UTC, khuzema786 commented on flake.nix
> +      url = "github:nammayatri/shared-kernel/5d3049e4762809cb36b116e570cad03e2637423f";
Revert

2025-01-10 10:36 UTC, 0utkarsh requested changes

2025-01-10 10:36 UTC, 0utkarsh commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/UI/BBPS.hs
> +            splitSettlementDetails = Nothing
This will break all these payments. Will need to pass a json assigning whole amount to marketplace

2025-01-10 10:36 UTC, 0utkarsh commented on Backend/app/rider-platform/rider-app/Main/src/Domain/Action/UI/BBPS.hs
> +  _bbpsConfig <- QBBPSC.findByMerchantId merchantId >>= fromMaybeM (InvalidRequest "BBPS not allowed for this merchant !")
This can be on city basis?

2025-01-13 11:39 UTC, 0utkarsh approved these changes

2025-01-13 11:39 UTC, merged