backend/feat/fare-policy-intercity-source-destination-details
nammayatri/nammayatri pull request #9554
Opened 2024-12-04 15:25 UTC by RahulGupta0706

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables
- [ ] This PR contains API breaking changes

## Motivation and Context

## How did you test it?

## Screenshot of test results

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added integration tests for my changes where possible
- [ ] I tested the changes using integration tests
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable
- [ ] No leak detected in leakcanary

2024-12-04 21:21 UTC, khuzema786 commented on .psc-ide-port
> +15745
Please revert

2024-12-04 21:36 UTC, 0utkarsh requested changes

2024-12-04 21:36 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Beam/FareParameters.hs
> +    stateEntryPermitCharges :: B.C f (Maybe HighPrecMoney),
Let's move this to Fare Parameters Intercity Details

2024-12-04 21:36 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Types/FarePolicy.hs
> +    stateEntryPermitCharges :: Maybe HighPrecMoney,
Should be moved to Fare Policy Intercity Details

2024-12-04 21:36 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Domain/Action/Dashboard/Management/Merchant.hs
> +      stateEntryPermitCharges :: Maybe HighPrecMoney <- readCSVField idx row.stateEntryPermitCharges "State Entry Permit Charges"
`readMaybeCSVField` should be used

2024-12-04 21:36 UTC, 0utkarsh commented on Backend/app/provider-platform/dynamic-offer-driver-app/Main/src/Storage/Queries/FarePolicy.hs
> +      Se.Set BeamFP.stateEntryPermitCharges $ farePolicy.stateEntryPermitCharges,
Migration for this column is missing for both policy and parameters tables

2024-12-10 13:53 UTC, khuzema786 approved these changes

2024-12-10 14:03 UTC, 0utkarsh approved these changes

2024-12-10 14:03 UTC, merged